// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedball/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedball
//     --tz_version 2025b
//     --actions zonedb
//     --language c
//     --scope complete
//     --db_namespace Zonedball
//     --start_year 1800
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025b
//
// Supported Zones: 597 (340 zones, 257 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [1800,2200]
// Accurate Years: [-32767,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1844,2087]
// Lower/Upper Truncated: [False,False]
//
// Estimator Years: [1800,2090]
// Max Buffer Size: 8
//
// Records:
//   Infos: 597
//   Eras: 1956
//   Policies: 134
//   Rules: 2235
//
// Memory (8-bits):
//   Context: 20
//   Rules: 26820
//   Policies: 402
//   Eras: 29340
//   Zones: 4420
//   Links: 3341
//   Registry: 1194
//   Formats: 486
//   Letters: 160
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 75277
//
// Memory (32-bits):
//   Context: 28
//   Rules: 26820
//   Policies: 1072
//   Eras: 39120
//   Zones: 8160
//   Links: 6168
//   Registry: 2388
//   Formats: 486
//   Letters: 216
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 93552
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ZONEDBALL_ZONE_POLICIES_H
#define ACE_TIME_C_ZONEDB_ZONEDBALL_ZONE_POLICIES_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

//---------------------------------------------------------------------------
// Supported policies: 134
//---------------------------------------------------------------------------

extern const AtcZonePolicy kAtcZonedballZonePolicyAN;
extern const AtcZonePolicy kAtcZonedballZonePolicyAQ;
extern const AtcZonePolicy kAtcZonedballZonePolicyAS;
extern const AtcZonePolicy kAtcZonedballZonePolicyAT;
extern const AtcZonePolicy kAtcZonedballZonePolicyAV;
extern const AtcZonePolicy kAtcZonedballZonePolicyAW;
extern const AtcZonePolicy kAtcZonedballZonePolicyAlbania;
extern const AtcZonePolicy kAtcZonedballZonePolicyAlgeria;
extern const AtcZonePolicy kAtcZonedballZonePolicyArg;
extern const AtcZonePolicy kAtcZonedballZonePolicyArmenia;
extern const AtcZonePolicy kAtcZonedballZonePolicyAus;
extern const AtcZonePolicy kAtcZonedballZonePolicyAustria;
extern const AtcZonePolicy kAtcZonedballZonePolicyAzer;
extern const AtcZonePolicy kAtcZonedballZonePolicyBarb;
extern const AtcZonePolicy kAtcZonedballZonePolicyBelgium;
extern const AtcZonePolicy kAtcZonedballZonePolicyBelize;
extern const AtcZonePolicy kAtcZonedballZonePolicyBermuda;
extern const AtcZonePolicy kAtcZonedballZonePolicyBrazil;
extern const AtcZonePolicy kAtcZonedballZonePolicyBulg;
extern const AtcZonePolicy kAtcZonedballZonePolicyC_Eur;
extern const AtcZonePolicy kAtcZonedballZonePolicyCA;
extern const AtcZonePolicy kAtcZonedballZonePolicyCO;
extern const AtcZonePolicy kAtcZonedballZonePolicyCR;
extern const AtcZonePolicy kAtcZonedballZonePolicyCanada;
extern const AtcZonePolicy kAtcZonedballZonePolicyChatham;
extern const AtcZonePolicy kAtcZonedballZonePolicyChicago;
extern const AtcZonePolicy kAtcZonedballZonePolicyChile;
extern const AtcZonePolicy kAtcZonedballZonePolicyCook;
extern const AtcZonePolicy kAtcZonedballZonePolicyCuba;
extern const AtcZonePolicy kAtcZonedballZonePolicyCyprus;
extern const AtcZonePolicy kAtcZonedballZonePolicyCzech;
extern const AtcZonePolicy kAtcZonedballZonePolicyDR;
extern const AtcZonePolicy kAtcZonedballZonePolicyDenver;
extern const AtcZonePolicy kAtcZonedballZonePolicyDetroit;
extern const AtcZonePolicy kAtcZonedballZonePolicyDhaka;
extern const AtcZonePolicy kAtcZonedballZonePolicyE_Eur;
extern const AtcZonePolicy kAtcZonedballZonePolicyE_EurAsia;
extern const AtcZonePolicy kAtcZonedballZonePolicyEU;
extern const AtcZonePolicy kAtcZonedballZonePolicyEUAsia;
extern const AtcZonePolicy kAtcZonedballZonePolicyEcuador;
extern const AtcZonePolicy kAtcZonedballZonePolicyEdm;
extern const AtcZonePolicy kAtcZonedballZonePolicyEgypt;
extern const AtcZonePolicy kAtcZonedballZonePolicyEgyptAsia;
extern const AtcZonePolicy kAtcZonedballZonePolicyEire;
extern const AtcZonePolicy kAtcZonedballZonePolicyFalk;
extern const AtcZonePolicy kAtcZonedballZonePolicyFiji;
extern const AtcZonePolicy kAtcZonedballZonePolicyFinland;
extern const AtcZonePolicy kAtcZonedballZonePolicyFrance;
extern const AtcZonePolicy kAtcZonedballZonePolicyGB_Eire;
extern const AtcZonePolicy kAtcZonedballZonePolicyGermany;
extern const AtcZonePolicy kAtcZonedballZonePolicyGreece;
extern const AtcZonePolicy kAtcZonedballZonePolicyGuam;
extern const AtcZonePolicy kAtcZonedballZonePolicyGuat;
extern const AtcZonePolicy kAtcZonedballZonePolicyHK;
extern const AtcZonePolicy kAtcZonedballZonePolicyHaiti;
extern const AtcZonePolicy kAtcZonedballZonePolicyHalifax;
extern const AtcZonePolicy kAtcZonedballZonePolicyHoliday;
extern const AtcZonePolicy kAtcZonedballZonePolicyHond;
extern const AtcZonePolicy kAtcZonedballZonePolicyHungary;
extern const AtcZonePolicy kAtcZonedballZonePolicyIndianapolis;
extern const AtcZonePolicy kAtcZonedballZonePolicyIran;
extern const AtcZonePolicy kAtcZonedballZonePolicyIraq;
extern const AtcZonePolicy kAtcZonedballZonePolicyItaly;
extern const AtcZonePolicy kAtcZonedballZonePolicyJapan;
extern const AtcZonePolicy kAtcZonedballZonePolicyJordan;
extern const AtcZonePolicy kAtcZonedballZonePolicyKyrgyz;
extern const AtcZonePolicy kAtcZonedballZonePolicyLH;
extern const AtcZonePolicy kAtcZonedballZonePolicyLatvia;
extern const AtcZonePolicy kAtcZonedballZonePolicyLebanon;
extern const AtcZonePolicy kAtcZonedballZonePolicyLibya;
extern const AtcZonePolicy kAtcZonedballZonePolicyLouisville;
extern const AtcZonePolicy kAtcZonedballZonePolicyMacau;
extern const AtcZonePolicy kAtcZonedballZonePolicyMalta;
extern const AtcZonePolicy kAtcZonedballZonePolicyMarengo;
extern const AtcZonePolicy kAtcZonedballZonePolicyMauritius;
extern const AtcZonePolicy kAtcZonedballZonePolicyMenominee;
extern const AtcZonePolicy kAtcZonedballZonePolicyMexico;
extern const AtcZonePolicy kAtcZonedballZonePolicyMoldova;
extern const AtcZonePolicy kAtcZonedballZonePolicyMoncton;
extern const AtcZonePolicy kAtcZonedballZonePolicyMongol;
extern const AtcZonePolicy kAtcZonedballZonePolicyMorocco;
extern const AtcZonePolicy kAtcZonedballZonePolicyNBorneo;
extern const AtcZonePolicy kAtcZonedballZonePolicyNC;
extern const AtcZonePolicy kAtcZonedballZonePolicyNT_YK;
extern const AtcZonePolicy kAtcZonedballZonePolicyNYC;
extern const AtcZonePolicy kAtcZonedballZonePolicyNZ;
extern const AtcZonePolicy kAtcZonedballZonePolicyNamibia;
extern const AtcZonePolicy kAtcZonedballZonePolicyNic;
extern const AtcZonePolicy kAtcZonedballZonePolicyPRC;
extern const AtcZonePolicy kAtcZonedballZonePolicyPakistan;
extern const AtcZonePolicy kAtcZonedballZonePolicyPalestine;
extern const AtcZonePolicy kAtcZonedballZonePolicyPara;
extern const AtcZonePolicy kAtcZonedballZonePolicyPerry;
extern const AtcZonePolicy kAtcZonedballZonePolicyPeru;
extern const AtcZonePolicy kAtcZonedballZonePolicyPhil;
extern const AtcZonePolicy kAtcZonedballZonePolicyPike;
extern const AtcZonePolicy kAtcZonedballZonePolicyPoland;
extern const AtcZonePolicy kAtcZonedballZonePolicyPort;
extern const AtcZonePolicy kAtcZonedballZonePolicyPulaski;
extern const AtcZonePolicy kAtcZonedballZonePolicyROK;
extern const AtcZonePolicy kAtcZonedballZonePolicyRegina;
extern const AtcZonePolicy kAtcZonedballZonePolicyRomania;
extern const AtcZonePolicy kAtcZonedballZonePolicyRussia;
extern const AtcZonePolicy kAtcZonedballZonePolicyRussiaAsia;
extern const AtcZonePolicy kAtcZonedballZonePolicySA;
extern const AtcZonePolicy kAtcZonedballZonePolicySalv;
extern const AtcZonePolicy kAtcZonedballZonePolicySanLuis;
extern const AtcZonePolicy kAtcZonedballZonePolicyShang;
extern const AtcZonePolicy kAtcZonedballZonePolicySovietZone;
extern const AtcZonePolicy kAtcZonedballZonePolicySpain;
extern const AtcZonePolicy kAtcZonedballZonePolicySpainAfrica;
extern const AtcZonePolicy kAtcZonedballZonePolicyStJohns;
extern const AtcZonePolicy kAtcZonedballZonePolicyStarke;
extern const AtcZonePolicy kAtcZonedballZonePolicySudan;
extern const AtcZonePolicy kAtcZonedballZonePolicySwift;
extern const AtcZonePolicy kAtcZonedballZonePolicySwiss;
extern const AtcZonePolicy kAtcZonedballZonePolicySyria;
extern const AtcZonePolicy kAtcZonedballZonePolicyTaiwan;
extern const AtcZonePolicy kAtcZonedballZonePolicyThule;
extern const AtcZonePolicy kAtcZonedballZonePolicyTonga;
extern const AtcZonePolicy kAtcZonedballZonePolicyToronto;
extern const AtcZonePolicy kAtcZonedballZonePolicyTroll;
extern const AtcZonePolicy kAtcZonedballZonePolicyTunisia;
extern const AtcZonePolicy kAtcZonedballZonePolicyTurkey;
extern const AtcZonePolicy kAtcZonedballZonePolicyUS;
extern const AtcZonePolicy kAtcZonedballZonePolicyUruguay;
extern const AtcZonePolicy kAtcZonedballZonePolicyVanc;
extern const AtcZonePolicy kAtcZonedballZonePolicyVanuatu;
extern const AtcZonePolicy kAtcZonedballZonePolicyVincennes;
extern const AtcZonePolicy kAtcZonedballZonePolicyW_Eur;
extern const AtcZonePolicy kAtcZonedballZonePolicyWS;
extern const AtcZonePolicy kAtcZonedballZonePolicyWinn;
extern const AtcZonePolicy kAtcZonedballZonePolicyYukon;
extern const AtcZonePolicy kAtcZonedballZonePolicyZion;


//---------------------------------------------------------------------------
// Unsupported zone policies: 0
//---------------------------------------------------------------------------



//---------------------------------------------------------------------------
// Notable zone policies: 27
//---------------------------------------------------------------------------

// Barb {SAVE '0:30' different from 1:00}
// Belize {
//   LETTER '-0530' not single character,
//   LETTER 'CDT' not single character,
//   LETTER 'CPT' not single character,
//   LETTER 'CST' not single character,
//   LETTER 'CWT' not single character,
//   SAVE '0:30' different from 1:00,
// }
// CA {AT '2:01' not multiple of :15 min}
// Cook {SAVE '0:30' different from 1:00}
// DR {
//   LETTER '-0430' not single character,
//   LETTER 'EDT' not single character,
//   LETTER 'EST' not single character,
//   SAVE '0:30' different from 1:00,
// }
// Eire {SAVE '-1:00' is a negative DST}
// France {SAVE '2:00' different from 1:00}
// GB-Eire {
//   LETTER 'BDST' not single character,
//   LETTER 'BST' not single character,
//   LETTER 'GMT' not single character,
//   SAVE '2:00' different from 1:00,
// }
// Germany {SAVE '2:00' different from 1:00}
// Guam {
//   AT '0:01' not multiple of :15 min,
//   AT '2:01' not multiple of :15 min,
// }
// LH {SAVE '0:30' different from 1:00}
// Louisville {AT '0:01' not multiple of :15 min}
// Moncton {AT '0:01' not multiple of :15 min}
// Morocco {SAVE '-1:00' is a negative DST}
// NBorneo {SAVE '0:20' different from 1:00}
// NZ {SAVE '0:30' different from 1:00}
// Namibia {
//   LETTER 'CAT' not single character,
//   LETTER 'WAT' not single character,
//   SAVE '-1:00' is a negative DST,
// }
// Palestine {AT '0:01' not multiple of :15 min}
// Port {SAVE '2:00' different from 1:00}
// Russia {
//   LETTER '+05' not single character,
//   LETTER 'MDST' not single character,
//   LETTER 'MMT' not single character,
//   LETTER 'MSD' not single character,
//   LETTER 'MSK' not single character,
//   LETTER 'MST' not single character,
//   SAVE '2:00' different from 1:00,
// }
// SovietZone {SAVE '2:00' different from 1:00}
// Spain {SAVE '2:00' different from 1:00}
// StJohns {
//   AT '0:01' not multiple of :15 min,
//   LETTER 'DD' not single character,
//   SAVE '2:00' different from 1:00,
// }
// Troll {
//   LETTER '+00' not single character,
//   LETTER '+02' not single character,
//   SAVE '2:00' different from 1:00,
// }
// Uruguay {
//   SAVE '0:30' different from 1:00,
//   SAVE '1:30' different from 1:00,
// }
// Yukon {
//   LETTER 'DD' not single character,
//   SAVE '2:00' different from 1:00,
// }
// Zion {
//   LETTER 'DD' not single character,
//   SAVE '2:00' different from 1:00,
// }


//---------------------------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif
