// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/acetimec/src/zonedball/tzfiles
//     --output_dir /home/brian/src/acetimec/src/zonedball
//     --tz_version 2023d
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace AtcAll
//     --start_year 1800
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2023d
//
// Supported Zones: 596 (351 zones, 245 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [1800,2200]
// Accurate Years: [-32767,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1844,2087]
// Lower/Upper Truncated: [False,False]
//
// Estimator Years: [1800,2090]
// Max Buffer Size: 8
//
// Records:
//   Infos: 596
//   Eras: 1961
//   Policies: 134
//   Rules: 2238
//
// Memory (8-bits):
//   Context: 16
//   Rules: 26856
//   Policies: 402
//   Eras: 29415
//   Zones: 4563
//   Links: 3185
//   Registry: 1192
//   Formats: 1032
//   Letters: 160
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 75897
//
// Memory (32-bits):
//   Context: 24
//   Rules: 26856
//   Policies: 1072
//   Eras: 39220
//   Zones: 8424
//   Links: 5880
//   Registry: 2384
//   Formats: 1032
//   Letters: 216
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 94184
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATCALL_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ATCALL_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcAllZoneRegistrySize 351
extern const AtcZoneInfo * const kAtcAllZoneRegistry[351];

// Zones and Links
#define kAtcAllZoneAndLinkRegistrySize 596
extern const AtcZoneInfo * const kAtcAllZoneAndLinkRegistry[596];

#ifdef __cplusplus
}
#endif

#endif
