// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedball/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedball
//     --tz_version 2025a
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace AtcAll
//     --start_year 1800
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025a
//
// Supported Zones: 596 (339 zones, 257 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [1800,2200]
// Accurate Years: [-32767,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1844,2087]
// Lower/Upper Truncated: [False,False]
//
// Estimator Years: [1800,2090]
// Max Buffer Size: 8
//
// Records:
//   Infos: 596
//   Eras: 1942
//   Policies: 134
//   Rules: 2235
//
// Memory (8-bits):
//   Context: 16
//   Rules: 26820
//   Policies: 402
//   Eras: 29130
//   Zones: 4407
//   Links: 3341
//   Registry: 1192
//   Formats: 486
//   Letters: 160
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 75030
//
// Memory (32-bits):
//   Context: 24
//   Rules: 26820
//   Policies: 1072
//   Eras: 38840
//   Zones: 8136
//   Links: 6168
//   Registry: 2384
//   Formats: 486
//   Letters: 216
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 93222
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATCALL_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ATCALL_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcAllZoneRegistrySize 339
extern const AtcZoneInfo * const kAtcAllZoneRegistry[339];

// Zones and Links
#define kAtcAllZoneAndLinkRegistrySize 596
extern const AtcZoneInfo * const kAtcAllZoneAndLinkRegistry[596];

#ifdef __cplusplus
}
#endif

#endif
