// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/acetimec/src/zonedball/tzfiles
//     --output_dir /home/brian/src/acetimec/src/zonedball
//     --tz_version 2023d
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace AtcAll
//     --start_year 1800
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2023d
//
// Supported Zones: 596 (351 zones, 245 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [1800,2200]
// Accurate Years: [-32767,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1844,2087]
// Lower/Upper Truncated: [False,False]
//
// Estimator Years: [1800,2090]
// Max Buffer Size: 8
//
// Records:
//   Infos: 596
//   Eras: 1961
//   Policies: 134
//   Rules: 2238
//
// Memory (8-bits):
//   Context: 16
//   Rules: 26856
//   Policies: 402
//   Eras: 29415
//   Zones: 4563
//   Links: 3185
//   Registry: 1192
//   Formats: 1032
//   Letters: 160
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 75897
//
// Memory (32-bits):
//   Context: 24
//   Rules: 26856
//   Policies: 1072
//   Eras: 39220
//   Zones: 8424
//   Links: 5880
//   Registry: 2384
//   Formats: 1032
//   Letters: 216
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 94184
//
// DO NOT EDIT

#include "zone_infos.h"
#include "zone_registry.h"

//---------------------------------------------------------------------------
// Zone Info registry. Sorted by zoneId.
//---------------------------------------------------------------------------
const AtcZoneInfo * const kAtcAllZoneRegistry[351]  = {
  &kAtcAllZoneAmerica_St_Johns, // 0x04b14e6e, America/St_Johns
  &kAtcAllZoneAmerica_North_Dakota_New_Salem, // 0x04f9958e, America/North_Dakota/New_Salem
  &kAtcAllZoneAsia_Jakarta, // 0x0506ab50, Asia/Jakarta
  &kAtcAllZoneAmerica_Mazatlan, // 0x0532189e, America/Mazatlan
  &kAtcAllZonePacific_Fakaofo, // 0x06532bba, Pacific/Fakaofo
  &kAtcAllZoneAmerica_Hermosillo, // 0x065d21c4, America/Hermosillo
  &kAtcAllZoneAsia_Tbilisi, // 0x0903e442, Asia/Tbilisi
  &kAtcAllZoneAmerica_Indiana_Tell_City, // 0x09263612, America/Indiana/Tell_City
  &kAtcAllZoneAmerica_Boa_Vista, // 0x0a7b7efe, America/Boa_Vista
  &kAtcAllZoneAsia_Colombo, // 0x0af0e91d, Asia/Colombo
  &kAtcAllZoneCET, // 0x0b87d921, CET
  &kAtcAllZoneEET, // 0x0b87e1a3, EET
  &kAtcAllZoneEST, // 0x0b87e371, EST
  &kAtcAllZoneHST, // 0x0b87f034, HST
  &kAtcAllZoneMET, // 0x0b8803ab, MET
  &kAtcAllZoneMST, // 0x0b880579, MST
  &kAtcAllZoneWET, // 0x0b882e35, WET
  &kAtcAllZoneAmerica_Guatemala, // 0x0c8259f7, America/Guatemala
  &kAtcAllZoneAfrica_Monrovia, // 0x0ce90385, Africa/Monrovia
  &kAtcAllZoneAntarctica_Rothera, // 0x0e86d203, Antarctica/Rothera
  &kAtcAllZoneAustralia_Melbourne, // 0x0fe559a3, Australia/Melbourne
  &kAtcAllZoneAmerica_Sao_Paulo, // 0x1063bfc9, America/Sao_Paulo
  &kAtcAllZoneAmerica_Indiana_Vevay, // 0x10aca054, America/Indiana/Vevay
  &kAtcAllZoneAmerica_Scoresbysund, // 0x123f8d2a, America/Scoresbysund
  &kAtcAllZoneAsia_Samarkand, // 0x13ae5104, Asia/Samarkand
  &kAtcAllZoneAsia_Amman, // 0x148d21bc, Asia/Amman
  &kAtcAllZoneAsia_Aqtau, // 0x148f710e, Asia/Aqtau
  &kAtcAllZoneAsia_Chita, // 0x14ae863b, Asia/Chita
  &kAtcAllZoneAsia_Dhaka, // 0x14c07b8b, Asia/Dhaka
  &kAtcAllZoneAsia_Dubai, // 0x14c79f77, Asia/Dubai
  &kAtcAllZoneAmerica_Bahia_Banderas, // 0x14f6329a, America/Bahia_Banderas
  &kAtcAllZoneAsia_Kabul, // 0x153b5601, Asia/Kabul
  &kAtcAllZoneAsia_Macau, // 0x155f88b9, Asia/Macau
  &kAtcAllZoneAsia_Qatar, // 0x15a8330b, Asia/Qatar
  &kAtcAllZoneAsia_Seoul, // 0x15ce82da, Asia/Seoul
  &kAtcAllZoneAsia_Tokyo, // 0x15e606a8, Asia/Tokyo
  &kAtcAllZoneAsia_Tomsk, // 0x15e60e60, Asia/Tomsk
  &kAtcAllZoneAsia_Thimphu, // 0x170380d1, Asia/Thimphu
  &kAtcAllZoneAmerica_Guayaquil, // 0x17e64958, America/Guayaquil
  &kAtcAllZoneAmerica_Kentucky_Louisville, // 0x1a21024b, America/Kentucky/Louisville
  &kAtcAllZoneAsia_Pontianak, // 0x1a76c057, Asia/Pontianak
  &kAtcAllZoneAmerica_New_York, // 0x1e2a7654, America/New_York
  &kAtcAllZoneAsia_Baku, // 0x1fa788b5, Asia/Baku
  &kAtcAllZoneAsia_Dili, // 0x1fa8c394, Asia/Dili
  &kAtcAllZoneAsia_Gaza, // 0x1faa4875, Asia/Gaza
  &kAtcAllZoneAsia_Hovd, // 0x1fab0fe3, Asia/Hovd
  &kAtcAllZoneAsia_Omsk, // 0x1faeddac, Asia/Omsk
  &kAtcAllZoneAsia_Oral, // 0x1faef0a0, Asia/Oral
  &kAtcAllZoneAsia_Ho_Chi_Minh, // 0x20f2d127, Asia/Ho_Chi_Minh
  &kAtcAllZoneAsia_Damascus, // 0x20fbb063, Asia/Damascus
  &kAtcAllZonePacific_Apia, // 0x23359b5e, Pacific/Apia
  &kAtcAllZonePacific_Fiji, // 0x23383ba5, Pacific/Fiji
  &kAtcAllZonePacific_Guam, // 0x2338f9ed, Pacific/Guam
  &kAtcAllZonePacific_Niue, // 0x233ca014, Pacific/Niue
  &kAtcAllZoneAustralia_Adelaide, // 0x2428e8a3, Australia/Adelaide
  &kAtcAllZonePacific_Auckland, // 0x25062f86, Pacific/Auckland
  &kAtcAllZonePacific_Tongatapu, // 0x262ca836, Pacific/Tongatapu
  &kAtcAllZoneAmerica_Monterrey, // 0x269a1deb, America/Monterrey
  &kAtcAllZoneAustralia_Darwin, // 0x2876bdff, Australia/Darwin
  &kAtcAllZoneAsia_Famagusta, // 0x289b4f8b, Asia/Famagusta
  &kAtcAllZoneAmerica_Indiana_Vincennes, // 0x28a0b212, America/Indiana/Vincennes
  &kAtcAllZoneAmerica_Indiana_Indianapolis, // 0x28a669a4, America/Indiana/Indianapolis
  &kAtcAllZoneAsia_Vladivostok, // 0x29de34a8, Asia/Vladivostok
  &kAtcAllZoneAmerica_Fortaleza, // 0x2ad018ee, America/Fortaleza
  &kAtcAllZoneAmerica_Vancouver, // 0x2c6f6b1f, America/Vancouver
  &kAtcAllZoneAmerica_Iqaluit, // 0x2de310bf, America/Iqaluit
  &kAtcAllZonePacific_Chatham, // 0x2f0de999, Pacific/Chatham
  &kAtcAllZoneAmerica_Indiana_Marengo, // 0x2feeee72, America/Indiana/Marengo
  &kAtcAllZoneEurope_Tallinn, // 0x30c4e096, Europe/Tallinn
  &kAtcAllZoneAsia_Ulaanbaatar, // 0x30f0cc4e, Asia/Ulaanbaatar
  &kAtcAllZoneAmerica_Argentina_Ushuaia, // 0x320dcdde, America/Argentina/Ushuaia
  &kAtcAllZoneAustralia_Hobart, // 0x32bf951a, Australia/Hobart
  &kAtcAllZoneAsia_Dushanbe, // 0x32fc5c3c, Asia/Dushanbe
  &kAtcAllZoneAtlantic_South_Georgia, // 0x33013174, Atlantic/South_Georgia
  &kAtcAllZoneAmerica_Phoenix, // 0x34b5af01, America/Phoenix
  &kAtcAllZoneAntarctica_Mawson, // 0x399cd863, Antarctica/Mawson
  &kAtcAllZoneAmerica_Caracas, // 0x3be064f4, America/Caracas
  &kAtcAllZoneAmerica_Cayenne, // 0x3c617269, America/Cayenne
  &kAtcAllZoneAtlantic_Bermuda, // 0x3d4bb1c4, Atlantic/Bermuda
  &kAtcAllZoneAmerica_Managua, // 0x3d5e7600, America/Managua
  &kAtcAllZoneAmerica_Argentina_San_Juan, // 0x3e1009bd, America/Argentina/San_Juan
  &kAtcAllZoneAmerica_Argentina_San_Luis, // 0x3e11238c, America/Argentina/San_Luis
  &kAtcAllZoneEurope_Volgograd, // 0x3ed0f389, Europe/Volgograd
  &kAtcAllZoneAmerica_Fort_Nelson, // 0x3f437e0f, America/Fort_Nelson
  &kAtcAllZoneEtc_GMT_PLUS_10, // 0x3f8f1cc4, Etc/GMT+10
  &kAtcAllZoneEtc_GMT_PLUS_11, // 0x3f8f1cc5, Etc/GMT+11
  &kAtcAllZoneEtc_GMT_PLUS_12, // 0x3f8f1cc6, Etc/GMT+12
  &kAtcAllZoneEtc_GMT_10, // 0x3f8f2546, Etc/GMT-10
  &kAtcAllZoneEtc_GMT_11, // 0x3f8f2547, Etc/GMT-11
  &kAtcAllZoneEtc_GMT_12, // 0x3f8f2548, Etc/GMT-12
  &kAtcAllZoneEtc_GMT_13, // 0x3f8f2549, Etc/GMT-13
  &kAtcAllZoneEtc_GMT_14, // 0x3f8f254a, Etc/GMT-14
  &kAtcAllZoneAntarctica_Palmer, // 0x40962f4f, Antarctica/Palmer
  &kAtcAllZoneEurope_Athens, // 0x4318fa27, Europe/Athens
  &kAtcAllZoneAmerica_Indiana_Winamac, // 0x4413fa69, America/Indiana/Winamac
  &kAtcAllZoneEurope_Berlin, // 0x44644c20, Europe/Berlin
  &kAtcAllZoneIndian_Chagos, // 0x456f7c3c, Indian/Chagos
  &kAtcAllZoneAsia_Ust_Nera, // 0x4785f921, Asia/Ust-Nera
  &kAtcAllZoneEurope_Dublin, // 0x4a275f62, Europe/Dublin
  &kAtcAllZoneAsia_Nicosia, // 0x4b0fcf78, Asia/Nicosia
  &kAtcAllZoneAmerica_Chicago, // 0x4b92b5d4, America/Chicago
  &kAtcAllZoneAustralia_Sydney, // 0x4d1e9776, Australia/Sydney
  &kAtcAllZoneAntarctica_Vostok, // 0x4f966fd4, Antarctica/Vostok
  &kAtcAllZoneAustralia_Brisbane, // 0x4fedc9c0, Australia/Brisbane
  &kAtcAllZoneAmerica_Asuncion, // 0x50ec79a6, America/Asuncion
  &kAtcAllZoneAsia_Karachi, // 0x527f5245, Asia/Karachi
  &kAtcAllZonePacific_Gambier, // 0x53720c3a, Pacific/Gambier
  &kAtcAllZoneAmerica_Whitehorse, // 0x54e0e3e8, America/Whitehorse
  &kAtcAllZoneAmerica_Martinique, // 0x551e84c5, America/Martinique
  &kAtcAllZoneAmerica_Jamaica, // 0x565dad6c, America/Jamaica
  &kAtcAllZoneAsia_Hong_Kong, // 0x577f28ac, Asia/Hong_Kong
  &kAtcAllZonePacific_Marquesas, // 0x57ca7135, Pacific/Marquesas
  &kAtcAllZoneAmerica_Miquelon, // 0x59674330, America/Miquelon
  &kAtcAllZoneAmerica_Anchorage, // 0x5a79260e, America/Anchorage
  &kAtcAllZoneAsia_Jerusalem, // 0x5becd23a, Asia/Jerusalem
  &kAtcAllZoneEurope_Lisbon, // 0x5c00a70b, Europe/Lisbon
  &kAtcAllZoneAtlantic_Cape_Verde, // 0x5c5e1772, Atlantic/Cape_Verde
  &kAtcAllZoneEurope_London, // 0x5c6a84ae, Europe/London
  &kAtcAllZoneEurope_Madrid, // 0x5dbd1535, Europe/Madrid
  &kAtcAllZoneAmerica_Moncton, // 0x5e07fe24, America/Moncton
  &kAtcAllZonePacific_Bougainville, // 0x5e10f7a4, Pacific/Bougainville
  &kAtcAllZoneEurope_Moscow, // 0x5ec266fc, Europe/Moscow
  &kAtcAllZoneAmerica_Argentina_Jujuy, // 0x5f2f46c5, America/Argentina/Jujuy
  &kAtcAllZoneAmerica_Argentina_Salta, // 0x5fc73403, America/Argentina/Salta
  &kAtcAllZonePacific_Pago_Pago, // 0x603aebd0, Pacific/Pago_Pago
  &kAtcAllZoneAfrica_Sao_Tome, // 0x61b319d1, Africa/Sao_Tome
  &kAtcAllZoneAmerica_Costa_Rica, // 0x63ff66be, America/Costa_Rica
  &kAtcAllZoneAsia_Qostanay, // 0x654fe522, Asia/Qostanay
  &kAtcAllZoneAmerica_Indiana_Knox, // 0x6554adc9, America/Indiana/Knox
  &kAtcAllZoneEurope_Prague, // 0x65ee5d48, Europe/Prague
  &kAtcAllZoneAmerica_Puerto_Rico, // 0x6752ca31, America/Puerto_Rico
  &kAtcAllZoneAsia_Novokuznetsk, // 0x69264f93, Asia/Novokuznetsk
  &kAtcAllZoneAmerica_Tijuana, // 0x6aa1df72, America/Tijuana
  &kAtcAllZoneAsia_Makassar, // 0x6aa21c85, Asia/Makassar
  &kAtcAllZoneEurope_Helsinki, // 0x6ab2975b, Europe/Helsinki
  &kAtcAllZoneAmerica_Porto_Velho, // 0x6b1aac77, America/Porto_Velho
  &kAtcAllZoneEurope_Samara, // 0x6bc0b139, Europe/Samara
  &kAtcAllZoneAmerica_Edmonton, // 0x6cb9484a, America/Edmonton
  &kAtcAllZoneAmerica_Dawson_Creek, // 0x6cf24e5b, America/Dawson_Creek
  &kAtcAllZoneAmerica_Grand_Turk, // 0x6e216197, America/Grand_Turk
  &kAtcAllZoneEurope_Tirane, // 0x6ea95b47, Europe/Tirane
  &kAtcAllZoneAmerica_Araguaina, // 0x6f9a3aef, America/Araguaina
  &kAtcAllZoneAsia_Qyzylorda, // 0x71282e81, Asia/Qyzylorda
  &kAtcAllZoneAsia_Kolkata, // 0x72c06cd9, Asia/Kolkata
  &kAtcAllZoneAmerica_Ciudad_Juarez, // 0x7347fc60, America/Ciudad_Juarez
  &kAtcAllZoneEurope_Vienna, // 0x734cc2e5, Europe/Vienna
  &kAtcAllZoneAsia_Kamchatka, // 0x73baf9d7, Asia/Kamchatka
  &kAtcAllZoneAmerica_Santarem, // 0x740caec1, America/Santarem
  &kAtcAllZoneAmerica_Santiago, // 0x7410c9bc, America/Santiago
  &kAtcAllZoneEurope_Warsaw, // 0x75185c19, Europe/Warsaw
  &kAtcAllZoneAmerica_El_Salvador, // 0x752ad652, America/El_Salvador
  &kAtcAllZoneAfrica_Bissau, // 0x75564141, Africa/Bissau
  &kAtcAllZoneAmerica_Santo_Domingo, // 0x75a0d177, America/Santo_Domingo
  &kAtcAllZoneAfrica_Cairo, // 0x77f8e228, Africa/Cairo
  &kAtcAllZoneAfrica_Ceuta, // 0x77fb46ec, Africa/Ceuta
  &kAtcAllZoneAfrica_Lagos, // 0x789bb5d0, Africa/Lagos
  &kAtcAllZoneAfrica_Windhoek, // 0x789c9bd3, Africa/Windhoek
  &kAtcAllZoneAmerica_Toronto, // 0x792e851b, America/Toronto
  &kAtcAllZoneAfrica_Tunis, // 0x79378e6d, Africa/Tunis
  &kAtcAllZoneIndian_Mauritius, // 0x7b09c02a, Indian/Mauritius
  &kAtcAllZoneAtlantic_Stanley, // 0x7bb3e1c4, Atlantic/Stanley
  &kAtcAllZoneEurope_Zurich, // 0x7d8195b9, Europe/Zurich
  &kAtcAllZoneAsia_Kuching, // 0x801b003b, Asia/Kuching
  &kAtcAllZoneAtlantic_Madeira, // 0x81b5c037, Atlantic/Madeira
  &kAtcAllZonePacific_Kiritimati, // 0x8305073a, Pacific/Kiritimati
  &kAtcAllZoneAmerica_Metlakatla, // 0x84de2686, America/Metlakatla
  &kAtcAllZoneAsia_Yakutsk, // 0x87bb3a9e, Asia/Yakutsk
  &kAtcAllZoneAmerica_Chihuahua, // 0x8827d776, America/Chihuahua
  &kAtcAllZonePacific_Pitcairn, // 0x8837d8bd, Pacific/Pitcairn
  &kAtcAllZonePacific_Efate, // 0x8a2bce28, Pacific/Efate
  &kAtcAllZonePacific_Nauru, // 0x8acc41ae, Pacific/Nauru
  &kAtcAllZoneEST5EDT, // 0x8adc72a3, EST5EDT
  &kAtcAllZonePacific_Palau, // 0x8af04a36, Pacific/Palau
  &kAtcAllZoneAmerica_Winnipeg, // 0x8c7dafc7, America/Winnipeg
  &kAtcAllZoneAustralia_Eucla, // 0x8cf99e44, Australia/Eucla
  &kAtcAllZoneAmerica_Argentina_Catamarca, // 0x8d40986b, America/Argentina/Catamarca
  &kAtcAllZoneAustralia_Perth, // 0x8db8269d, Australia/Perth
  &kAtcAllZonePacific_Kwajalein, // 0x8e216759, Pacific/Kwajalein
  &kAtcAllZoneAmerica_Port_au_Prince, // 0x8e4a7bdc, America/Port-au-Prince
  &kAtcAllZoneAfrica_Maputo, // 0x8e6ca1f0, Africa/Maputo
  &kAtcAllZonePacific_Norfolk, // 0x8f4eb4be, Pacific/Norfolk
  &kAtcAllZoneAsia_Yerevan, // 0x9185c8cc, Asia/Yerevan
  &kAtcAllZoneAmerica_Detroit, // 0x925cfbc1, America/Detroit
  &kAtcAllZoneAsia_Choibalsan, // 0x928aa4a6, Asia/Choibalsan
  &kAtcAllZoneAntarctica_Macquarie, // 0x92f47626, Antarctica/Macquarie
  &kAtcAllZoneAmerica_Belize, // 0x93256c81, America/Belize
  &kAtcAllZoneAmerica_Bogota, // 0x93d7bc62, America/Bogota
  &kAtcAllZoneAsia_Pyongyang, // 0x93ed1c8e, Asia/Pyongyang
  &kAtcAllZoneAmerica_Indiana_Petersburg, // 0x94ac7acc, America/Indiana/Petersburg
  &kAtcAllZoneAmerica_Cancun, // 0x953331be, America/Cancun
  &kAtcAllZoneAmerica_Glace_Bay, // 0x9681f8dd, America/Glace_Bay
  &kAtcAllZoneAsia_Khandyga, // 0x9685a4d9, Asia/Khandyga
  &kAtcAllZoneAmerica_Cuiaba, // 0x969a52eb, America/Cuiaba
  &kAtcAllZoneAmerica_Dawson, // 0x978d8d12, America/Dawson
  &kAtcAllZoneAmerica_Denver, // 0x97d10b2a, America/Denver
  &kAtcAllZoneAmerica_Bahia, // 0x97d815fb, America/Bahia
  &kAtcAllZoneAmerica_Belem, // 0x97da580b, America/Belem
  &kAtcAllZoneAmerica_Boise, // 0x97dfc8d8, America/Boise
  &kAtcAllZoneEurope_Andorra, // 0x97f6764b, Europe/Andorra
  &kAtcAllZoneAmerica_Adak, // 0x97fe49d7, America/Adak
  &kAtcAllZoneAmerica_Lima, // 0x980468c9, America/Lima
  &kAtcAllZoneAmerica_Nome, // 0x98059b15, America/Nome
  &kAtcAllZoneAmerica_Nuuk, // 0x9805b5a9, America/Nuuk
  &kAtcAllZoneIndian_Maldives, // 0x9869681c, Indian/Maldives
  &kAtcAllZoneAmerica_Sitka, // 0x99104ce2, America/Sitka
  &kAtcAllZoneAmerica_Thule, // 0x9921dd68, America/Thule
  &kAtcAllZonePacific_Rarotonga, // 0x9981a3b0, Pacific/Rarotonga
  &kAtcAllZoneAsia_Kathmandu, // 0x9a96ce6f, Asia/Kathmandu
  &kAtcAllZoneAmerica_North_Dakota_Beulah, // 0x9b52b384, America/North_Dakota/Beulah
  &kAtcAllZoneEurope_Budapest, // 0x9ce0197c, Europe/Budapest
  &kAtcAllZoneAsia_Baghdad, // 0x9ceffbed, Asia/Baghdad
  &kAtcAllZoneEtc_GMT_PLUS_1, // 0x9d13da14, Etc/GMT+1
  &kAtcAllZoneEtc_GMT_PLUS_2, // 0x9d13da15, Etc/GMT+2
  &kAtcAllZoneEtc_GMT_PLUS_3, // 0x9d13da16, Etc/GMT+3
  &kAtcAllZoneEtc_GMT_PLUS_4, // 0x9d13da17, Etc/GMT+4
  &kAtcAllZoneEtc_GMT_PLUS_5, // 0x9d13da18, Etc/GMT+5
  &kAtcAllZoneEtc_GMT_PLUS_6, // 0x9d13da19, Etc/GMT+6
  &kAtcAllZoneEtc_GMT_PLUS_7, // 0x9d13da1a, Etc/GMT+7
  &kAtcAllZoneEtc_GMT_PLUS_8, // 0x9d13da1b, Etc/GMT+8
  &kAtcAllZoneEtc_GMT_PLUS_9, // 0x9d13da1c, Etc/GMT+9
  &kAtcAllZoneEtc_GMT_1, // 0x9d13da56, Etc/GMT-1
  &kAtcAllZoneEtc_GMT_2, // 0x9d13da57, Etc/GMT-2
  &kAtcAllZoneEtc_GMT_3, // 0x9d13da58, Etc/GMT-3
  &kAtcAllZoneEtc_GMT_4, // 0x9d13da59, Etc/GMT-4
  &kAtcAllZoneEtc_GMT_5, // 0x9d13da5a, Etc/GMT-5
  &kAtcAllZoneEtc_GMT_6, // 0x9d13da5b, Etc/GMT-6
  &kAtcAllZoneEtc_GMT_7, // 0x9d13da5c, Etc/GMT-7
  &kAtcAllZoneEtc_GMT_8, // 0x9d13da5d, Etc/GMT-8
  &kAtcAllZoneEtc_GMT_9, // 0x9d13da5e, Etc/GMT-9
  &kAtcAllZoneAmerica_Rio_Branco, // 0x9d352764, America/Rio_Branco
  &kAtcAllZoneAsia_Bangkok, // 0x9d6e3aaf, Asia/Bangkok
  &kAtcAllZoneAfrica_El_Aaiun, // 0x9d6fb118, Africa/El_Aaiun
  &kAtcAllZoneAmerica_North_Dakota_Center, // 0x9da42814, America/North_Dakota/Center
  &kAtcAllZoneAsia_Barnaul, // 0x9dba4997, Asia/Barnaul
  &kAtcAllZoneAfrica_Tripoli, // 0x9dfebd3d, Africa/Tripoli
  &kAtcAllZoneEurope_Istanbul, // 0x9e09d6e6, Europe/Istanbul
  &kAtcAllZoneAfrica_Ndjamena, // 0x9fe09898, Africa/Ndjamena
  &kAtcAllZoneAmerica_Guyana, // 0x9ff7bd0b, America/Guyana
  &kAtcAllZoneAmerica_Havana, // 0xa0e15675, America/Havana
  &kAtcAllZoneAsia_Novosibirsk, // 0xa2a435cb, Asia/Novosibirsk
  &kAtcAllZoneEurope_Kyiv, // 0xa2c1e347, Europe/Kyiv
  &kAtcAllZoneEurope_Riga, // 0xa2c57587, Europe/Riga
  &kAtcAllZoneEurope_Rome, // 0xa2c58fd7, Europe/Rome
  &kAtcAllZoneAmerica_Inuvik, // 0xa42189fc, America/Inuvik
  &kAtcAllZoneAmerica_Argentina_La_Rioja, // 0xa46b7eef, America/Argentina/La_Rioja
  &kAtcAllZoneAsia_Almaty, // 0xa61f41fa, Asia/Almaty
  &kAtcAllZoneAsia_Anadyr, // 0xa63cebd1, Asia/Anadyr
  &kAtcAllZoneAsia_Aqtobe, // 0xa67dcc4e, Asia/Aqtobe
  &kAtcAllZoneAsia_Atyrau, // 0xa6b6e068, Asia/Atyrau
  &kAtcAllZoneAmerica_Juneau, // 0xa6f13e2e, America/Juneau
  &kAtcAllZoneAustralia_Lord_Howe, // 0xa748b67d, Australia/Lord_Howe
  &kAtcAllZonePacific_Port_Moresby, // 0xa7ba7f68, Pacific/Port_Moresby
  &kAtcAllZoneAsia_Beirut, // 0xa7f3d5fd, Asia/Beirut
  &kAtcAllZoneAfrica_Nairobi, // 0xa87ab57e, Africa/Nairobi
  &kAtcAllZonePacific_Galapagos, // 0xa952f752, Pacific/Galapagos
  &kAtcAllZoneAmerica_Argentina_Mendoza, // 0xa9f72d5c, America/Argentina/Mendoza
  &kAtcAllZoneAmerica_La_Paz, // 0xaa29125d, America/La_Paz
  &kAtcAllZoneAmerica_Noronha, // 0xab5116fb, America/Noronha
  &kAtcAllZoneAmerica_Maceio, // 0xac80c6d4, America/Maceio
  &kAtcAllZoneAmerica_Manaus, // 0xac86bf8b, America/Manaus
  &kAtcAllZoneAmerica_Merida, // 0xacd172d8, America/Merida
  &kAtcAllZoneEurope_Chisinau, // 0xad58aa18, Europe/Chisinau
  &kAtcAllZoneAustralia_Broken_Hill, // 0xb06eada3, Australia/Broken_Hill
  &kAtcAllZoneAsia_Bishkek, // 0xb0728553, Asia/Bishkek
  &kAtcAllZoneAmerica_Paramaribo, // 0xb319e4c4, America/Paramaribo
  &kAtcAllZoneAmerica_Panama, // 0xb3863854, America/Panama
  &kAtcAllZoneAsia_Hebron, // 0xb5eef250, Asia/Hebron
  &kAtcAllZoneAmerica_Goose_Bay, // 0xb649541e, America/Goose_Bay
  &kAtcAllZoneAmerica_Los_Angeles, // 0xb7f7e8f2, America/Los_Angeles
  &kAtcAllZoneAmerica_Recife, // 0xb8730494, America/Recife
  &kAtcAllZoneAmerica_Regina, // 0xb875371c, America/Regina
  &kAtcAllZoneAsia_Ashgabat, // 0xba87598d, Asia/Ashgabat
  &kAtcAllZoneAmerica_Halifax, // 0xbc5b7183, America/Halifax
  &kAtcAllZoneAsia_Srednekolymsk, // 0xbf8e337d, Asia/Srednekolymsk
  &kAtcAllZoneAmerica_Argentina_Cordoba, // 0xbfccc308, America/Argentina/Cordoba
  &kAtcAllZoneAmerica_Tegucigalpa, // 0xbfd6fd4c, America/Tegucigalpa
  &kAtcAllZoneAsia_Manila, // 0xc156c944, Asia/Manila
  &kAtcAllZoneAfrica_Abidjan, // 0xc21305a3, Africa/Abidjan
  &kAtcAllZoneAmerica_Punta_Arenas, // 0xc2c3bce7, America/Punta_Arenas
  &kAtcAllZoneAfrica_Casablanca, // 0xc59f1b33, Africa/Casablanca
  &kAtcAllZoneAmerica_Argentina_Rio_Gallegos, // 0xc5b0f565, America/Argentina/Rio_Gallegos
  &kAtcAllZoneAsia_Jayapura, // 0xc6833c2f, Asia/Jayapura
  &kAtcAllZoneAmerica_Resolute, // 0xc7093459, America/Resolute
  &kAtcAllZoneAmerica_Rankin_Inlet, // 0xc8de4984, America/Rankin_Inlet
  &kAtcAllZoneAmerica_Barbados, // 0xcbbc3b04, America/Barbados
  &kAtcAllZoneAsia_Riyadh, // 0xcd973d93, Asia/Riyadh
  &kAtcAllZonePacific_Easter, // 0xcf54f7e7, Pacific/Easter
  &kAtcAllZoneAsia_Singapore, // 0xcf8581fa, Asia/Singapore
  &kAtcAllZoneAsia_Krasnoyarsk, // 0xd0376c6a, Asia/Krasnoyarsk
  &kAtcAllZoneAmerica_Mexico_City, // 0xd0d93f43, America/Mexico_City
  &kAtcAllZoneAsia_Taipei, // 0xd1a844ae, Asia/Taipei
  &kAtcAllZoneAsia_Tehran, // 0xd1f02254, Asia/Tehran
  &kAtcAllZoneEurope_Kaliningrad, // 0xd33b2f28, Europe/Kaliningrad
  &kAtcAllZoneAmerica_Argentina_Buenos_Aires, // 0xd43b4c0d, America/Argentina/Buenos_Aires
  &kAtcAllZoneAfrica_Juba, // 0xd51b395c, Africa/Juba
  &kAtcAllZoneAsia_Urumqi, // 0xd5379735, Asia/Urumqi
  &kAtcAllZoneAmerica_Cambridge_Bay, // 0xd5a44aff, America/Cambridge_Bay
  &kAtcAllZoneAfrica_Johannesburg, // 0xd5d157a0, Africa/Johannesburg
  &kAtcAllZoneEtc_GMT, // 0xd8e2de58, Etc/GMT
  &kAtcAllZoneEtc_UTC, // 0xd8e31abc, Etc/UTC
  &kAtcAllZoneAmerica_Yakutat, // 0xd8ee31e9, America/Yakutat
  &kAtcAllZoneAfrica_Algiers, // 0xd94515c1, Africa/Algiers
  &kAtcAllZonePST8PDT, // 0xd99ee2dc, PST8PDT
  &kAtcAllZoneEurope_Simferopol, // 0xda9eb724, Europe/Simferopol
  &kAtcAllZoneAmerica_Matamoros, // 0xdd1b0259, America/Matamoros
  &kAtcAllZonePacific_Kanton, // 0xdd512f0e, Pacific/Kanton
  &kAtcAllZoneAsia_Yangon, // 0xdd54a8be, Asia/Yangon
  &kAtcAllZoneEurope_Vilnius, // 0xdd63b8ce, Europe/Vilnius
  &kAtcAllZonePacific_Kosrae, // 0xde5139a8, Pacific/Kosrae
  &kAtcAllZoneAmerica_Kentucky_Monticello, // 0xde71c439, America/Kentucky/Monticello
  &kAtcAllZoneEurope_Brussels, // 0xdee07337, Europe/Brussels
  &kAtcAllZoneAmerica_Swift_Current, // 0xdef98e55, America/Swift_Current
  &kAtcAllZoneAsia_Irkutsk, // 0xdfbf213f, Asia/Irkutsk
  &kAtcAllZoneEurope_Ulyanovsk, // 0xe03783d0, Europe/Ulyanovsk
  &kAtcAllZoneAustralia_Lindeman, // 0xe05029e2, Australia/Lindeman
  &kAtcAllZoneEurope_Belgrade, // 0xe0532b3a, Europe/Belgrade
  &kAtcAllZoneAmerica_Menominee, // 0xe0e9c583, America/Menominee
  &kAtcAllZoneAtlantic_Faroe, // 0xe110a971, Atlantic/Faroe
  &kAtcAllZoneAntarctica_Casey, // 0xe2022583, Antarctica/Casey
  &kAtcAllZoneAntarctica_Davis, // 0xe2144b45, Antarctica/Davis
  &kAtcAllZoneEurope_Astrakhan, // 0xe22256e1, Europe/Astrakhan
  &kAtcAllZoneAntarctica_Troll, // 0xe33f085b, Antarctica/Troll
  &kAtcAllZoneEurope_Saratov, // 0xe4315da4, Europe/Saratov
  &kAtcAllZonePacific_Noumea, // 0xe551b788, Pacific/Noumea
  &kAtcAllZonePacific_Honolulu, // 0xe6e70af9, Pacific/Honolulu
  &kAtcAllZoneAmerica_Argentina_Tucuman, // 0xe96399eb, America/Argentina/Tucuman
  &kAtcAllZoneAsia_Magadan, // 0xebacc19b, Asia/Magadan
  &kAtcAllZoneAmerica_Ojinaga, // 0xebfde83f, America/Ojinaga
  &kAtcAllZoneCST6CDT, // 0xf0e87d00, CST6CDT
  &kAtcAllZonePacific_Tahiti, // 0xf24c2446, Pacific/Tahiti
  &kAtcAllZonePacific_Tarawa, // 0xf2517e63, Pacific/Tarawa
  &kAtcAllZoneMST7MDT, // 0xf2af9375, MST7MDT
  &kAtcAllZoneAsia_Tashkent, // 0xf3924254, Asia/Tashkent
  &kAtcAllZoneAsia_Sakhalin, // 0xf4a1c9bd, Asia/Sakhalin
  &kAtcAllZonePacific_Guadalcanal, // 0xf4dd25f0, Pacific/Guadalcanal
  &kAtcAllZoneAmerica_Danmarkshavn, // 0xf554d204, America/Danmarkshavn
  &kAtcAllZoneAsia_Shanghai, // 0xf895a7f5, Asia/Shanghai
  &kAtcAllZoneEurope_Gibraltar, // 0xf8e325fc, Europe/Gibraltar
  &kAtcAllZoneAtlantic_Azores, // 0xf93ed918, Atlantic/Azores
  &kAtcAllZoneAmerica_Eirunepe, // 0xf9b29683, America/Eirunepe
  &kAtcAllZoneAmerica_Montevideo, // 0xfa214780, America/Montevideo
  &kAtcAllZoneEurope_Kirov, // 0xfaf5abef, Europe/Kirov
  &kAtcAllZoneEurope_Malta, // 0xfb1560f3, Europe/Malta
  &kAtcAllZoneEurope_Minsk, // 0xfb19cc66, Europe/Minsk
  &kAtcAllZoneEurope_Bucharest, // 0xfb349ec5, Europe/Bucharest
  &kAtcAllZoneAfrica_Khartoum, // 0xfb3d4205, Africa/Khartoum
  &kAtcAllZoneEurope_Paris, // 0xfb4bc2a3, Europe/Paris
  &kAtcAllZoneAsia_Yekaterinburg, // 0xfb544c6e, Asia/Yekaterinburg
  &kAtcAllZoneEurope_Sofia, // 0xfb898656, Europe/Sofia
  &kAtcAllZoneAtlantic_Canary, // 0xfc23f2c2, Atlantic/Canary
  &kAtcAllZoneAmerica_Campo_Grande, // 0xfec3e7a6, America/Campo_Grande

};

//---------------------------------------------------------------------------
// Zone and Link Info registry. Sorted by zoneId. Links act like Zones.
//---------------------------------------------------------------------------
const AtcZoneInfo * const kAtcAllZoneAndLinkRegistry[596]  = {
  &kAtcAllZoneGB, // 0x005973ae, GB -> Europe/London
  &kAtcAllZoneNZ, // 0x005974ad, NZ -> Pacific/Auckland
  &kAtcAllZoneAsia_Kuala_Lumpur, // 0x014763c4, Asia/Kuala_Lumpur -> Asia/Singapore
  &kAtcAllZoneAfrica_Libreville, // 0x01d96de4, Africa/Libreville -> Africa/Lagos
  &kAtcAllZoneIndian_Cocos, // 0x021e86de, Indian/Cocos -> Asia/Yangon
  &kAtcAllZoneAustralia_Victoria, // 0x0260d5db, Australia/Victoria -> Australia/Melbourne
  &kAtcAllZoneAtlantic_Faeroe, // 0x031ec516, Atlantic/Faeroe -> Atlantic/Faroe
  &kAtcAllZoneAmerica_St_Johns, // 0x04b14e6e, America/St_Johns
  &kAtcAllZoneAmerica_St_Kitts, // 0x04c0507b, America/St_Kitts -> America/Puerto_Rico
  &kAtcAllZoneAfrica_Ouagadougou, // 0x04d7219a, Africa/Ouagadougou -> Africa/Abidjan
  &kAtcAllZoneAmerica_St_Lucia, // 0x04d8b3ba, America/St_Lucia -> America/Puerto_Rico
  &kAtcAllZoneAmerica_North_Dakota_New_Salem, // 0x04f9958e, America/North_Dakota/New_Salem
  &kAtcAllZoneAsia_Jakarta, // 0x0506ab50, Asia/Jakarta
  &kAtcAllZoneAfrica_Bujumbura, // 0x05232a47, Africa/Bujumbura -> Africa/Maputo
  &kAtcAllZoneAmerica_Mazatlan, // 0x0532189e, America/Mazatlan
  &kAtcAllZoneAmerica_St_Barthelemy, // 0x054e6a79, America/St_Barthelemy -> America/Puerto_Rico
  &kAtcAllZoneAfrica_Addis_Ababa, // 0x05ae1e65, Africa/Addis_Ababa -> Africa/Nairobi
  &kAtcAllZonePacific_Fakaofo, // 0x06532bba, Pacific/Fakaofo
  &kAtcAllZoneAmerica_Hermosillo, // 0x065d21c4, America/Hermosillo
  &kAtcAllZoneMexico_BajaSur, // 0x08ee3641, Mexico/BajaSur -> America/Mazatlan
  &kAtcAllZoneAsia_Tbilisi, // 0x0903e442, Asia/Tbilisi
  &kAtcAllZoneAmerica_Indiana_Tell_City, // 0x09263612, America/Indiana/Tell_City
  &kAtcAllZoneUS_Hawaii, // 0x09c8de2f, US/Hawaii -> Pacific/Honolulu
  &kAtcAllZoneAmerica_Boa_Vista, // 0x0a7b7efe, America/Boa_Vista
  &kAtcAllZoneAsia_Colombo, // 0x0af0e91d, Asia/Colombo
  &kAtcAllZoneCET, // 0x0b87d921, CET
  &kAtcAllZoneEET, // 0x0b87e1a3, EET
  &kAtcAllZoneEST, // 0x0b87e371, EST
  &kAtcAllZoneGMT, // 0x0b87eb2d, GMT -> Etc/GMT
  &kAtcAllZoneHST, // 0x0b87f034, HST
  &kAtcAllZoneMET, // 0x0b8803ab, MET
  &kAtcAllZoneMST, // 0x0b880579, MST
  &kAtcAllZonePRC, // 0x0b88120a, PRC -> Asia/Shanghai
  &kAtcAllZoneROC, // 0x0b881a29, ROC -> Asia/Taipei
  &kAtcAllZoneROK, // 0x0b881a31, ROK -> Asia/Seoul
  &kAtcAllZoneUCT, // 0x0b882571, UCT -> Etc/UTC
  &kAtcAllZoneUTC, // 0x0b882791, UTC -> Etc/UTC
  &kAtcAllZoneWET, // 0x0b882e35, WET
  &kAtcAllZoneAmerica_Guatemala, // 0x0c8259f7, America/Guatemala
  &kAtcAllZoneEurope_Mariehamn, // 0x0caa6496, Europe/Mariehamn -> Europe/Helsinki
  &kAtcAllZoneAfrica_Monrovia, // 0x0ce90385, Africa/Monrovia
  &kAtcAllZoneEgypt, // 0x0d1a278e, Egypt -> Africa/Cairo
  &kAtcAllZoneGMT_PLUS_0, // 0x0d2f7028, GMT+0 -> Etc/GMT
  &kAtcAllZoneGMT_0, // 0x0d2f706a, GMT-0 -> Etc/GMT
  &kAtcAllZoneJapan, // 0x0d712f8f, Japan -> Asia/Tokyo
  &kAtcAllZoneLibya, // 0x0d998b16, Libya -> Africa/Tripoli
  &kAtcAllZoneKwajalein, // 0x0e57afbb, Kwajalein -> Pacific/Kwajalein
  &kAtcAllZoneAntarctica_Rothera, // 0x0e86d203, Antarctica/Rothera
  &kAtcAllZoneAmerica_Yellowknife, // 0x0f76c76f, America/Yellowknife -> America/Edmonton
  &kAtcAllZoneAustralia_Melbourne, // 0x0fe559a3, Australia/Melbourne
  &kAtcAllZoneAmerica_Sao_Paulo, // 0x1063bfc9, America/Sao_Paulo
  &kAtcAllZoneEurope_Amsterdam, // 0x109395c2, Europe/Amsterdam -> Europe/Brussels
  &kAtcAllZoneAmerica_Indiana_Vevay, // 0x10aca054, America/Indiana/Vevay
  &kAtcAllZoneAmerica_Scoresbysund, // 0x123f8d2a, America/Scoresbysund
  &kAtcAllZoneAsia_Samarkand, // 0x13ae5104, Asia/Samarkand
  &kAtcAllZoneAsia_Amman, // 0x148d21bc, Asia/Amman
  &kAtcAllZoneAsia_Aqtau, // 0x148f710e, Asia/Aqtau
  &kAtcAllZoneAsia_Chita, // 0x14ae863b, Asia/Chita
  &kAtcAllZoneAsia_Dacca, // 0x14bcac5e, Asia/Dacca -> Asia/Dhaka
  &kAtcAllZoneAsia_Dhaka, // 0x14c07b8b, Asia/Dhaka
  &kAtcAllZoneAsia_Dubai, // 0x14c79f77, Asia/Dubai
  &kAtcAllZoneAmerica_Bahia_Banderas, // 0x14f6329a, America/Bahia_Banderas
  &kAtcAllZoneAsia_Kabul, // 0x153b5601, Asia/Kabul
  &kAtcAllZoneAsia_Ashkhabad, // 0x15454f09, Asia/Ashkhabad -> Asia/Ashgabat
  &kAtcAllZoneAsia_Macao, // 0x155f88b3, Asia/Macao -> Asia/Macau
  &kAtcAllZoneAsia_Macau, // 0x155f88b9, Asia/Macau
  &kAtcAllZoneAsia_Qatar, // 0x15a8330b, Asia/Qatar
  &kAtcAllZoneAsia_Seoul, // 0x15ce82da, Asia/Seoul
  &kAtcAllZoneAsia_Tokyo, // 0x15e606a8, Asia/Tokyo
  &kAtcAllZoneAsia_Tomsk, // 0x15e60e60, Asia/Tomsk
  &kAtcAllZoneAsia_Tel_Aviv, // 0x166d7c2c, Asia/Tel_Aviv -> Asia/Jerusalem
  &kAtcAllZoneAsia_Thimphu, // 0x170380d1, Asia/Thimphu
  &kAtcAllZoneAmerica_Guayaquil, // 0x17e64958, America/Guayaquil
  &kAtcAllZoneAmerica_Montserrat, // 0x199b0a35, America/Montserrat -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Kentucky_Louisville, // 0x1a21024b, America/Kentucky/Louisville
  &kAtcAllZoneAsia_Pontianak, // 0x1a76c057, Asia/Pontianak
  &kAtcAllZoneEurope_Podgorica, // 0x1c1a499c, Europe/Podgorica -> Europe/Belgrade
  &kAtcAllZoneAtlantic_Reykjavik, // 0x1c2b4f74, Atlantic/Reykjavik -> Africa/Abidjan
  &kAtcAllZoneAmerica_New_York, // 0x1e2a7654, America/New_York
  &kAtcAllZoneEurope_Luxembourg, // 0x1f8bc6ce, Europe/Luxembourg -> Europe/Brussels
  &kAtcAllZoneAsia_Aden, // 0x1fa7084a, Asia/Aden -> Asia/Riyadh
  &kAtcAllZoneAsia_Baku, // 0x1fa788b5, Asia/Baku
  &kAtcAllZoneAsia_Dili, // 0x1fa8c394, Asia/Dili
  &kAtcAllZoneAsia_Gaza, // 0x1faa4875, Asia/Gaza
  &kAtcAllZoneAsia_Hovd, // 0x1fab0fe3, Asia/Hovd
  &kAtcAllZoneAsia_Omsk, // 0x1faeddac, Asia/Omsk
  &kAtcAllZoneAsia_Oral, // 0x1faef0a0, Asia/Oral
  &kAtcAllZoneAmerica_Montreal, // 0x203a1ea8, America/Montreal -> America/Toronto
  &kAtcAllZoneAsia_Ho_Chi_Minh, // 0x20f2d127, Asia/Ho_Chi_Minh
  &kAtcAllZoneAsia_Damascus, // 0x20fbb063, Asia/Damascus
  &kAtcAllZoneAmerica_Argentina_ComodRivadavia, // 0x22758877, America/Argentina/ComodRivadavia -> America/Argentina/Catamarca
  &kAtcAllZonePacific_Apia, // 0x23359b5e, Pacific/Apia
  &kAtcAllZonePacific_Fiji, // 0x23383ba5, Pacific/Fiji
  &kAtcAllZonePacific_Guam, // 0x2338f9ed, Pacific/Guam
  &kAtcAllZonePacific_Niue, // 0x233ca014, Pacific/Niue
  &kAtcAllZonePacific_Truk, // 0x234010a9, Pacific/Truk -> Pacific/Port_Moresby
  &kAtcAllZonePacific_Wake, // 0x23416c2b, Pacific/Wake -> Pacific/Tarawa
  &kAtcAllZoneAustralia_Adelaide, // 0x2428e8a3, Australia/Adelaide
  &kAtcAllZonePacific_Auckland, // 0x25062f86, Pacific/Auckland
  &kAtcAllZonePacific_Tongatapu, // 0x262ca836, Pacific/Tongatapu
  &kAtcAllZoneAmerica_Monterrey, // 0x269a1deb, America/Monterrey
  &kAtcAllZoneEtc_Greenwich, // 0x26daa98c, Etc/Greenwich -> Etc/GMT
  &kAtcAllZoneAustralia_Currie, // 0x278b6a24, Australia/Currie -> Australia/Hobart
  &kAtcAllZoneAustralia_Darwin, // 0x2876bdff, Australia/Darwin
  &kAtcAllZonePacific_Pohnpei, // 0x28929f96, Pacific/Pohnpei -> Pacific/Guadalcanal
  &kAtcAllZoneAsia_Famagusta, // 0x289b4f8b, Asia/Famagusta
  &kAtcAllZoneAmerica_Indiana_Vincennes, // 0x28a0b212, America/Indiana/Vincennes
  &kAtcAllZoneAmerica_Indiana_Indianapolis, // 0x28a669a4, America/Indiana/Indianapolis
  &kAtcAllZoneAsia_Vladivostok, // 0x29de34a8, Asia/Vladivostok
  &kAtcAllZoneAustralia_Canberra, // 0x2a09ae58, Australia/Canberra -> Australia/Sydney
  &kAtcAllZoneAmerica_Fortaleza, // 0x2ad018ee, America/Fortaleza
  &kAtcAllZoneAmerica_Vancouver, // 0x2c6f6b1f, America/Vancouver
  &kAtcAllZoneAmerica_Pangnirtung, // 0x2d999193, America/Pangnirtung -> America/Iqaluit
  &kAtcAllZoneAmerica_Iqaluit, // 0x2de310bf, America/Iqaluit
  &kAtcAllZoneJamaica, // 0x2e44fdab, Jamaica -> America/Jamaica
  &kAtcAllZonePacific_Chatham, // 0x2f0de999, Pacific/Chatham
  &kAtcAllZoneEtc_Universal, // 0x2f8cb9a9, Etc/Universal -> Etc/UTC
  &kAtcAllZoneAmerica_Indiana_Marengo, // 0x2feeee72, America/Indiana/Marengo
  &kAtcAllZoneEurope_Tallinn, // 0x30c4e096, Europe/Tallinn
  &kAtcAllZoneAfrica_Djibouti, // 0x30ea01d4, Africa/Djibouti -> Africa/Nairobi
  &kAtcAllZoneAsia_Ulaanbaatar, // 0x30f0cc4e, Asia/Ulaanbaatar
  &kAtcAllZoneAfrica_Gaborone, // 0x317c0aa7, Africa/Gaborone -> Africa/Maputo
  &kAtcAllZoneAmerica_Argentina_Ushuaia, // 0x320dcdde, America/Argentina/Ushuaia
  &kAtcAllZoneAsia_Calcutta, // 0x328a44c3, Asia/Calcutta -> Asia/Kolkata
  &kAtcAllZoneAustralia_Hobart, // 0x32bf951a, Australia/Hobart
  &kAtcAllZoneAsia_Dushanbe, // 0x32fc5c3c, Asia/Dushanbe
  &kAtcAllZoneAtlantic_South_Georgia, // 0x33013174, Atlantic/South_Georgia
  &kAtcAllZoneAmerica_Phoenix, // 0x34b5af01, America/Phoenix
  &kAtcAllZoneAsia_Istanbul, // 0x382e7894, Asia/Istanbul -> Europe/Istanbul
  &kAtcAllZoneAsia_Ulan_Bator, // 0x394db4d9, Asia/Ulan_Bator -> Asia/Ulaanbaatar
  &kAtcAllZoneAntarctica_Mawson, // 0x399cd863, Antarctica/Mawson
  &kAtcAllZoneAfrica_Brazzaville, // 0x39cda760, Africa/Brazzaville -> Africa/Lagos
  &kAtcAllZoneAmerica_Caracas, // 0x3be064f4, America/Caracas
  &kAtcAllZoneAmerica_Cayenne, // 0x3c617269, America/Cayenne
  &kAtcAllZoneAfrica_Porto_Novo, // 0x3d1bf95d, Africa/Porto-Novo -> Africa/Lagos
  &kAtcAllZoneAtlantic_Bermuda, // 0x3d4bb1c4, Atlantic/Bermuda
  &kAtcAllZoneAmerica_Managua, // 0x3d5e7600, America/Managua
  &kAtcAllZoneAmerica_Marigot, // 0x3dab3a59, America/Marigot -> America/Puerto_Rico
  &kAtcAllZoneEurope_Guernsey, // 0x3db12c16, Europe/Guernsey -> Europe/London
  &kAtcAllZoneAfrica_Nouakchott, // 0x3dc49dba, Africa/Nouakchott -> Africa/Abidjan
  &kAtcAllZoneAmerica_Louisville, // 0x3dcb47ee, America/Louisville -> America/Kentucky/Louisville
  &kAtcAllZoneAmerica_Argentina_San_Juan, // 0x3e1009bd, America/Argentina/San_Juan
  &kAtcAllZoneAmerica_Argentina_San_Luis, // 0x3e11238c, America/Argentina/San_Luis
  &kAtcAllZoneEurope_Volgograd, // 0x3ed0f389, Europe/Volgograd
  &kAtcAllZoneAmerica_Fort_Nelson, // 0x3f437e0f, America/Fort_Nelson
  &kAtcAllZoneEtc_GMT_PLUS_10, // 0x3f8f1cc4, Etc/GMT+10
  &kAtcAllZoneEtc_GMT_PLUS_11, // 0x3f8f1cc5, Etc/GMT+11
  &kAtcAllZoneEtc_GMT_PLUS_12, // 0x3f8f1cc6, Etc/GMT+12
  &kAtcAllZoneEtc_GMT_10, // 0x3f8f2546, Etc/GMT-10
  &kAtcAllZoneEtc_GMT_11, // 0x3f8f2547, Etc/GMT-11
  &kAtcAllZoneEtc_GMT_12, // 0x3f8f2548, Etc/GMT-12
  &kAtcAllZoneEtc_GMT_13, // 0x3f8f2549, Etc/GMT-13
  &kAtcAllZoneEtc_GMT_14, // 0x3f8f254a, Etc/GMT-14
  &kAtcAllZoneAntarctica_Palmer, // 0x40962f4f, Antarctica/Palmer
  &kAtcAllZoneCanada_Pacific, // 0x40fa3c7b, Canada/Pacific -> America/Vancouver
  &kAtcAllZoneEurope_Athens, // 0x4318fa27, Europe/Athens
  &kAtcAllZoneIndian_Kerguelen, // 0x4351b389, Indian/Kerguelen -> Indian/Maldives
  &kAtcAllZoneAmerica_Indiana_Winamac, // 0x4413fa69, America/Indiana/Winamac
  &kAtcAllZoneEurope_Berlin, // 0x44644c20, Europe/Berlin
  &kAtcAllZoneAtlantic_St_Helena, // 0x451fc5f7, Atlantic/St_Helena -> Africa/Abidjan
  &kAtcAllZoneIndian_Chagos, // 0x456f7c3c, Indian/Chagos
  &kAtcAllZoneIndian_Mahe, // 0x45e725e2, Indian/Mahe -> Asia/Dubai
  &kAtcAllZoneIndian_Comoro, // 0x45f4deb6, Indian/Comoro -> Africa/Nairobi
  &kAtcAllZoneAmerica_Mendoza, // 0x46b4e054, America/Mendoza -> America/Argentina/Mendoza
  &kAtcAllZoneAsia_Ust_Nera, // 0x4785f921, Asia/Ust-Nera
  &kAtcAllZoneEurope_Dublin, // 0x4a275f62, Europe/Dublin
  &kAtcAllZoneAsia_Nicosia, // 0x4b0fcf78, Asia/Nicosia
  &kAtcAllZoneAmerica_Chicago, // 0x4b92b5d4, America/Chicago
  &kAtcAllZoneAustralia_Sydney, // 0x4d1e9776, Australia/Sydney
  &kAtcAllZoneNZ_CHAT, // 0x4d42afda, NZ-CHAT -> Pacific/Chatham
  &kAtcAllZoneUS_Arizona, // 0x4ec52670, US/Arizona -> America/Phoenix
  &kAtcAllZoneAntarctica_Vostok, // 0x4f966fd4, Antarctica/Vostok
  &kAtcAllZoneUS_Aleutian, // 0x4fe013ef, US/Aleutian -> America/Adak
  &kAtcAllZoneAustralia_Brisbane, // 0x4fedc9c0, Australia/Brisbane
  &kAtcAllZoneAmerica_Catamarca, // 0x5036e963, America/Catamarca -> America/Argentina/Catamarca
  &kAtcAllZoneAmerica_Asuncion, // 0x50ec79a6, America/Asuncion
  &kAtcAllZoneAsia_Karachi, // 0x527f5245, Asia/Karachi
  &kAtcAllZoneAsia_Kashgar, // 0x52955193, Asia/Kashgar -> Asia/Urumqi
  &kAtcAllZoneCanada_Atlantic, // 0x536b119c, Canada/Atlantic -> America/Halifax
  &kAtcAllZonePacific_Gambier, // 0x53720c3a, Pacific/Gambier
  &kAtcAllZoneAmerica_Whitehorse, // 0x54e0e3e8, America/Whitehorse
  &kAtcAllZoneAmerica_Martinique, // 0x551e84c5, America/Martinique
  &kAtcAllZoneAmerica_Jamaica, // 0x565dad6c, America/Jamaica
  &kAtcAllZoneUS_Samoa, // 0x566821cd, US/Samoa -> Pacific/Pago_Pago
  &kAtcAllZoneHongkong, // 0x56d36560, Hongkong -> Asia/Hong_Kong
  &kAtcAllZoneEurope_Jersey, // 0x570dae76, Europe/Jersey -> Europe/London
  &kAtcAllZoneAsia_Hong_Kong, // 0x577f28ac, Asia/Hong_Kong
  &kAtcAllZonePacific_Marquesas, // 0x57ca7135, Pacific/Marquesas
  &kAtcAllZoneAmerica_Miquelon, // 0x59674330, America/Miquelon
  &kAtcAllZoneAntarctica_DumontDUrville, // 0x5a3c656c, Antarctica/DumontDUrville -> Pacific/Port_Moresby
  &kAtcAllZoneAtlantic_Jan_Mayen, // 0x5a7535b6, Atlantic/Jan_Mayen -> Europe/Berlin
  &kAtcAllZoneAmerica_Anchorage, // 0x5a79260e, America/Anchorage
  &kAtcAllZoneUS_Eastern, // 0x5bb7e78e, US/Eastern -> America/New_York
  &kAtcAllZoneAsia_Jerusalem, // 0x5becd23a, Asia/Jerusalem
  &kAtcAllZoneEurope_Stockholm, // 0x5bf6fbb8, Europe/Stockholm -> Europe/Berlin
  &kAtcAllZoneEurope_Lisbon, // 0x5c00a70b, Europe/Lisbon
  &kAtcAllZoneAtlantic_Cape_Verde, // 0x5c5e1772, Atlantic/Cape_Verde
  &kAtcAllZoneEurope_London, // 0x5c6a84ae, Europe/London
  &kAtcAllZoneAmerica_Cordoba, // 0x5c8a7600, America/Cordoba -> America/Argentina/Cordoba
  &kAtcAllZoneAsia_Ujung_Pandang, // 0x5d001eb3, Asia/Ujung_Pandang -> Asia/Makassar
  &kAtcAllZoneAfrica_Mbabane, // 0x5d3bdd40, Africa/Mbabane -> Africa/Johannesburg
  &kAtcAllZoneEurope_Madrid, // 0x5dbd1535, Europe/Madrid
  &kAtcAllZoneAmerica_Moncton, // 0x5e07fe24, America/Moncton
  &kAtcAllZonePacific_Bougainville, // 0x5e10f7a4, Pacific/Bougainville
  &kAtcAllZoneEurope_Monaco, // 0x5ebf9f01, Europe/Monaco -> Europe/Paris
  &kAtcAllZoneEurope_Moscow, // 0x5ec266fc, Europe/Moscow
  &kAtcAllZoneAmerica_Argentina_Jujuy, // 0x5f2f46c5, America/Argentina/Jujuy
  &kAtcAllZoneAmerica_Argentina_Salta, // 0x5fc73403, America/Argentina/Salta
  &kAtcAllZonePacific_Pago_Pago, // 0x603aebd0, Pacific/Pago_Pago
  &kAtcAllZonePacific_Enderbury, // 0x61599a93, Pacific/Enderbury -> Pacific/Kanton
  &kAtcAllZoneAfrica_Sao_Tome, // 0x61b319d1, Africa/Sao_Tome
  &kAtcAllZoneCanada_Central, // 0x626710f5, Canada/Central -> America/Winnipeg
  &kAtcAllZoneAmerica_Creston, // 0x62a70204, America/Creston -> America/Phoenix
  &kAtcAllZoneAmerica_Costa_Rica, // 0x63ff66be, America/Costa_Rica
  &kAtcAllZoneAsia_Qostanay, // 0x654fe522, Asia/Qostanay
  &kAtcAllZoneAmerica_Indiana_Knox, // 0x6554adc9, America/Indiana/Knox
  &kAtcAllZoneEurope_Prague, // 0x65ee5d48, Europe/Prague
  &kAtcAllZoneBrazil_Acre, // 0x66934f93, Brazil/Acre -> America/Rio_Branco
  &kAtcAllZoneBrazil_East, // 0x669578c5, Brazil/East -> America/Sao_Paulo
  &kAtcAllZoneAfrica_Kinshasa, // 0x6695d70c, Africa/Kinshasa -> Africa/Lagos
  &kAtcAllZoneBrazil_West, // 0x669f689b, Brazil/West -> America/Manaus
  &kAtcAllZoneAfrica_Mogadishu, // 0x66bc159b, Africa/Mogadishu -> Africa/Nairobi
  &kAtcAllZoneAmerica_Puerto_Rico, // 0x6752ca31, America/Puerto_Rico
  &kAtcAllZoneUS_Indiana_Starke, // 0x67977be7, US/Indiana-Starke -> America/Indiana/Knox
  &kAtcAllZoneAmerica_Buenos_Aires, // 0x67d79a05, America/Buenos_Aires -> America/Argentina/Buenos_Aires
  &kAtcAllZoneAfrica_Freetown, // 0x6823dd64, Africa/Freetown -> Africa/Abidjan
  &kAtcAllZoneIndian_Christmas, // 0x68c207d5, Indian/Christmas -> Asia/Bangkok
  &kAtcAllZoneAsia_Novokuznetsk, // 0x69264f93, Asia/Novokuznetsk
  &kAtcAllZoneAmerica_Indianapolis, // 0x6a009ae1, America/Indianapolis -> America/Indiana/Indianapolis
  &kAtcAllZoneEurope_Sarajevo, // 0x6a576c3f, Europe/Sarajevo -> Europe/Belgrade
  &kAtcAllZoneAmerica_Curacao, // 0x6a879184, America/Curacao -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Tijuana, // 0x6aa1df72, America/Tijuana
  &kAtcAllZoneAsia_Makassar, // 0x6aa21c85, Asia/Makassar
  &kAtcAllZoneEurope_Helsinki, // 0x6ab2975b, Europe/Helsinki
  &kAtcAllZoneAmerica_Lower_Princes, // 0x6ae45b62, America/Lower_Princes -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Porto_Velho, // 0x6b1aac77, America/Porto_Velho
  &kAtcAllZoneEurope_Samara, // 0x6bc0b139, Europe/Samara
  &kAtcAllZoneEurope_Skopje, // 0x6c76fdd0, Europe/Skopje -> Europe/Belgrade
  &kAtcAllZoneAmerica_Edmonton, // 0x6cb9484a, America/Edmonton
  &kAtcAllZoneAmerica_Dawson_Creek, // 0x6cf24e5b, America/Dawson_Creek
  &kAtcAllZoneAsia_Rangoon, // 0x6d1217c6, Asia/Rangoon -> Asia/Yangon
  &kAtcAllZoneUS_East_Indiana, // 0x6dcf558a, US/East-Indiana -> America/Indiana/Indianapolis
  &kAtcAllZoneAmerica_Grand_Turk, // 0x6e216197, America/Grand_Turk
  &kAtcAllZoneAmerica_Blanc_Sablon, // 0x6e299892, America/Blanc-Sablon -> America/Puerto_Rico
  &kAtcAllZoneEurope_Tirane, // 0x6ea95b47, Europe/Tirane
  &kAtcAllZoneUS_Mountain, // 0x6eb88247, US/Mountain -> America/Denver
  &kAtcAllZoneAntarctica_McMurdo, // 0x6eeb5585, Antarctica/McMurdo -> Pacific/Auckland
  &kAtcAllZoneAmerica_Araguaina, // 0x6f9a3aef, America/Araguaina
  &kAtcAllZoneAfrica_Lubumbashi, // 0x6fd88566, Africa/Lubumbashi -> Africa/Maputo
  &kAtcAllZoneIndian_Reunion, // 0x7076c047, Indian/Reunion -> Asia/Dubai
  &kAtcAllZoneAsia_Qyzylorda, // 0x71282e81, Asia/Qyzylorda
  &kAtcAllZoneAsia_Kolkata, // 0x72c06cd9, Asia/Kolkata
  &kAtcAllZoneAmerica_Ciudad_Juarez, // 0x7347fc60, America/Ciudad_Juarez
  &kAtcAllZoneEurope_Vienna, // 0x734cc2e5, Europe/Vienna
  &kAtcAllZoneAfrica_Asmara, // 0x73b278ef, Africa/Asmara -> Africa/Nairobi
  &kAtcAllZoneAfrica_Asmera, // 0x73b289f3, Africa/Asmera -> Africa/Nairobi
  &kAtcAllZoneAsia_Kamchatka, // 0x73baf9d7, Asia/Kamchatka
  &kAtcAllZoneAmerica_Santarem, // 0x740caec1, America/Santarem
  &kAtcAllZoneAmerica_Santiago, // 0x7410c9bc, America/Santiago
  &kAtcAllZoneAfrica_Bamako, // 0x74c1e7a5, Africa/Bamako -> Africa/Abidjan
  &kAtcAllZoneAfrica_Bangui, // 0x74c28ed0, Africa/Bangui -> Africa/Lagos
  &kAtcAllZoneAfrica_Banjul, // 0x74c29b96, Africa/Banjul -> Africa/Abidjan
  &kAtcAllZoneEurope_Nicosia, // 0x74efab8a, Europe/Nicosia -> Asia/Nicosia
  &kAtcAllZoneEurope_Warsaw, // 0x75185c19, Europe/Warsaw
  &kAtcAllZoneAmerica_El_Salvador, // 0x752ad652, America/El_Salvador
  &kAtcAllZoneAfrica_Bissau, // 0x75564141, Africa/Bissau
  &kAtcAllZoneAmerica_Santo_Domingo, // 0x75a0d177, America/Santo_Domingo
  &kAtcAllZoneUS_Michigan, // 0x766bb7bc, US/Michigan -> America/Detroit
  &kAtcAllZoneCanada_Saskatchewan, // 0x77311f49, Canada/Saskatchewan -> America/Regina
  &kAtcAllZoneAfrica_Accra, // 0x77d5b054, Africa/Accra -> Africa/Abidjan
  &kAtcAllZoneAfrica_Cairo, // 0x77f8e228, Africa/Cairo
  &kAtcAllZoneAfrica_Ceuta, // 0x77fb46ec, Africa/Ceuta
  &kAtcAllZoneAfrica_Dakar, // 0x780b00fd, Africa/Dakar -> Africa/Abidjan
  &kAtcAllZoneAfrica_Lagos, // 0x789bb5d0, Africa/Lagos
  &kAtcAllZoneAfrica_Windhoek, // 0x789c9bd3, Africa/Windhoek
  &kAtcAllZoneCanada_Yukon, // 0x78dd35c2, Canada/Yukon -> America/Whitehorse
  &kAtcAllZoneAmerica_Toronto, // 0x792e851b, America/Toronto
  &kAtcAllZoneAmerica_Tortola, // 0x7931462b, America/Tortola -> America/Puerto_Rico
  &kAtcAllZoneAfrica_Tunis, // 0x79378e6d, Africa/Tunis
  &kAtcAllZoneAfrica_Douala, // 0x7a6df310, Africa/Douala -> Africa/Lagos
  &kAtcAllZoneAfrica_Conakry, // 0x7ab36b31, Africa/Conakry -> Africa/Abidjan
  &kAtcAllZoneIndian_Mauritius, // 0x7b09c02a, Indian/Mauritius
  &kAtcAllZoneAtlantic_Stanley, // 0x7bb3e1c4, Atlantic/Stanley
  &kAtcAllZoneAmerica_Ensenada, // 0x7bc95445, America/Ensenada -> America/Tijuana
  &kAtcAllZoneEurope_Zagreb, // 0x7c11c9ff, Europe/Zagreb -> Europe/Belgrade
  &kAtcAllZoneCuba, // 0x7c83cba0, Cuba -> America/Havana
  &kAtcAllZoneEire, // 0x7c84b36a, Eire -> Europe/Dublin
  &kAtcAllZoneGMT0, // 0x7c8550fd, GMT0 -> Etc/GMT
  &kAtcAllZoneIran, // 0x7c87090f, Iran -> Asia/Tehran
  &kAtcAllZoneW_SU, // 0x7c8d8ef1, W-SU -> Europe/Moscow
  &kAtcAllZoneZulu, // 0x7c9069b5, Zulu -> Etc/UTC
  &kAtcAllZoneEurope_Zurich, // 0x7d8195b9, Europe/Zurich
  &kAtcAllZoneChile_Continental, // 0x7e2bdb18, Chile/Continental -> America/Santiago
  &kAtcAllZoneAmerica_Fort_Wayne, // 0x7eaaaf24, America/Fort_Wayne -> America/Indiana/Indianapolis
  &kAtcAllZoneAsia_Kuching, // 0x801b003b, Asia/Kuching
  &kAtcAllZoneAtlantic_Madeira, // 0x81b5c037, Atlantic/Madeira
  &kAtcAllZoneAmerica_Atikokan, // 0x81b92098, America/Atikokan -> America/Panama
  &kAtcAllZoneAfrica_Harare, // 0x82c39a2d, Africa/Harare -> Africa/Maputo
  &kAtcAllZoneAmerica_Shiprock, // 0x82fb7049, America/Shiprock -> America/Denver
  &kAtcAllZonePacific_Kiritimati, // 0x8305073a, Pacific/Kiritimati
  &kAtcAllZoneAmerica_St_Vincent, // 0x8460e523, America/St_Vincent -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Metlakatla, // 0x84de2686, America/Metlakatla
  &kAtcAllZoneAsia_Yakutsk, // 0x87bb3a9e, Asia/Yakutsk
  &kAtcAllZoneAmerica_Chihuahua, // 0x8827d776, America/Chihuahua
  &kAtcAllZonePacific_Pitcairn, // 0x8837d8bd, Pacific/Pitcairn
  &kAtcAllZoneAsia_Vientiane, // 0x89d68d75, Asia/Vientiane -> Asia/Bangkok
  &kAtcAllZonePacific_Chuuk, // 0x8a090b23, Pacific/Chuuk -> Pacific/Port_Moresby
  &kAtcAllZonePacific_Efate, // 0x8a2bce28, Pacific/Efate
  &kAtcAllZoneAfrica_Kigali, // 0x8a4dcf2b, Africa/Kigali -> Africa/Maputo
  &kAtcAllZoneAustralia_ACT, // 0x8a970eb2, Australia/ACT -> Australia/Sydney
  &kAtcAllZoneAustralia_LHI, // 0x8a973e17, Australia/LHI -> Australia/Lord_Howe
  &kAtcAllZoneAustralia_NSW, // 0x8a974812, Australia/NSW -> Australia/Sydney
  &kAtcAllZonePacific_Nauru, // 0x8acc41ae, Pacific/Nauru
  &kAtcAllZoneEST5EDT, // 0x8adc72a3, EST5EDT
  &kAtcAllZonePacific_Palau, // 0x8af04a36, Pacific/Palau
  &kAtcAllZonePacific_Samoa, // 0x8b2699b4, Pacific/Samoa -> Pacific/Pago_Pago
  &kAtcAllZoneAmerica_Winnipeg, // 0x8c7dafc7, America/Winnipeg
  &kAtcAllZoneAustralia_Eucla, // 0x8cf99e44, Australia/Eucla
  &kAtcAllZoneAmerica_Argentina_Catamarca, // 0x8d40986b, America/Argentina/Catamarca
  &kAtcAllZoneAfrica_Luanda, // 0x8d7909cf, Africa/Luanda -> Africa/Lagos
  &kAtcAllZoneAfrica_Lusaka, // 0x8d82b23b, Africa/Lusaka -> Africa/Maputo
  &kAtcAllZoneAustralia_North, // 0x8d997165, Australia/North -> Australia/Darwin
  &kAtcAllZoneAustralia_Perth, // 0x8db8269d, Australia/Perth
  &kAtcAllZoneAustralia_South, // 0x8df3f8ad, Australia/South -> Australia/Adelaide
  &kAtcAllZonePacific_Kwajalein, // 0x8e216759, Pacific/Kwajalein
  &kAtcAllZoneAmerica_Port_au_Prince, // 0x8e4a7bdc, America/Port-au-Prince
  &kAtcAllZoneAfrica_Malabo, // 0x8e6a1906, Africa/Malabo -> Africa/Lagos
  &kAtcAllZoneAfrica_Maputo, // 0x8e6ca1f0, Africa/Maputo
  &kAtcAllZoneAfrica_Maseru, // 0x8e6e02c7, Africa/Maseru -> Africa/Johannesburg
  &kAtcAllZonePacific_Norfolk, // 0x8f4eb4be, Pacific/Norfolk
  &kAtcAllZoneAmerica_Godthab, // 0x8f7eba1f, America/Godthab -> America/Nuuk
  &kAtcAllZoneAustralia_Yancowinna, // 0x90bac131, Australia/Yancowinna -> Australia/Broken_Hill
  &kAtcAllZoneAfrica_Niamey, // 0x914a30fd, Africa/Niamey -> Africa/Lagos
  &kAtcAllZoneAsia_Yerevan, // 0x9185c8cc, Asia/Yerevan
  &kAtcAllZoneAmerica_Detroit, // 0x925cfbc1, America/Detroit
  &kAtcAllZoneAsia_Choibalsan, // 0x928aa4a6, Asia/Choibalsan
  &kAtcAllZoneAntarctica_Macquarie, // 0x92f47626, Antarctica/Macquarie
  &kAtcAllZoneAmerica_Belize, // 0x93256c81, America/Belize
  &kAtcAllZoneMexico_General, // 0x93711d57, Mexico/General -> America/Mexico_City
  &kAtcAllZoneAmerica_Bogota, // 0x93d7bc62, America/Bogota
  &kAtcAllZoneAsia_Pyongyang, // 0x93ed1c8e, Asia/Pyongyang
  &kAtcAllZoneAmerica_Indiana_Petersburg, // 0x94ac7acc, America/Indiana/Petersburg
  &kAtcAllZoneAmerica_Cancun, // 0x953331be, America/Cancun
  &kAtcAllZoneAmerica_Cayman, // 0x953961df, America/Cayman -> America/Panama
  &kAtcAllZoneAmerica_Glace_Bay, // 0x9681f8dd, America/Glace_Bay
  &kAtcAllZoneAsia_Khandyga, // 0x9685a4d9, Asia/Khandyga
  &kAtcAllZoneAmerica_Grenada, // 0x968ce4d8, America/Grenada -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Cuiaba, // 0x969a52eb, America/Cuiaba
  &kAtcAllZoneAmerica_Dawson, // 0x978d8d12, America/Dawson
  &kAtcAllZoneAmerica_Aruba, // 0x97cf8651, America/Aruba -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Denver, // 0x97d10b2a, America/Denver
  &kAtcAllZoneAmerica_Bahia, // 0x97d815fb, America/Bahia
  &kAtcAllZoneAmerica_Belem, // 0x97da580b, America/Belem
  &kAtcAllZoneAmerica_Boise, // 0x97dfc8d8, America/Boise
  &kAtcAllZoneEurope_Andorra, // 0x97f6764b, Europe/Andorra
  &kAtcAllZoneAmerica_Adak, // 0x97fe49d7, America/Adak
  &kAtcAllZoneAmerica_Atka, // 0x97fe8f27, America/Atka -> America/Adak
  &kAtcAllZoneAmerica_Lima, // 0x980468c9, America/Lima
  &kAtcAllZoneAmerica_Nome, // 0x98059b15, America/Nome
  &kAtcAllZoneAmerica_Nuuk, // 0x9805b5a9, America/Nuuk
  &kAtcAllZoneIndian_Maldives, // 0x9869681c, Indian/Maldives
  &kAtcAllZoneAmerica_Jujuy, // 0x9873dbbd, America/Jujuy -> America/Argentina/Jujuy
  &kAtcAllZoneAmerica_Sitka, // 0x99104ce2, America/Sitka
  &kAtcAllZoneAmerica_Thule, // 0x9921dd68, America/Thule
  &kAtcAllZonePacific_Rarotonga, // 0x9981a3b0, Pacific/Rarotonga
  &kAtcAllZoneAsia_Kathmandu, // 0x9a96ce6f, Asia/Kathmandu
  &kAtcAllZoneBrazil_DeNoronha, // 0x9b4cb496, Brazil/DeNoronha -> America/Noronha
  &kAtcAllZoneAmerica_North_Dakota_Beulah, // 0x9b52b384, America/North_Dakota/Beulah
  &kAtcAllZoneAmerica_Rainy_River, // 0x9cd58a10, America/Rainy_River -> America/Winnipeg
  &kAtcAllZoneEurope_Budapest, // 0x9ce0197c, Europe/Budapest
  &kAtcAllZoneAsia_Baghdad, // 0x9ceffbed, Asia/Baghdad
  &kAtcAllZoneAsia_Bahrain, // 0x9d078487, Asia/Bahrain -> Asia/Qatar
  &kAtcAllZoneEtc_GMT_PLUS_0, // 0x9d13da13, Etc/GMT+0 -> Etc/GMT
  &kAtcAllZoneEtc_GMT_PLUS_1, // 0x9d13da14, Etc/GMT+1
  &kAtcAllZoneEtc_GMT_PLUS_2, // 0x9d13da15, Etc/GMT+2
  &kAtcAllZoneEtc_GMT_PLUS_3, // 0x9d13da16, Etc/GMT+3
  &kAtcAllZoneEtc_GMT_PLUS_4, // 0x9d13da17, Etc/GMT+4
  &kAtcAllZoneEtc_GMT_PLUS_5, // 0x9d13da18, Etc/GMT+5
  &kAtcAllZoneEtc_GMT_PLUS_6, // 0x9d13da19, Etc/GMT+6
  &kAtcAllZoneEtc_GMT_PLUS_7, // 0x9d13da1a, Etc/GMT+7
  &kAtcAllZoneEtc_GMT_PLUS_8, // 0x9d13da1b, Etc/GMT+8
  &kAtcAllZoneEtc_GMT_PLUS_9, // 0x9d13da1c, Etc/GMT+9
  &kAtcAllZoneEtc_GMT_0, // 0x9d13da55, Etc/GMT-0 -> Etc/GMT
  &kAtcAllZoneEtc_GMT_1, // 0x9d13da56, Etc/GMT-1
  &kAtcAllZoneEtc_GMT_2, // 0x9d13da57, Etc/GMT-2
  &kAtcAllZoneEtc_GMT_3, // 0x9d13da58, Etc/GMT-3
  &kAtcAllZoneEtc_GMT_4, // 0x9d13da59, Etc/GMT-4
  &kAtcAllZoneEtc_GMT_5, // 0x9d13da5a, Etc/GMT-5
  &kAtcAllZoneEtc_GMT_6, // 0x9d13da5b, Etc/GMT-6
  &kAtcAllZoneEtc_GMT_7, // 0x9d13da5c, Etc/GMT-7
  &kAtcAllZoneEtc_GMT_8, // 0x9d13da5d, Etc/GMT-8
  &kAtcAllZoneEtc_GMT_9, // 0x9d13da5e, Etc/GMT-9
  &kAtcAllZoneAmerica_Nipigon, // 0x9d2a8b1a, America/Nipigon -> America/Toronto
  &kAtcAllZoneAmerica_Rio_Branco, // 0x9d352764, America/Rio_Branco
  &kAtcAllZoneAsia_Bangkok, // 0x9d6e3aaf, Asia/Bangkok
  &kAtcAllZoneAfrica_El_Aaiun, // 0x9d6fb118, Africa/El_Aaiun
  &kAtcAllZoneAmerica_North_Dakota_Center, // 0x9da42814, America/North_Dakota/Center
  &kAtcAllZoneAsia_Barnaul, // 0x9dba4997, Asia/Barnaul
  &kAtcAllZoneAfrica_Tripoli, // 0x9dfebd3d, Africa/Tripoli
  &kAtcAllZoneEurope_Istanbul, // 0x9e09d6e6, Europe/Istanbul
  &kAtcAllZoneIndian_Antananarivo, // 0x9ebf5289, Indian/Antananarivo -> Africa/Nairobi
  &kAtcAllZoneAfrica_Ndjamena, // 0x9fe09898, Africa/Ndjamena
  &kAtcAllZoneAmerica_Guyana, // 0x9ff7bd0b, America/Guyana
  &kAtcAllZoneAfrica_Dar_es_Salaam, // 0xa04c47b6, Africa/Dar_es_Salaam -> Africa/Nairobi
  &kAtcAllZoneAmerica_Havana, // 0xa0e15675, America/Havana
  &kAtcAllZoneAsia_Novosibirsk, // 0xa2a435cb, Asia/Novosibirsk
  &kAtcAllZoneEurope_Kiev, // 0xa2c19eb3, Europe/Kiev -> Europe/Kyiv
  &kAtcAllZoneEurope_Kyiv, // 0xa2c1e347, Europe/Kyiv
  &kAtcAllZoneEurope_Oslo, // 0xa2c3fba1, Europe/Oslo -> Europe/Berlin
  &kAtcAllZoneEurope_Riga, // 0xa2c57587, Europe/Riga
  &kAtcAllZoneEurope_Rome, // 0xa2c58fd7, Europe/Rome
  &kAtcAllZoneAmerica_Inuvik, // 0xa42189fc, America/Inuvik
  &kAtcAllZoneAmerica_Argentina_La_Rioja, // 0xa46b7eef, America/Argentina/La_Rioja
  &kAtcAllZoneAsia_Almaty, // 0xa61f41fa, Asia/Almaty
  &kAtcAllZoneAsia_Anadyr, // 0xa63cebd1, Asia/Anadyr
  &kAtcAllZoneAsia_Aqtobe, // 0xa67dcc4e, Asia/Aqtobe
  &kAtcAllZoneAsia_Atyrau, // 0xa6b6e068, Asia/Atyrau
  &kAtcAllZoneAmerica_Juneau, // 0xa6f13e2e, America/Juneau
  &kAtcAllZoneAustralia_Lord_Howe, // 0xa748b67d, Australia/Lord_Howe
  &kAtcAllZonePacific_Port_Moresby, // 0xa7ba7f68, Pacific/Port_Moresby
  &kAtcAllZoneAsia_Katmandu, // 0xa7ec12c7, Asia/Katmandu -> Asia/Kathmandu
  &kAtcAllZoneAsia_Beirut, // 0xa7f3d5fd, Asia/Beirut
  &kAtcAllZoneSingapore, // 0xa8598c8d, Singapore -> Asia/Singapore
  &kAtcAllZoneAfrica_Nairobi, // 0xa87ab57e, Africa/Nairobi
  &kAtcAllZoneAsia_Brunei, // 0xa8e595f7, Asia/Brunei -> Asia/Kuching
  &kAtcAllZoneUS_Pacific, // 0xa950f6ab, US/Pacific -> America/Los_Angeles
  &kAtcAllZonePacific_Galapagos, // 0xa952f752, Pacific/Galapagos
  &kAtcAllZoneAmerica_Argentina_Mendoza, // 0xa9f72d5c, America/Argentina/Mendoza
  &kAtcAllZoneAmerica_La_Paz, // 0xaa29125d, America/La_Paz
  &kAtcAllZoneAmerica_Noronha, // 0xab5116fb, America/Noronha
  &kAtcAllZoneAmerica_Coral_Harbour, // 0xabcb7569, America/Coral_Harbour -> America/Panama
  &kAtcAllZoneAmerica_Maceio, // 0xac80c6d4, America/Maceio
  &kAtcAllZoneAmerica_Manaus, // 0xac86bf8b, America/Manaus
  &kAtcAllZoneAmerica_Merida, // 0xacd172d8, America/Merida
  &kAtcAllZoneEurope_Chisinau, // 0xad58aa18, Europe/Chisinau
  &kAtcAllZoneAmerica_Nassau, // 0xaedef011, America/Nassau -> America/Toronto
  &kAtcAllZoneAmerica_Anguilla, // 0xafe31333, America/Anguilla -> America/Puerto_Rico
  &kAtcAllZoneEurope_Uzhgorod, // 0xb066f5d6, Europe/Uzhgorod -> Europe/Kyiv
  &kAtcAllZoneAustralia_Broken_Hill, // 0xb06eada3, Australia/Broken_Hill
  &kAtcAllZoneAsia_Bishkek, // 0xb0728553, Asia/Bishkek
  &kAtcAllZoneChile_EasterIsland, // 0xb0982af8, Chile/EasterIsland -> Pacific/Easter
  &kAtcAllZonePacific_Johnston, // 0xb15d7b36, Pacific/Johnston -> Pacific/Honolulu
  &kAtcAllZoneAfrica_Timbuktu, // 0xb164d56f, Africa/Timbuktu -> Africa/Abidjan
  &kAtcAllZoneAmerica_St_Thomas, // 0xb1b3d778, America/St_Thomas -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Paramaribo, // 0xb319e4c4, America/Paramaribo
  &kAtcAllZoneAmerica_Panama, // 0xb3863854, America/Panama
  &kAtcAllZoneCanada_Newfoundland, // 0xb396e991, Canada/Newfoundland -> America/St_Johns
  &kAtcAllZoneAsia_Harbin, // 0xb5af1186, Asia/Harbin -> Asia/Shanghai
  &kAtcAllZoneAsia_Hebron, // 0xb5eef250, Asia/Hebron
  &kAtcAllZoneAmerica_Goose_Bay, // 0xb649541e, America/Goose_Bay
  &kAtcAllZoneAmerica_Los_Angeles, // 0xb7f7e8f2, America/Los_Angeles
  &kAtcAllZoneAmerica_Recife, // 0xb8730494, America/Recife
  &kAtcAllZoneAmerica_Regina, // 0xb875371c, America/Regina
  &kAtcAllZoneAsia_Ashgabat, // 0xba87598d, Asia/Ashgabat
  &kAtcAllZoneIsrael, // 0xba88c9e5, Israel -> Asia/Jerusalem
  &kAtcAllZonePacific_Yap, // 0xbb40138d, Pacific/Yap -> Pacific/Port_Moresby
  &kAtcAllZoneAmerica_Halifax, // 0xbc5b7183, America/Halifax
  &kAtcAllZoneEurope_Ljubljana, // 0xbd98cdb7, Europe/Ljubljana -> Europe/Belgrade
  &kAtcAllZoneAsia_Kuwait, // 0xbe1b2f27, Asia/Kuwait -> Asia/Riyadh
  &kAtcAllZoneEurope_Tiraspol, // 0xbe704472, Europe/Tiraspol -> Europe/Chisinau
  &kAtcAllZoneAsia_Srednekolymsk, // 0xbf8e337d, Asia/Srednekolymsk
  &kAtcAllZoneAmerica_Argentina_Cordoba, // 0xbfccc308, America/Argentina/Cordoba
  &kAtcAllZoneAmerica_Tegucigalpa, // 0xbfd6fd4c, America/Tegucigalpa
  &kAtcAllZoneAmerica_Antigua, // 0xc067a32f, America/Antigua -> America/Puerto_Rico
  &kAtcAllZoneEurope_Busingen, // 0xc06d2cdf, Europe/Busingen -> Europe/Zurich
  &kAtcAllZoneAsia_Manila, // 0xc156c944, Asia/Manila
  &kAtcAllZoneAfrica_Kampala, // 0xc1d30e31, Africa/Kampala -> Africa/Nairobi
  &kAtcAllZoneAmerica_Knox_IN, // 0xc1db9a1c, America/Knox_IN -> America/Indiana/Knox
  &kAtcAllZoneAfrica_Abidjan, // 0xc21305a3, Africa/Abidjan
  &kAtcAllZoneAmerica_Virgin, // 0xc2183ab5, America/Virgin -> America/Puerto_Rico
  &kAtcAllZoneAsia_Phnom_Penh, // 0xc224945e, Asia/Phnom_Penh -> Asia/Bangkok
  &kAtcAllZoneAsia_Muscat, // 0xc2c3565f, Asia/Muscat -> Asia/Dubai
  &kAtcAllZoneAmerica_Punta_Arenas, // 0xc2c3bce7, America/Punta_Arenas
  &kAtcAllZonePortugal, // 0xc3274593, Portugal -> Europe/Lisbon
  &kAtcAllZoneNavajo, // 0xc4ef0e24, Navajo -> America/Denver
  &kAtcAllZoneAfrica_Casablanca, // 0xc59f1b33, Africa/Casablanca
  &kAtcAllZoneAmerica_Argentina_Rio_Gallegos, // 0xc5b0f565, America/Argentina/Rio_Gallegos
  &kAtcAllZoneAsia_Jayapura, // 0xc6833c2f, Asia/Jayapura
  &kAtcAllZoneAmerica_Resolute, // 0xc7093459, America/Resolute
  &kAtcAllZoneAsia_Chungking, // 0xc7121dd0, Asia/Chungking -> Asia/Shanghai
  &kAtcAllZoneGreenwich, // 0xc84d4221, Greenwich -> Etc/GMT
  &kAtcAllZoneAmerica_Rankin_Inlet, // 0xc8de4984, America/Rankin_Inlet
  &kAtcAllZonePoland, // 0xca913b23, Poland -> Europe/Warsaw
  &kAtcAllZoneUS_Central, // 0xcabdcb25, US/Central -> America/Chicago
  &kAtcAllZoneEurope_Vatican, // 0xcb485dca, Europe/Vatican -> Europe/Rome
  &kAtcAllZoneAmerica_Barbados, // 0xcbbc3b04, America/Barbados
  &kAtcAllZoneAmerica_Porto_Acre, // 0xcce5bf54, America/Porto_Acre -> America/Rio_Branco
  &kAtcAllZoneAmerica_Guadeloupe, // 0xcd1f8a31, America/Guadeloupe -> America/Puerto_Rico
  &kAtcAllZoneAntarctica_South_Pole, // 0xcd96b290, Antarctica/South_Pole -> Pacific/Auckland
  &kAtcAllZoneAsia_Riyadh, // 0xcd973d93, Asia/Riyadh
  &kAtcAllZoneAmerica_Dominica, // 0xcecb4c4a, America/Dominica -> America/Puerto_Rico
  &kAtcAllZoneEurope_San_Marino, // 0xcef7724b, Europe/San_Marino -> Europe/Rome
  &kAtcAllZoneAsia_Saigon, // 0xcf52f713, Asia/Saigon -> Asia/Ho_Chi_Minh
  &kAtcAllZonePacific_Easter, // 0xcf54f7e7, Pacific/Easter
  &kAtcAllZoneAsia_Singapore, // 0xcf8581fa, Asia/Singapore
  &kAtcAllZoneAsia_Krasnoyarsk, // 0xd0376c6a, Asia/Krasnoyarsk
  &kAtcAllZoneEurope_Belfast, // 0xd07dd1e5, Europe/Belfast -> Europe/London
  &kAtcAllZoneAmerica_Mexico_City, // 0xd0d93f43, America/Mexico_City
  &kAtcAllZoneUniversal, // 0xd0ff523e, Universal -> Etc/UTC
  &kAtcAllZoneAsia_Taipei, // 0xd1a844ae, Asia/Taipei
  &kAtcAllZoneAsia_Tehran, // 0xd1f02254, Asia/Tehran
  &kAtcAllZoneAsia_Thimbu, // 0xd226e31b, Asia/Thimbu -> Asia/Thimphu
  &kAtcAllZoneArctic_Longyearbyen, // 0xd23e7859, Arctic/Longyearbyen -> Europe/Berlin
  &kAtcAllZoneAustralia_Queensland, // 0xd326ed0a, Australia/Queensland -> Australia/Brisbane
  &kAtcAllZoneEurope_Kaliningrad, // 0xd33b2f28, Europe/Kaliningrad
  &kAtcAllZoneAmerica_Argentina_Buenos_Aires, // 0xd43b4c0d, America/Argentina/Buenos_Aires
  &kAtcAllZoneTurkey, // 0xd455e469, Turkey -> Europe/Istanbul
  &kAtcAllZoneAfrica_Juba, // 0xd51b395c, Africa/Juba
  &kAtcAllZoneAfrica_Lome, // 0xd51c3a07, Africa/Lome -> Africa/Abidjan
  &kAtcAllZoneAsia_Urumqi, // 0xd5379735, Asia/Urumqi
  &kAtcAllZoneAmerica_Cambridge_Bay, // 0xd5a44aff, America/Cambridge_Bay
  &kAtcAllZoneAfrica_Johannesburg, // 0xd5d157a0, Africa/Johannesburg
  &kAtcAllZoneAmerica_Port_of_Spain, // 0xd8b28d59, America/Port_of_Spain -> America/Puerto_Rico
  &kAtcAllZoneEtc_GMT, // 0xd8e2de58, Etc/GMT
  &kAtcAllZoneEtc_UCT, // 0xd8e3189c, Etc/UCT -> Etc/UTC
  &kAtcAllZoneEtc_UTC, // 0xd8e31abc, Etc/UTC
  &kAtcAllZoneAmerica_Yakutat, // 0xd8ee31e9, America/Yakutat
  &kAtcAllZoneAfrica_Algiers, // 0xd94515c1, Africa/Algiers
  &kAtcAllZonePST8PDT, // 0xd99ee2dc, PST8PDT
  &kAtcAllZoneEurope_Bratislava, // 0xda493bed, Europe/Bratislava -> Europe/Prague
  &kAtcAllZoneEurope_Simferopol, // 0xda9eb724, Europe/Simferopol
  &kAtcAllZonePacific_Funafuti, // 0xdb402d65, Pacific/Funafuti -> Pacific/Tarawa
  &kAtcAllZoneAmerica_Matamoros, // 0xdd1b0259, America/Matamoros
  &kAtcAllZonePacific_Kanton, // 0xdd512f0e, Pacific/Kanton
  &kAtcAllZoneAsia_Yangon, // 0xdd54a8be, Asia/Yangon
  &kAtcAllZoneEurope_Vilnius, // 0xdd63b8ce, Europe/Vilnius
  &kAtcAllZoneAustralia_West, // 0xdd858a5d, Australia/West -> Australia/Perth
  &kAtcAllZonePacific_Kosrae, // 0xde5139a8, Pacific/Kosrae
  &kAtcAllZoneAmerica_Kentucky_Monticello, // 0xde71c439, America/Kentucky/Monticello
  &kAtcAllZoneEurope_Brussels, // 0xdee07337, Europe/Brussels
  &kAtcAllZoneAmerica_Swift_Current, // 0xdef98e55, America/Swift_Current
  &kAtcAllZoneAmerica_Rosario, // 0xdf448665, America/Rosario -> America/Argentina/Cordoba
  &kAtcAllZoneAsia_Irkutsk, // 0xdfbf213f, Asia/Irkutsk
  &kAtcAllZoneEurope_Ulyanovsk, // 0xe03783d0, Europe/Ulyanovsk
  &kAtcAllZoneAustralia_Lindeman, // 0xe05029e2, Australia/Lindeman
  &kAtcAllZoneEurope_Belgrade, // 0xe0532b3a, Europe/Belgrade
  &kAtcAllZoneAfrica_Blantyre, // 0xe08d813b, Africa/Blantyre -> Africa/Maputo
  &kAtcAllZoneAmerica_Menominee, // 0xe0e9c583, America/Menominee
  &kAtcAllZoneEurope_Copenhagen, // 0xe0ed30bc, Europe/Copenhagen -> Europe/Berlin
  &kAtcAllZoneAtlantic_Faroe, // 0xe110a971, Atlantic/Faroe
  &kAtcAllZonePacific_Majuro, // 0xe1f95371, Pacific/Majuro -> Pacific/Tarawa
  &kAtcAllZoneAntarctica_Casey, // 0xe2022583, Antarctica/Casey
  &kAtcAllZoneAntarctica_Davis, // 0xe2144b45, Antarctica/Davis
  &kAtcAllZoneEurope_Astrakhan, // 0xe22256e1, Europe/Astrakhan
  &kAtcAllZonePacific_Midway, // 0xe286d38e, Pacific/Midway -> Pacific/Pago_Pago
  &kAtcAllZoneAntarctica_Syowa, // 0xe330c7e1, Antarctica/Syowa -> Asia/Riyadh
  &kAtcAllZoneAntarctica_Troll, // 0xe33f085b, Antarctica/Troll
  &kAtcAllZoneEurope_Saratov, // 0xe4315da4, Europe/Saratov
  &kAtcAllZonePacific_Noumea, // 0xe551b788, Pacific/Noumea
  &kAtcAllZoneIceland, // 0xe56a35b5, Iceland -> Africa/Abidjan
  &kAtcAllZoneIndian_Mayotte, // 0xe6880bca, Indian/Mayotte -> Africa/Nairobi
  &kAtcAllZoneAustralia_Tasmania, // 0xe6d76648, Australia/Tasmania -> Australia/Hobart
  &kAtcAllZonePacific_Honolulu, // 0xe6e70af9, Pacific/Honolulu
  &kAtcAllZoneAmerica_Kralendijk, // 0xe7c456c5, America/Kralendijk -> America/Puerto_Rico
  &kAtcAllZoneAmerica_Argentina_Tucuman, // 0xe96399eb, America/Argentina/Tucuman
  &kAtcAllZonePacific_Ponape, // 0xe9f80086, Pacific/Ponape -> Pacific/Guadalcanal
  &kAtcAllZoneEurope_Zaporozhye, // 0xeab9767f, Europe/Zaporozhye -> Europe/Kyiv
  &kAtcAllZoneEurope_Isle_of_Man, // 0xeaf84580, Europe/Isle_of_Man -> Europe/London
  &kAtcAllZoneAsia_Magadan, // 0xebacc19b, Asia/Magadan
  &kAtcAllZoneAmerica_Ojinaga, // 0xebfde83f, America/Ojinaga
  &kAtcAllZonePacific_Saipan, // 0xeff7a35f, Pacific/Saipan -> Pacific/Guam
  &kAtcAllZoneCST6CDT, // 0xf0e87d00, CST6CDT
  &kAtcAllZonePacific_Tahiti, // 0xf24c2446, Pacific/Tahiti
  &kAtcAllZonePacific_Tarawa, // 0xf2517e63, Pacific/Tarawa
  &kAtcAllZoneMST7MDT, // 0xf2af9375, MST7MDT
  &kAtcAllZoneCanada_Eastern, // 0xf3612d5e, Canada/Eastern -> America/Toronto
  &kAtcAllZoneAsia_Tashkent, // 0xf3924254, Asia/Tashkent
  &kAtcAllZoneAsia_Sakhalin, // 0xf4a1c9bd, Asia/Sakhalin
  &kAtcAllZonePacific_Guadalcanal, // 0xf4dd25f0, Pacific/Guadalcanal
  &kAtcAllZoneEtc_GMT0, // 0xf53ea988, Etc/GMT0 -> Etc/GMT
  &kAtcAllZoneEtc_Zulu, // 0xf549c240, Etc/Zulu -> Etc/UTC
  &kAtcAllZoneAmerica_Danmarkshavn, // 0xf554d204, America/Danmarkshavn
  &kAtcAllZoneAsia_Shanghai, // 0xf895a7f5, Asia/Shanghai
  &kAtcAllZoneEurope_Gibraltar, // 0xf8e325fc, Europe/Gibraltar
  &kAtcAllZoneAsia_Chongqing, // 0xf937fb90, Asia/Chongqing -> Asia/Shanghai
  &kAtcAllZoneAtlantic_Azores, // 0xf93ed918, Atlantic/Azores
  &kAtcAllZonePacific_Wallis, // 0xf94ddb0f, Pacific/Wallis -> Pacific/Tarawa
  &kAtcAllZoneAmerica_Thunder_Bay, // 0xf962e71b, America/Thunder_Bay -> America/Toronto
  &kAtcAllZoneAmerica_Eirunepe, // 0xf9b29683, America/Eirunepe
  &kAtcAllZoneAmerica_Montevideo, // 0xfa214780, America/Montevideo
  &kAtcAllZoneUS_Alaska, // 0xfa300bc9, US/Alaska -> America/Anchorage
  &kAtcAllZoneGB_Eire, // 0xfa70e300, GB-Eire -> Europe/London
  &kAtcAllZoneEurope_Kirov, // 0xfaf5abef, Europe/Kirov
  &kAtcAllZoneEurope_Malta, // 0xfb1560f3, Europe/Malta
  &kAtcAllZoneEurope_Minsk, // 0xfb19cc66, Europe/Minsk
  &kAtcAllZoneEurope_Bucharest, // 0xfb349ec5, Europe/Bucharest
  &kAtcAllZoneAfrica_Khartoum, // 0xfb3d4205, Africa/Khartoum
  &kAtcAllZoneEurope_Paris, // 0xfb4bc2a3, Europe/Paris
  &kAtcAllZoneAsia_Yekaterinburg, // 0xfb544c6e, Asia/Yekaterinburg
  &kAtcAllZoneEurope_Sofia, // 0xfb898656, Europe/Sofia
  &kAtcAllZoneCanada_Mountain, // 0xfb8a8217, Canada/Mountain -> America/Edmonton
  &kAtcAllZoneEurope_Vaduz, // 0xfbb81bae, Europe/Vaduz -> Europe/Zurich
  &kAtcAllZoneAtlantic_Canary, // 0xfc23f2c2, Atlantic/Canary
  &kAtcAllZoneMexico_BajaNorte, // 0xfcf7150f, Mexico/BajaNorte -> America/Tijuana
  &kAtcAllZoneAmerica_Santa_Isabel, // 0xfd18a56c, America/Santa_Isabel -> America/Tijuana
  &kAtcAllZoneAmerica_Campo_Grande, // 0xfec3e7a6, America/Campo_Grande

};
