// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedbtestingm/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedbtestingm
//     --tz_version 2025b
//     --actions zonedb
//     --language c
//     --scope full
//     --db_namespace Testing
//     --start_year 2000
//     --until_year 2200
//     --nocompress
//     --include_list include_list.txt
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025b
//
// Supported Zones: 17 (16 zones, 1 links)
// Unsupported Zones: 580 (324 zones, 256 links)
//
// Requested Years: [2000,2200]
// Accurate Years: [2000,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1966,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1966,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 17
//   Eras: 22
//   Policies: 8
//   Rules: 201
//
// Memory (8-bits):
//   Context: 20
//   Rules: 2211
//   Policies: 24
//   Eras: 264
//   Zones: 208
//   Links: 13
//   Registry: 34
//   Formats: 37
//   Letters: 23
//   Fragments: 0
//   Names: 268 (original: 268)
//   TOTAL: 3102
//
// Memory (32-bits):
//   Context: 28
//   Rules: 2412
//   Policies: 64
//   Eras: 352
//   Zones: 384
//   Links: 24
//   Registry: 68
//   Formats: 37
//   Letters: 33
//   Fragments: 0
//   Names: 268 (original: 268)
//   TOTAL: 3670
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_TESTING_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_TESTING_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcTestingZoneRegistrySize 16
extern const AtcZoneInfo * const kAtcTestingZoneRegistry[16];

// Zones and Links
#define kAtcTestingZoneAndLinkRegistrySize 17
extern const AtcZoneInfo * const kAtcTestingZoneAndLinkRegistry[17];

#ifdef __cplusplus
}
#endif

#endif
