// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb2000m/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb2000m
//     --tz_version 2025b
//     --actions zonedb
//     --language c
//     --scope full
//     --db_namespace Zonedb2000
//     --start_year 2000
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025b
//
// Supported Zones: 597 (340 zones, 257 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2000,2200]
// Accurate Years: [2000,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1950,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1950,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 597
//   Eras: 647
//   Policies: 82
//   Rules: 731
//
// Memory (8-bits):
//   Context: 20
//   Rules: 8041
//   Policies: 246
//   Eras: 7764
//   Zones: 4420
//   Links: 3341
//   Registry: 1194
//   Formats: 231
//   Letters: 46
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 34397
//
// Memory (32-bits):
//   Context: 28
//   Rules: 8772
//   Policies: 656
//   Eras: 10352
//   Zones: 8160
//   Links: 6168
//   Registry: 2388
//   Formats: 231
//   Letters: 64
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 45913
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ZONEDB2000_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ZONEDB2000_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcZonedb2000ZoneRegistrySize 340
extern const AtcZoneInfo * const kAtcZonedb2000ZoneRegistry[340];

// Zones and Links
#define kAtcZonedb2000ZoneAndLinkRegistrySize 597
extern const AtcZoneInfo * const kAtcZonedb2000ZoneAndLinkRegistry[597];

#ifdef __cplusplus
}
#endif

#endif
