// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/acetimec/src/zonedb/tzfiles
//     --output_dir /home/brian/src/acetimec/src/zonedb
//     --tz_version 2024a
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace Atc
//     --start_year 2000
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2024a
//
// Supported Zones: 596 (351 zones, 245 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2000,2200]
// Accurate Years: [2000,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1950,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1950,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 596
//   Eras: 657
//   Policies: 83
//   Rules: 735
//
// Memory (8-bits):
//   Context: 16
//   Rules: 8820
//   Policies: 249
//   Eras: 9855
//   Zones: 4563
//   Links: 3185
//   Registry: 1192
//   Formats: 597
//   Letters: 46
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 37599
//
// Memory (32-bits):
//   Context: 24
//   Rules: 8820
//   Policies: 664
//   Eras: 13140
//   Zones: 8424
//   Links: 5880
//   Registry: 2384
//   Formats: 597
//   Letters: 64
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 49073
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcZoneRegistrySize 351
extern const AtcZoneInfo * const kAtcZoneRegistry[351];

// Zones and Links
#define kAtcZoneAndLinkRegistrySize 596
extern const AtcZoneInfo * const kAtcZoneAndLinkRegistry[596];

#ifdef __cplusplus
}
#endif

#endif
