// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeC/src/zonedb/tzfiles
//     --output_dir /home/brian/src/AceTimeC/src/zonedb
//     --tz_version 2023c
//     --action zonedb
//     --language c
//     --scope extended
//     --db_namespace Atc
//     --offset_granularity 1
//     --delta_granularity 60
//     --until_at_granularity 1
//     --generate_int16_years
//     --generate_hires
//     --start_year 2000
//     --until_year 10000
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2023c
//
// Supported Zones: 596 (350 zones, 246 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Original Years:  [1844,2087]
// Generated Years: [1950,2087]
// Estimator Years: [1950,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 596
//   Eras: 646
//   Policies: 83
//   Rules: 735
//
// Memory (8-bits):
//   Rules: 8820
//   Policies: 249
//   Eras: 9690
//   Zones: 4550
//   Links: 3198
//   Registry: 1192
//   Formats: 597
//   Letters: 46
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 37418
//
// Memory (32-bits):
//   Rules: 8820
//   Policies: 664
//   Eras: 12920
//   Zones: 8400
//   Links: 5904
//   Registry: 2384
//   Formats: 597
//   Letters: 64
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 48829
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcZoneRegistrySize 350
extern const AtcZoneInfo * const kAtcZoneRegistry[350];

// Zones and Links
#define kAtcZoneAndLinkRegistrySize 596
extern const AtcZoneInfo * const kAtcZoneAndLinkRegistry[596];

#ifdef __cplusplus
}
#endif

#endif
