// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb
//     --tz_version 2025a
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace Atc
//     --start_year 2000
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025a
//
// Supported Zones: 596 (339 zones, 257 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2000,2200]
// Accurate Years: [2000,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1950,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1950,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 596
//   Eras: 645
//   Policies: 82
//   Rules: 731
//
// Memory (8-bits):
//   Context: 16
//   Rules: 8772
//   Policies: 246
//   Eras: 9675
//   Zones: 4407
//   Links: 3341
//   Registry: 1192
//   Formats: 231
//   Letters: 46
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 37002
//
// Memory (32-bits):
//   Context: 24
//   Rules: 8772
//   Policies: 656
//   Eras: 12900
//   Zones: 8136
//   Links: 6168
//   Registry: 2384
//   Formats: 231
//   Letters: 64
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 48411
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcZoneRegistrySize 339
extern const AtcZoneInfo * const kAtcZoneRegistry[339];

// Zones and Links
#define kAtcZoneAndLinkRegistrySize 596
extern const AtcZoneInfo * const kAtcZoneAndLinkRegistry[596];

#ifdef __cplusplus
}
#endif

#endif
