// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/dev/tz
//     --output_dir /home/brian/src/AceTimeC/src/ace_time_c/zonedb
//     --tz_version 2022a
//     --action zonedb
//     --language c
//     --scope extended
//     --start_year 2000
//     --until_year 2050
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2022a
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDBX_ZONE_POLICIES_H
#define ACE_TIME_C_ZONEDBX_ZONE_POLICIES_H

#include "../zone_info.h"

//---------------------------------------------------------------------------
// Supported zone policies: 83
//---------------------------------------------------------------------------

extern const struct AtcZonePolicy kAtcPolicyAN;
extern const struct AtcZonePolicy kAtcPolicyAQ;
extern const struct AtcZonePolicy kAtcPolicyAS;
extern const struct AtcZonePolicy kAtcPolicyAT;
extern const struct AtcZonePolicy kAtcPolicyAV;
extern const struct AtcZonePolicy kAtcPolicyAW;
extern const struct AtcZonePolicy kAtcPolicyArg;
extern const struct AtcZonePolicy kAtcPolicyArmenia;
extern const struct AtcZonePolicy kAtcPolicyAus;
extern const struct AtcZonePolicy kAtcPolicyAzer;
extern const struct AtcZonePolicy kAtcPolicyBarb;
extern const struct AtcZonePolicy kAtcPolicyBelize;
extern const struct AtcZonePolicy kAtcPolicyBrazil;
extern const struct AtcZonePolicy kAtcPolicyC_Eur;
extern const struct AtcZonePolicy kAtcPolicyCO;
extern const struct AtcZonePolicy kAtcPolicyCR;
extern const struct AtcZonePolicy kAtcPolicyCanada;
extern const struct AtcZonePolicy kAtcPolicyChatham;
extern const struct AtcZonePolicy kAtcPolicyChile;
extern const struct AtcZonePolicy kAtcPolicyCook;
extern const struct AtcZonePolicy kAtcPolicyCuba;
extern const struct AtcZonePolicy kAtcPolicyDhaka;
extern const struct AtcZonePolicy kAtcPolicyE_EurAsia;
extern const struct AtcZonePolicy kAtcPolicyEU;
extern const struct AtcZonePolicy kAtcPolicyEUAsia;
extern const struct AtcZonePolicy kAtcPolicyEcuador;
extern const struct AtcZonePolicy kAtcPolicyEgypt;
extern const struct AtcZonePolicy kAtcPolicyEire;
extern const struct AtcZonePolicy kAtcPolicyFalk;
extern const struct AtcZonePolicy kAtcPolicyFiji;
extern const struct AtcZonePolicy kAtcPolicyGuam;
extern const struct AtcZonePolicy kAtcPolicyGuat;
extern const struct AtcZonePolicy kAtcPolicyHK;
extern const struct AtcZonePolicy kAtcPolicyHaiti;
extern const struct AtcZonePolicy kAtcPolicyHoliday;
extern const struct AtcZonePolicy kAtcPolicyHond;
extern const struct AtcZonePolicy kAtcPolicyIran;
extern const struct AtcZonePolicy kAtcPolicyIraq;
extern const struct AtcZonePolicy kAtcPolicyJapan;
extern const struct AtcZonePolicy kAtcPolicyJordan;
extern const struct AtcZonePolicy kAtcPolicyKyrgyz;
extern const struct AtcZonePolicy kAtcPolicyLH;
extern const struct AtcZonePolicy kAtcPolicyLebanon;
extern const struct AtcZonePolicy kAtcPolicyLibya;
extern const struct AtcZonePolicy kAtcPolicyMacau;
extern const struct AtcZonePolicy kAtcPolicyMauritius;
extern const struct AtcZonePolicy kAtcPolicyMexico;
extern const struct AtcZonePolicy kAtcPolicyMoldova;
extern const struct AtcZonePolicy kAtcPolicyMoncton;
extern const struct AtcZonePolicy kAtcPolicyMongol;
extern const struct AtcZonePolicy kAtcPolicyMorocco;
extern const struct AtcZonePolicy kAtcPolicyNC;
extern const struct AtcZonePolicy kAtcPolicyNT_YK;
extern const struct AtcZonePolicy kAtcPolicyNZ;
extern const struct AtcZonePolicy kAtcPolicyNamibia;
extern const struct AtcZonePolicy kAtcPolicyNic;
extern const struct AtcZonePolicy kAtcPolicyPRC;
extern const struct AtcZonePolicy kAtcPolicyPakistan;
extern const struct AtcZonePolicy kAtcPolicyPalestine;
extern const struct AtcZonePolicy kAtcPolicyPara;
extern const struct AtcZonePolicy kAtcPolicyPeru;
extern const struct AtcZonePolicy kAtcPolicyPhil;
extern const struct AtcZonePolicy kAtcPolicyROK;
extern const struct AtcZonePolicy kAtcPolicyRussia;
extern const struct AtcZonePolicy kAtcPolicyRussiaAsia;
extern const struct AtcZonePolicy kAtcPolicySA;
extern const struct AtcZonePolicy kAtcPolicySalv;
extern const struct AtcZonePolicy kAtcPolicySanLuis;
extern const struct AtcZonePolicy kAtcPolicyStJohns;
extern const struct AtcZonePolicy kAtcPolicySudan;
extern const struct AtcZonePolicy kAtcPolicySyria;
extern const struct AtcZonePolicy kAtcPolicyTaiwan;
extern const struct AtcZonePolicy kAtcPolicyThule;
extern const struct AtcZonePolicy kAtcPolicyTonga;
extern const struct AtcZonePolicy kAtcPolicyTroll;
extern const struct AtcZonePolicy kAtcPolicyTunisia;
extern const struct AtcZonePolicy kAtcPolicyTurkey;
extern const struct AtcZonePolicy kAtcPolicyUS;
extern const struct AtcZonePolicy kAtcPolicyUruguay;
extern const struct AtcZonePolicy kAtcPolicyVanuatu;
extern const struct AtcZonePolicy kAtcPolicyWS;
extern const struct AtcZonePolicy kAtcPolicyWinn;
extern const struct AtcZonePolicy kAtcPolicyZion;


//---------------------------------------------------------------------------
// Unsupported zone policies: 55
//---------------------------------------------------------------------------

// Albania (unused)
// Algeria (unused)
// Austria (unused)
// Belgium (unused)
// Bermuda (unused)
// Bulg (unused)
// CA (unused)
// Chicago (unused)
// Cyprus (unused)
// Czech (unused)
// DR (unused)
// Denmark (unused)
// Denver (unused)
// Detroit (unused)
// E-Eur (unused)
// Edm (unused)
// EgyptAsia (unused)
// Finland (unused)
// France (unused)
// GB-Eire (unused)
// Germany (unused)
// Greece (unused)
// Halifax (unused)
// Hungary (unused)
// Iceland (unused)
// Indianapolis (unused)
// Italy (unused)
// Latvia (unused)
// Louisville (unused)
// Lux (unused)
// Malta (unused)
// Marengo (unused)
// Menominee (unused)
// NBorneo (unused)
// NYC (unused)
// Neth (unused)
// Norway (unused)
// Perry (unused)
// Pike (unused)
// Poland (unused)
// Port (unused)
// Pulaski (unused)
// Regina (unused)
// Romania (unused)
// Shang (unused)
// SovietZone (unused)
// Spain (unused)
// SpainAfrica (unused)
// Starke (unused)
// Swift (unused)
// Swiss (unused)
// Toronto (unused)
// Vanc (unused)
// Vincennes (unused)
// W-Eur (unused)


//---------------------------------------------------------------------------
// Notable zone policies: 9
//---------------------------------------------------------------------------

// Belize (LETTER 'CST' not single character)
// Eire (SAVE (delta_offset) '-1:00' different from 1:00)
// LH (SAVE (delta_offset) '0:30' different from 1:00)
// Moncton (AT '0:01' not on 15-minute boundary)
// Morocco (SAVE (delta_offset) '-1:00' different from 1:00)
// Namibia (
//   LETTER 'CAT' not single character,
//   LETTER 'WAT' not single character,
//   SAVE (delta_offset) '-1:00' different from 1:00,
// )
// Palestine (AT '0:01' not on 15-minute boundary)
// StJohns (
//   AT '0:01' not on 15-minute boundary,
//   LETTER 'DD' not single character,
//   SAVE (delta_offset) '2:00' different from 1:00,
// )
// Troll (
//   LETTER '+00' not single character,
//   LETTER '+02' not single character,
//   SAVE (delta_offset) '2:00' different from 1:00,
// )


#endif
