// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/dev/tz
//     --output_dir /home/brian/src/AceTimeC/src/ace_time_c/zonedb
//     --tz_version 2022d
//     --action zonedb
//     --language c
//     --scope extended
//     --generate_int16_years
//     --start_year 2000
//     --until_year 10000
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2022d
//
// DO NOT EDIT

#include "zone_infos.h"
#include "zone_registry.h"

//---------------------------------------------------------------------------
// Zone Info registry. Sorted by zoneId.
//---------------------------------------------------------------------------
const AtcZoneInfo * const kAtcZoneRegistry[354]  = {
  &kAtcZoneAmerica_St_Johns, // 0x04b14e6e, America/St_Johns
  &kAtcZoneAmerica_North_Dakota_New_Salem, // 0x04f9958e, America/North_Dakota/New_Salem
  &kAtcZoneAsia_Jakarta, // 0x0506ab50, Asia/Jakarta
  &kAtcZoneAmerica_Mazatlan, // 0x0532189e, America/Mazatlan
  &kAtcZonePacific_Fakaofo, // 0x06532bba, Pacific/Fakaofo
  &kAtcZoneAmerica_Hermosillo, // 0x065d21c4, America/Hermosillo
  &kAtcZoneAsia_Tbilisi, // 0x0903e442, Asia/Tbilisi
  &kAtcZoneAmerica_Indiana_Tell_City, // 0x09263612, America/Indiana/Tell_City
  &kAtcZoneAmerica_Boa_Vista, // 0x0a7b7efe, America/Boa_Vista
  &kAtcZoneAsia_Colombo, // 0x0af0e91d, Asia/Colombo
  &kAtcZoneCET, // 0x0b87d921, CET
  &kAtcZoneEET, // 0x0b87e1a3, EET
  &kAtcZoneEST, // 0x0b87e371, EST
  &kAtcZoneHST, // 0x0b87f034, HST
  &kAtcZoneMET, // 0x0b8803ab, MET
  &kAtcZoneMST, // 0x0b880579, MST
  &kAtcZoneWET, // 0x0b882e35, WET
  &kAtcZoneAmerica_Guatemala, // 0x0c8259f7, America/Guatemala
  &kAtcZoneAfrica_Monrovia, // 0x0ce90385, Africa/Monrovia
  &kAtcZoneAntarctica_Rothera, // 0x0e86d203, Antarctica/Rothera
  &kAtcZoneAmerica_Yellowknife, // 0x0f76c76f, America/Yellowknife
  &kAtcZoneAustralia_Melbourne, // 0x0fe559a3, Australia/Melbourne
  &kAtcZoneAmerica_Sao_Paulo, // 0x1063bfc9, America/Sao_Paulo
  &kAtcZoneAmerica_Indiana_Vevay, // 0x10aca054, America/Indiana/Vevay
  &kAtcZoneAmerica_Scoresbysund, // 0x123f8d2a, America/Scoresbysund
  &kAtcZoneAsia_Samarkand, // 0x13ae5104, Asia/Samarkand
  &kAtcZoneAsia_Amman, // 0x148d21bc, Asia/Amman
  &kAtcZoneAsia_Aqtau, // 0x148f710e, Asia/Aqtau
  &kAtcZoneAsia_Chita, // 0x14ae863b, Asia/Chita
  &kAtcZoneAsia_Dhaka, // 0x14c07b8b, Asia/Dhaka
  &kAtcZoneAsia_Dubai, // 0x14c79f77, Asia/Dubai
  &kAtcZoneAmerica_Bahia_Banderas, // 0x14f6329a, America/Bahia_Banderas
  &kAtcZoneAsia_Kabul, // 0x153b5601, Asia/Kabul
  &kAtcZoneAsia_Macau, // 0x155f88b9, Asia/Macau
  &kAtcZoneAsia_Qatar, // 0x15a8330b, Asia/Qatar
  &kAtcZoneAsia_Seoul, // 0x15ce82da, Asia/Seoul
  &kAtcZoneAsia_Tokyo, // 0x15e606a8, Asia/Tokyo
  &kAtcZoneAsia_Tomsk, // 0x15e60e60, Asia/Tomsk
  &kAtcZoneAsia_Thimphu, // 0x170380d1, Asia/Thimphu
  &kAtcZoneAmerica_Guayaquil, // 0x17e64958, America/Guayaquil
  &kAtcZoneAmerica_Kentucky_Louisville, // 0x1a21024b, America/Kentucky/Louisville
  &kAtcZoneAsia_Pontianak, // 0x1a76c057, Asia/Pontianak
  &kAtcZoneAmerica_New_York, // 0x1e2a7654, America/New_York
  &kAtcZoneAsia_Baku, // 0x1fa788b5, Asia/Baku
  &kAtcZoneAsia_Dili, // 0x1fa8c394, Asia/Dili
  &kAtcZoneAsia_Gaza, // 0x1faa4875, Asia/Gaza
  &kAtcZoneAsia_Hovd, // 0x1fab0fe3, Asia/Hovd
  &kAtcZoneAsia_Omsk, // 0x1faeddac, Asia/Omsk
  &kAtcZoneAsia_Oral, // 0x1faef0a0, Asia/Oral
  &kAtcZoneAsia_Ho_Chi_Minh, // 0x20f2d127, Asia/Ho_Chi_Minh
  &kAtcZoneAsia_Damascus, // 0x20fbb063, Asia/Damascus
  &kAtcZonePacific_Apia, // 0x23359b5e, Pacific/Apia
  &kAtcZonePacific_Fiji, // 0x23383ba5, Pacific/Fiji
  &kAtcZonePacific_Guam, // 0x2338f9ed, Pacific/Guam
  &kAtcZonePacific_Niue, // 0x233ca014, Pacific/Niue
  &kAtcZoneAustralia_Adelaide, // 0x2428e8a3, Australia/Adelaide
  &kAtcZonePacific_Auckland, // 0x25062f86, Pacific/Auckland
  &kAtcZonePacific_Tongatapu, // 0x262ca836, Pacific/Tongatapu
  &kAtcZoneAmerica_Monterrey, // 0x269a1deb, America/Monterrey
  &kAtcZoneAustralia_Darwin, // 0x2876bdff, Australia/Darwin
  &kAtcZoneAsia_Famagusta, // 0x289b4f8b, Asia/Famagusta
  &kAtcZoneAmerica_Indiana_Vincennes, // 0x28a0b212, America/Indiana/Vincennes
  &kAtcZoneAmerica_Indiana_Indianapolis, // 0x28a669a4, America/Indiana/Indianapolis
  &kAtcZoneAsia_Vladivostok, // 0x29de34a8, Asia/Vladivostok
  &kAtcZoneAmerica_Fortaleza, // 0x2ad018ee, America/Fortaleza
  &kAtcZoneAmerica_Vancouver, // 0x2c6f6b1f, America/Vancouver
  &kAtcZoneAmerica_Pangnirtung, // 0x2d999193, America/Pangnirtung
  &kAtcZoneAmerica_Iqaluit, // 0x2de310bf, America/Iqaluit
  &kAtcZonePacific_Chatham, // 0x2f0de999, Pacific/Chatham
  &kAtcZoneAmerica_Indiana_Marengo, // 0x2feeee72, America/Indiana/Marengo
  &kAtcZoneEurope_Tallinn, // 0x30c4e096, Europe/Tallinn
  &kAtcZoneAsia_Ulaanbaatar, // 0x30f0cc4e, Asia/Ulaanbaatar
  &kAtcZoneAmerica_Argentina_Ushuaia, // 0x320dcdde, America/Argentina/Ushuaia
  &kAtcZoneAustralia_Hobart, // 0x32bf951a, Australia/Hobart
  &kAtcZoneAsia_Dushanbe, // 0x32fc5c3c, Asia/Dushanbe
  &kAtcZoneAtlantic_South_Georgia, // 0x33013174, Atlantic/South_Georgia
  &kAtcZoneAmerica_Phoenix, // 0x34b5af01, America/Phoenix
  &kAtcZoneAntarctica_Mawson, // 0x399cd863, Antarctica/Mawson
  &kAtcZoneAmerica_Caracas, // 0x3be064f4, America/Caracas
  &kAtcZoneAmerica_Cayenne, // 0x3c617269, America/Cayenne
  &kAtcZoneAtlantic_Bermuda, // 0x3d4bb1c4, Atlantic/Bermuda
  &kAtcZoneAmerica_Managua, // 0x3d5e7600, America/Managua
  &kAtcZoneAmerica_Argentina_San_Juan, // 0x3e1009bd, America/Argentina/San_Juan
  &kAtcZoneAmerica_Argentina_San_Luis, // 0x3e11238c, America/Argentina/San_Luis
  &kAtcZoneEurope_Volgograd, // 0x3ed0f389, Europe/Volgograd
  &kAtcZoneAmerica_Fort_Nelson, // 0x3f437e0f, America/Fort_Nelson
  &kAtcZoneEtc_GMT_PLUS_10, // 0x3f8f1cc4, Etc/GMT+10
  &kAtcZoneEtc_GMT_PLUS_11, // 0x3f8f1cc5, Etc/GMT+11
  &kAtcZoneEtc_GMT_PLUS_12, // 0x3f8f1cc6, Etc/GMT+12
  &kAtcZoneEtc_GMT_10, // 0x3f8f2546, Etc/GMT-10
  &kAtcZoneEtc_GMT_11, // 0x3f8f2547, Etc/GMT-11
  &kAtcZoneEtc_GMT_12, // 0x3f8f2548, Etc/GMT-12
  &kAtcZoneEtc_GMT_13, // 0x3f8f2549, Etc/GMT-13
  &kAtcZoneEtc_GMT_14, // 0x3f8f254a, Etc/GMT-14
  &kAtcZoneAntarctica_Palmer, // 0x40962f4f, Antarctica/Palmer
  &kAtcZoneEurope_Athens, // 0x4318fa27, Europe/Athens
  &kAtcZoneAmerica_Indiana_Winamac, // 0x4413fa69, America/Indiana/Winamac
  &kAtcZoneEurope_Berlin, // 0x44644c20, Europe/Berlin
  &kAtcZoneIndian_Chagos, // 0x456f7c3c, Indian/Chagos
  &kAtcZoneAsia_Ust_Nera, // 0x4785f921, Asia/Ust-Nera
  &kAtcZoneEurope_Dublin, // 0x4a275f62, Europe/Dublin
  &kAtcZoneAsia_Nicosia, // 0x4b0fcf78, Asia/Nicosia
  &kAtcZoneAmerica_Chicago, // 0x4b92b5d4, America/Chicago
  &kAtcZoneAustralia_Sydney, // 0x4d1e9776, Australia/Sydney
  &kAtcZoneAustralia_Brisbane, // 0x4fedc9c0, Australia/Brisbane
  &kAtcZoneAmerica_Asuncion, // 0x50ec79a6, America/Asuncion
  &kAtcZoneAsia_Karachi, // 0x527f5245, Asia/Karachi
  &kAtcZonePacific_Gambier, // 0x53720c3a, Pacific/Gambier
  &kAtcZoneAmerica_Whitehorse, // 0x54e0e3e8, America/Whitehorse
  &kAtcZoneAmerica_Martinique, // 0x551e84c5, America/Martinique
  &kAtcZoneAmerica_Jamaica, // 0x565dad6c, America/Jamaica
  &kAtcZoneAsia_Hong_Kong, // 0x577f28ac, Asia/Hong_Kong
  &kAtcZonePacific_Marquesas, // 0x57ca7135, Pacific/Marquesas
  &kAtcZoneAmerica_Miquelon, // 0x59674330, America/Miquelon
  &kAtcZoneAmerica_Anchorage, // 0x5a79260e, America/Anchorage
  &kAtcZoneAsia_Jerusalem, // 0x5becd23a, Asia/Jerusalem
  &kAtcZoneEurope_Lisbon, // 0x5c00a70b, Europe/Lisbon
  &kAtcZoneAtlantic_Cape_Verde, // 0x5c5e1772, Atlantic/Cape_Verde
  &kAtcZoneEurope_London, // 0x5c6a84ae, Europe/London
  &kAtcZoneEurope_Madrid, // 0x5dbd1535, Europe/Madrid
  &kAtcZoneAmerica_Moncton, // 0x5e07fe24, America/Moncton
  &kAtcZonePacific_Bougainville, // 0x5e10f7a4, Pacific/Bougainville
  &kAtcZoneEurope_Moscow, // 0x5ec266fc, Europe/Moscow
  &kAtcZoneAmerica_Argentina_Jujuy, // 0x5f2f46c5, America/Argentina/Jujuy
  &kAtcZoneAmerica_Argentina_Salta, // 0x5fc73403, America/Argentina/Salta
  &kAtcZonePacific_Pago_Pago, // 0x603aebd0, Pacific/Pago_Pago
  &kAtcZoneAfrica_Sao_Tome, // 0x61b319d1, Africa/Sao_Tome
  &kAtcZoneAmerica_Costa_Rica, // 0x63ff66be, America/Costa_Rica
  &kAtcZoneAsia_Qostanay, // 0x654fe522, Asia/Qostanay
  &kAtcZoneAmerica_Indiana_Knox, // 0x6554adc9, America/Indiana/Knox
  &kAtcZoneEurope_Prague, // 0x65ee5d48, Europe/Prague
  &kAtcZoneAmerica_Puerto_Rico, // 0x6752ca31, America/Puerto_Rico
  &kAtcZoneAsia_Novokuznetsk, // 0x69264f93, Asia/Novokuznetsk
  &kAtcZoneAmerica_Tijuana, // 0x6aa1df72, America/Tijuana
  &kAtcZoneAsia_Makassar, // 0x6aa21c85, Asia/Makassar
  &kAtcZoneEurope_Helsinki, // 0x6ab2975b, Europe/Helsinki
  &kAtcZoneAmerica_Porto_Velho, // 0x6b1aac77, America/Porto_Velho
  &kAtcZoneEurope_Samara, // 0x6bc0b139, Europe/Samara
  &kAtcZoneAmerica_Edmonton, // 0x6cb9484a, America/Edmonton
  &kAtcZoneAmerica_Dawson_Creek, // 0x6cf24e5b, America/Dawson_Creek
  &kAtcZoneAmerica_Grand_Turk, // 0x6e216197, America/Grand_Turk
  &kAtcZoneEurope_Tirane, // 0x6ea95b47, Europe/Tirane
  &kAtcZoneAmerica_Araguaina, // 0x6f9a3aef, America/Araguaina
  &kAtcZoneAsia_Qyzylorda, // 0x71282e81, Asia/Qyzylorda
  &kAtcZoneAsia_Kolkata, // 0x72c06cd9, Asia/Kolkata
  &kAtcZoneEurope_Vienna, // 0x734cc2e5, Europe/Vienna
  &kAtcZoneAsia_Kamchatka, // 0x73baf9d7, Asia/Kamchatka
  &kAtcZoneAmerica_Santarem, // 0x740caec1, America/Santarem
  &kAtcZoneAmerica_Santiago, // 0x7410c9bc, America/Santiago
  &kAtcZoneEurope_Warsaw, // 0x75185c19, Europe/Warsaw
  &kAtcZoneAmerica_El_Salvador, // 0x752ad652, America/El_Salvador
  &kAtcZoneAfrica_Bissau, // 0x75564141, Africa/Bissau
  &kAtcZoneAmerica_Santo_Domingo, // 0x75a0d177, America/Santo_Domingo
  &kAtcZoneAfrica_Cairo, // 0x77f8e228, Africa/Cairo
  &kAtcZoneAfrica_Ceuta, // 0x77fb46ec, Africa/Ceuta
  &kAtcZoneAfrica_Lagos, // 0x789bb5d0, Africa/Lagos
  &kAtcZoneAfrica_Windhoek, // 0x789c9bd3, Africa/Windhoek
  &kAtcZoneAmerica_Toronto, // 0x792e851b, America/Toronto
  &kAtcZoneAfrica_Tunis, // 0x79378e6d, Africa/Tunis
  &kAtcZoneIndian_Mauritius, // 0x7b09c02a, Indian/Mauritius
  &kAtcZoneAtlantic_Stanley, // 0x7bb3e1c4, Atlantic/Stanley
  &kAtcZoneEurope_Zurich, // 0x7d8195b9, Europe/Zurich
  &kAtcZoneAsia_Kuching, // 0x801b003b, Asia/Kuching
  &kAtcZoneAtlantic_Madeira, // 0x81b5c037, Atlantic/Madeira
  &kAtcZonePacific_Kiritimati, // 0x8305073a, Pacific/Kiritimati
  &kAtcZoneAmerica_Metlakatla, // 0x84de2686, America/Metlakatla
  &kAtcZoneAsia_Yakutsk, // 0x87bb3a9e, Asia/Yakutsk
  &kAtcZoneAmerica_Chihuahua, // 0x8827d776, America/Chihuahua
  &kAtcZonePacific_Pitcairn, // 0x8837d8bd, Pacific/Pitcairn
  &kAtcZonePacific_Efate, // 0x8a2bce28, Pacific/Efate
  &kAtcZonePacific_Nauru, // 0x8acc41ae, Pacific/Nauru
  &kAtcZoneEST5EDT, // 0x8adc72a3, EST5EDT
  &kAtcZonePacific_Palau, // 0x8af04a36, Pacific/Palau
  &kAtcZoneAmerica_Winnipeg, // 0x8c7dafc7, America/Winnipeg
  &kAtcZoneAustralia_Eucla, // 0x8cf99e44, Australia/Eucla
  &kAtcZoneAmerica_Argentina_Catamarca, // 0x8d40986b, America/Argentina/Catamarca
  &kAtcZoneAustralia_Perth, // 0x8db8269d, Australia/Perth
  &kAtcZonePacific_Kwajalein, // 0x8e216759, Pacific/Kwajalein
  &kAtcZoneAmerica_Port_au_Prince, // 0x8e4a7bdc, America/Port-au-Prince
  &kAtcZoneAfrica_Maputo, // 0x8e6ca1f0, Africa/Maputo
  &kAtcZonePacific_Norfolk, // 0x8f4eb4be, Pacific/Norfolk
  &kAtcZoneAsia_Yerevan, // 0x9185c8cc, Asia/Yerevan
  &kAtcZoneAmerica_Detroit, // 0x925cfbc1, America/Detroit
  &kAtcZoneAsia_Choibalsan, // 0x928aa4a6, Asia/Choibalsan
  &kAtcZoneAntarctica_Macquarie, // 0x92f47626, Antarctica/Macquarie
  &kAtcZoneAmerica_Belize, // 0x93256c81, America/Belize
  &kAtcZoneAmerica_Bogota, // 0x93d7bc62, America/Bogota
  &kAtcZoneAsia_Pyongyang, // 0x93ed1c8e, Asia/Pyongyang
  &kAtcZoneAmerica_Indiana_Petersburg, // 0x94ac7acc, America/Indiana/Petersburg
  &kAtcZoneAmerica_Cancun, // 0x953331be, America/Cancun
  &kAtcZoneAmerica_Glace_Bay, // 0x9681f8dd, America/Glace_Bay
  &kAtcZoneAsia_Khandyga, // 0x9685a4d9, Asia/Khandyga
  &kAtcZoneAmerica_Cuiaba, // 0x969a52eb, America/Cuiaba
  &kAtcZoneAmerica_Dawson, // 0x978d8d12, America/Dawson
  &kAtcZoneAmerica_Denver, // 0x97d10b2a, America/Denver
  &kAtcZoneAmerica_Bahia, // 0x97d815fb, America/Bahia
  &kAtcZoneAmerica_Belem, // 0x97da580b, America/Belem
  &kAtcZoneAmerica_Boise, // 0x97dfc8d8, America/Boise
  &kAtcZoneEurope_Andorra, // 0x97f6764b, Europe/Andorra
  &kAtcZoneAmerica_Adak, // 0x97fe49d7, America/Adak
  &kAtcZoneAmerica_Lima, // 0x980468c9, America/Lima
  &kAtcZoneAmerica_Nome, // 0x98059b15, America/Nome
  &kAtcZoneAmerica_Nuuk, // 0x9805b5a9, America/Nuuk
  &kAtcZoneIndian_Maldives, // 0x9869681c, Indian/Maldives
  &kAtcZoneAmerica_Sitka, // 0x99104ce2, America/Sitka
  &kAtcZoneAmerica_Thule, // 0x9921dd68, America/Thule
  &kAtcZonePacific_Rarotonga, // 0x9981a3b0, Pacific/Rarotonga
  &kAtcZoneAsia_Kathmandu, // 0x9a96ce6f, Asia/Kathmandu
  &kAtcZoneAmerica_North_Dakota_Beulah, // 0x9b52b384, America/North_Dakota/Beulah
  &kAtcZoneAmerica_Rainy_River, // 0x9cd58a10, America/Rainy_River
  &kAtcZoneEurope_Budapest, // 0x9ce0197c, Europe/Budapest
  &kAtcZoneAsia_Baghdad, // 0x9ceffbed, Asia/Baghdad
  &kAtcZoneEtc_GMT_PLUS_1, // 0x9d13da14, Etc/GMT+1
  &kAtcZoneEtc_GMT_PLUS_2, // 0x9d13da15, Etc/GMT+2
  &kAtcZoneEtc_GMT_PLUS_3, // 0x9d13da16, Etc/GMT+3
  &kAtcZoneEtc_GMT_PLUS_4, // 0x9d13da17, Etc/GMT+4
  &kAtcZoneEtc_GMT_PLUS_5, // 0x9d13da18, Etc/GMT+5
  &kAtcZoneEtc_GMT_PLUS_6, // 0x9d13da19, Etc/GMT+6
  &kAtcZoneEtc_GMT_PLUS_7, // 0x9d13da1a, Etc/GMT+7
  &kAtcZoneEtc_GMT_PLUS_8, // 0x9d13da1b, Etc/GMT+8
  &kAtcZoneEtc_GMT_PLUS_9, // 0x9d13da1c, Etc/GMT+9
  &kAtcZoneEtc_GMT_1, // 0x9d13da56, Etc/GMT-1
  &kAtcZoneEtc_GMT_2, // 0x9d13da57, Etc/GMT-2
  &kAtcZoneEtc_GMT_3, // 0x9d13da58, Etc/GMT-3
  &kAtcZoneEtc_GMT_4, // 0x9d13da59, Etc/GMT-4
  &kAtcZoneEtc_GMT_5, // 0x9d13da5a, Etc/GMT-5
  &kAtcZoneEtc_GMT_6, // 0x9d13da5b, Etc/GMT-6
  &kAtcZoneEtc_GMT_7, // 0x9d13da5c, Etc/GMT-7
  &kAtcZoneEtc_GMT_8, // 0x9d13da5d, Etc/GMT-8
  &kAtcZoneEtc_GMT_9, // 0x9d13da5e, Etc/GMT-9
  &kAtcZoneAmerica_Nipigon, // 0x9d2a8b1a, America/Nipigon
  &kAtcZoneAmerica_Rio_Branco, // 0x9d352764, America/Rio_Branco
  &kAtcZoneAsia_Bangkok, // 0x9d6e3aaf, Asia/Bangkok
  &kAtcZoneAfrica_El_Aaiun, // 0x9d6fb118, Africa/El_Aaiun
  &kAtcZoneAmerica_North_Dakota_Center, // 0x9da42814, America/North_Dakota/Center
  &kAtcZoneAsia_Barnaul, // 0x9dba4997, Asia/Barnaul
  &kAtcZoneAfrica_Tripoli, // 0x9dfebd3d, Africa/Tripoli
  &kAtcZoneEurope_Istanbul, // 0x9e09d6e6, Europe/Istanbul
  &kAtcZoneAfrica_Ndjamena, // 0x9fe09898, Africa/Ndjamena
  &kAtcZoneAmerica_Guyana, // 0x9ff7bd0b, America/Guyana
  &kAtcZoneAmerica_Havana, // 0xa0e15675, America/Havana
  &kAtcZoneAsia_Novosibirsk, // 0xa2a435cb, Asia/Novosibirsk
  &kAtcZoneEurope_Kyiv, // 0xa2c1e347, Europe/Kyiv
  &kAtcZoneEurope_Riga, // 0xa2c57587, Europe/Riga
  &kAtcZoneEurope_Rome, // 0xa2c58fd7, Europe/Rome
  &kAtcZoneAmerica_Inuvik, // 0xa42189fc, America/Inuvik
  &kAtcZoneAmerica_Argentina_La_Rioja, // 0xa46b7eef, America/Argentina/La_Rioja
  &kAtcZoneAsia_Almaty, // 0xa61f41fa, Asia/Almaty
  &kAtcZoneAsia_Anadyr, // 0xa63cebd1, Asia/Anadyr
  &kAtcZoneAsia_Aqtobe, // 0xa67dcc4e, Asia/Aqtobe
  &kAtcZoneAsia_Atyrau, // 0xa6b6e068, Asia/Atyrau
  &kAtcZoneAmerica_Juneau, // 0xa6f13e2e, America/Juneau
  &kAtcZoneAustralia_Lord_Howe, // 0xa748b67d, Australia/Lord_Howe
  &kAtcZonePacific_Port_Moresby, // 0xa7ba7f68, Pacific/Port_Moresby
  &kAtcZoneAsia_Beirut, // 0xa7f3d5fd, Asia/Beirut
  &kAtcZoneAfrica_Nairobi, // 0xa87ab57e, Africa/Nairobi
  &kAtcZonePacific_Galapagos, // 0xa952f752, Pacific/Galapagos
  &kAtcZoneAmerica_Argentina_Mendoza, // 0xa9f72d5c, America/Argentina/Mendoza
  &kAtcZoneAmerica_La_Paz, // 0xaa29125d, America/La_Paz
  &kAtcZoneAmerica_Noronha, // 0xab5116fb, America/Noronha
  &kAtcZoneAmerica_Maceio, // 0xac80c6d4, America/Maceio
  &kAtcZoneAmerica_Manaus, // 0xac86bf8b, America/Manaus
  &kAtcZoneAmerica_Merida, // 0xacd172d8, America/Merida
  &kAtcZoneEurope_Chisinau, // 0xad58aa18, Europe/Chisinau
  &kAtcZoneAustralia_Broken_Hill, // 0xb06eada3, Australia/Broken_Hill
  &kAtcZoneAsia_Bishkek, // 0xb0728553, Asia/Bishkek
  &kAtcZoneAmerica_Paramaribo, // 0xb319e4c4, America/Paramaribo
  &kAtcZoneAmerica_Panama, // 0xb3863854, America/Panama
  &kAtcZoneAsia_Hebron, // 0xb5eef250, Asia/Hebron
  &kAtcZoneAmerica_Goose_Bay, // 0xb649541e, America/Goose_Bay
  &kAtcZoneAmerica_Los_Angeles, // 0xb7f7e8f2, America/Los_Angeles
  &kAtcZoneAmerica_Recife, // 0xb8730494, America/Recife
  &kAtcZoneAmerica_Regina, // 0xb875371c, America/Regina
  &kAtcZoneAsia_Ashgabat, // 0xba87598d, Asia/Ashgabat
  &kAtcZoneAmerica_Halifax, // 0xbc5b7183, America/Halifax
  &kAtcZoneAsia_Srednekolymsk, // 0xbf8e337d, Asia/Srednekolymsk
  &kAtcZoneAmerica_Argentina_Cordoba, // 0xbfccc308, America/Argentina/Cordoba
  &kAtcZoneAmerica_Tegucigalpa, // 0xbfd6fd4c, America/Tegucigalpa
  &kAtcZoneAsia_Manila, // 0xc156c944, Asia/Manila
  &kAtcZoneAfrica_Abidjan, // 0xc21305a3, Africa/Abidjan
  &kAtcZoneAmerica_Punta_Arenas, // 0xc2c3bce7, America/Punta_Arenas
  &kAtcZoneAfrica_Casablanca, // 0xc59f1b33, Africa/Casablanca
  &kAtcZoneAmerica_Argentina_Rio_Gallegos, // 0xc5b0f565, America/Argentina/Rio_Gallegos
  &kAtcZoneAsia_Jayapura, // 0xc6833c2f, Asia/Jayapura
  &kAtcZoneAmerica_Resolute, // 0xc7093459, America/Resolute
  &kAtcZoneAmerica_Rankin_Inlet, // 0xc8de4984, America/Rankin_Inlet
  &kAtcZoneAmerica_Barbados, // 0xcbbc3b04, America/Barbados
  &kAtcZoneAsia_Riyadh, // 0xcd973d93, Asia/Riyadh
  &kAtcZonePacific_Easter, // 0xcf54f7e7, Pacific/Easter
  &kAtcZoneAsia_Singapore, // 0xcf8581fa, Asia/Singapore
  &kAtcZoneAsia_Krasnoyarsk, // 0xd0376c6a, Asia/Krasnoyarsk
  &kAtcZoneAmerica_Mexico_City, // 0xd0d93f43, America/Mexico_City
  &kAtcZoneAsia_Taipei, // 0xd1a844ae, Asia/Taipei
  &kAtcZoneAsia_Tehran, // 0xd1f02254, Asia/Tehran
  &kAtcZoneEurope_Kaliningrad, // 0xd33b2f28, Europe/Kaliningrad
  &kAtcZoneAmerica_Argentina_Buenos_Aires, // 0xd43b4c0d, America/Argentina/Buenos_Aires
  &kAtcZoneAfrica_Juba, // 0xd51b395c, Africa/Juba
  &kAtcZoneAsia_Urumqi, // 0xd5379735, Asia/Urumqi
  &kAtcZoneAmerica_Cambridge_Bay, // 0xd5a44aff, America/Cambridge_Bay
  &kAtcZoneAfrica_Johannesburg, // 0xd5d157a0, Africa/Johannesburg
  &kAtcZoneEtc_GMT, // 0xd8e2de58, Etc/GMT
  &kAtcZoneEtc_UTC, // 0xd8e31abc, Etc/UTC
  &kAtcZoneAmerica_Yakutat, // 0xd8ee31e9, America/Yakutat
  &kAtcZoneAfrica_Algiers, // 0xd94515c1, Africa/Algiers
  &kAtcZonePST8PDT, // 0xd99ee2dc, PST8PDT
  &kAtcZoneEurope_Simferopol, // 0xda9eb724, Europe/Simferopol
  &kAtcZoneAmerica_Matamoros, // 0xdd1b0259, America/Matamoros
  &kAtcZonePacific_Kanton, // 0xdd512f0e, Pacific/Kanton
  &kAtcZoneAsia_Yangon, // 0xdd54a8be, Asia/Yangon
  &kAtcZoneEurope_Vilnius, // 0xdd63b8ce, Europe/Vilnius
  &kAtcZonePacific_Kosrae, // 0xde5139a8, Pacific/Kosrae
  &kAtcZoneAmerica_Kentucky_Monticello, // 0xde71c439, America/Kentucky/Monticello
  &kAtcZoneEurope_Brussels, // 0xdee07337, Europe/Brussels
  &kAtcZoneAmerica_Swift_Current, // 0xdef98e55, America/Swift_Current
  &kAtcZoneAsia_Irkutsk, // 0xdfbf213f, Asia/Irkutsk
  &kAtcZoneEurope_Ulyanovsk, // 0xe03783d0, Europe/Ulyanovsk
  &kAtcZoneAustralia_Lindeman, // 0xe05029e2, Australia/Lindeman
  &kAtcZoneEurope_Belgrade, // 0xe0532b3a, Europe/Belgrade
  &kAtcZoneAmerica_Menominee, // 0xe0e9c583, America/Menominee
  &kAtcZoneAtlantic_Faroe, // 0xe110a971, Atlantic/Faroe
  &kAtcZoneAntarctica_Casey, // 0xe2022583, Antarctica/Casey
  &kAtcZoneAntarctica_Davis, // 0xe2144b45, Antarctica/Davis
  &kAtcZoneEurope_Astrakhan, // 0xe22256e1, Europe/Astrakhan
  &kAtcZoneAntarctica_Troll, // 0xe33f085b, Antarctica/Troll
  &kAtcZoneEurope_Saratov, // 0xe4315da4, Europe/Saratov
  &kAtcZonePacific_Noumea, // 0xe551b788, Pacific/Noumea
  &kAtcZonePacific_Honolulu, // 0xe6e70af9, Pacific/Honolulu
  &kAtcZoneAmerica_Argentina_Tucuman, // 0xe96399eb, America/Argentina/Tucuman
  &kAtcZoneAsia_Magadan, // 0xebacc19b, Asia/Magadan
  &kAtcZoneAmerica_Ojinaga, // 0xebfde83f, America/Ojinaga
  &kAtcZoneCST6CDT, // 0xf0e87d00, CST6CDT
  &kAtcZonePacific_Tahiti, // 0xf24c2446, Pacific/Tahiti
  &kAtcZonePacific_Tarawa, // 0xf2517e63, Pacific/Tarawa
  &kAtcZoneMST7MDT, // 0xf2af9375, MST7MDT
  &kAtcZoneAsia_Tashkent, // 0xf3924254, Asia/Tashkent
  &kAtcZoneAsia_Sakhalin, // 0xf4a1c9bd, Asia/Sakhalin
  &kAtcZonePacific_Guadalcanal, // 0xf4dd25f0, Pacific/Guadalcanal
  &kAtcZoneAmerica_Danmarkshavn, // 0xf554d204, America/Danmarkshavn
  &kAtcZoneAsia_Shanghai, // 0xf895a7f5, Asia/Shanghai
  &kAtcZoneEurope_Gibraltar, // 0xf8e325fc, Europe/Gibraltar
  &kAtcZoneAtlantic_Azores, // 0xf93ed918, Atlantic/Azores
  &kAtcZoneAmerica_Thunder_Bay, // 0xf962e71b, America/Thunder_Bay
  &kAtcZoneAmerica_Eirunepe, // 0xf9b29683, America/Eirunepe
  &kAtcZoneAmerica_Montevideo, // 0xfa214780, America/Montevideo
  &kAtcZoneEurope_Kirov, // 0xfaf5abef, Europe/Kirov
  &kAtcZoneEurope_Malta, // 0xfb1560f3, Europe/Malta
  &kAtcZoneEurope_Minsk, // 0xfb19cc66, Europe/Minsk
  &kAtcZoneEurope_Bucharest, // 0xfb349ec5, Europe/Bucharest
  &kAtcZoneAfrica_Khartoum, // 0xfb3d4205, Africa/Khartoum
  &kAtcZoneEurope_Paris, // 0xfb4bc2a3, Europe/Paris
  &kAtcZoneAsia_Yekaterinburg, // 0xfb544c6e, Asia/Yekaterinburg
  &kAtcZoneEurope_Sofia, // 0xfb898656, Europe/Sofia
  &kAtcZoneAtlantic_Canary, // 0xfc23f2c2, Atlantic/Canary
  &kAtcZoneAmerica_Campo_Grande, // 0xfec3e7a6, America/Campo_Grande

};

//---------------------------------------------------------------------------
// Zone and Link (fat) Info registry. Sorted by zoneId. Links act like Zones.
//---------------------------------------------------------------------------
const AtcZoneInfo * const kAtcZoneAndLinkRegistry[595]  = {
  &kAtcZoneGB, // 0x005973ae, GB -> Europe/London
  &kAtcZoneNZ, // 0x005974ad, NZ -> Pacific/Auckland
  &kAtcZoneAsia_Kuala_Lumpur, // 0x014763c4, Asia/Kuala_Lumpur -> Asia/Singapore
  &kAtcZoneAfrica_Libreville, // 0x01d96de4, Africa/Libreville -> Africa/Lagos
  &kAtcZoneIndian_Cocos, // 0x021e86de, Indian/Cocos -> Asia/Yangon
  &kAtcZoneAustralia_Victoria, // 0x0260d5db, Australia/Victoria -> Australia/Melbourne
  &kAtcZoneAtlantic_Faeroe, // 0x031ec516, Atlantic/Faeroe -> Atlantic/Faroe
  &kAtcZoneAmerica_St_Johns, // 0x04b14e6e, America/St_Johns
  &kAtcZoneAmerica_St_Kitts, // 0x04c0507b, America/St_Kitts -> America/Puerto_Rico
  &kAtcZoneAfrica_Ouagadougou, // 0x04d7219a, Africa/Ouagadougou -> Africa/Abidjan
  &kAtcZoneAmerica_St_Lucia, // 0x04d8b3ba, America/St_Lucia -> America/Puerto_Rico
  &kAtcZoneAmerica_North_Dakota_New_Salem, // 0x04f9958e, America/North_Dakota/New_Salem
  &kAtcZoneAsia_Jakarta, // 0x0506ab50, Asia/Jakarta
  &kAtcZoneAfrica_Bujumbura, // 0x05232a47, Africa/Bujumbura -> Africa/Maputo
  &kAtcZoneAmerica_Mazatlan, // 0x0532189e, America/Mazatlan
  &kAtcZoneAmerica_St_Barthelemy, // 0x054e6a79, America/St_Barthelemy -> America/Puerto_Rico
  &kAtcZoneAfrica_Addis_Ababa, // 0x05ae1e65, Africa/Addis_Ababa -> Africa/Nairobi
  &kAtcZonePacific_Fakaofo, // 0x06532bba, Pacific/Fakaofo
  &kAtcZoneAmerica_Hermosillo, // 0x065d21c4, America/Hermosillo
  &kAtcZoneMexico_BajaSur, // 0x08ee3641, Mexico/BajaSur -> America/Mazatlan
  &kAtcZoneAsia_Tbilisi, // 0x0903e442, Asia/Tbilisi
  &kAtcZoneAmerica_Indiana_Tell_City, // 0x09263612, America/Indiana/Tell_City
  &kAtcZoneUS_Hawaii, // 0x09c8de2f, US/Hawaii -> Pacific/Honolulu
  &kAtcZoneAmerica_Boa_Vista, // 0x0a7b7efe, America/Boa_Vista
  &kAtcZoneAsia_Colombo, // 0x0af0e91d, Asia/Colombo
  &kAtcZoneCET, // 0x0b87d921, CET
  &kAtcZoneEET, // 0x0b87e1a3, EET
  &kAtcZoneEST, // 0x0b87e371, EST
  &kAtcZoneGMT, // 0x0b87eb2d, GMT -> Etc/GMT
  &kAtcZoneHST, // 0x0b87f034, HST
  &kAtcZoneMET, // 0x0b8803ab, MET
  &kAtcZoneMST, // 0x0b880579, MST
  &kAtcZonePRC, // 0x0b88120a, PRC -> Asia/Shanghai
  &kAtcZoneROC, // 0x0b881a29, ROC -> Asia/Taipei
  &kAtcZoneROK, // 0x0b881a31, ROK -> Asia/Seoul
  &kAtcZoneUCT, // 0x0b882571, UCT -> Etc/UTC
  &kAtcZoneUTC, // 0x0b882791, UTC -> Etc/UTC
  &kAtcZoneWET, // 0x0b882e35, WET
  &kAtcZoneAmerica_Guatemala, // 0x0c8259f7, America/Guatemala
  &kAtcZoneEurope_Mariehamn, // 0x0caa6496, Europe/Mariehamn -> Europe/Helsinki
  &kAtcZoneAfrica_Monrovia, // 0x0ce90385, Africa/Monrovia
  &kAtcZoneEgypt, // 0x0d1a278e, Egypt -> Africa/Cairo
  &kAtcZoneGMT_PLUS_0, // 0x0d2f7028, GMT+0 -> Etc/GMT
  &kAtcZoneGMT_0, // 0x0d2f706a, GMT-0 -> Etc/GMT
  &kAtcZoneJapan, // 0x0d712f8f, Japan -> Asia/Tokyo
  &kAtcZoneLibya, // 0x0d998b16, Libya -> Africa/Tripoli
  &kAtcZoneKwajalein, // 0x0e57afbb, Kwajalein -> Pacific/Kwajalein
  &kAtcZoneAntarctica_Rothera, // 0x0e86d203, Antarctica/Rothera
  &kAtcZoneAmerica_Yellowknife, // 0x0f76c76f, America/Yellowknife
  &kAtcZoneAustralia_Melbourne, // 0x0fe559a3, Australia/Melbourne
  &kAtcZoneAmerica_Sao_Paulo, // 0x1063bfc9, America/Sao_Paulo
  &kAtcZoneEurope_Amsterdam, // 0x109395c2, Europe/Amsterdam -> Europe/Brussels
  &kAtcZoneAmerica_Indiana_Vevay, // 0x10aca054, America/Indiana/Vevay
  &kAtcZoneAmerica_Scoresbysund, // 0x123f8d2a, America/Scoresbysund
  &kAtcZoneAsia_Samarkand, // 0x13ae5104, Asia/Samarkand
  &kAtcZoneAsia_Amman, // 0x148d21bc, Asia/Amman
  &kAtcZoneAsia_Aqtau, // 0x148f710e, Asia/Aqtau
  &kAtcZoneAsia_Chita, // 0x14ae863b, Asia/Chita
  &kAtcZoneAsia_Dacca, // 0x14bcac5e, Asia/Dacca -> Asia/Dhaka
  &kAtcZoneAsia_Dhaka, // 0x14c07b8b, Asia/Dhaka
  &kAtcZoneAsia_Dubai, // 0x14c79f77, Asia/Dubai
  &kAtcZoneAmerica_Bahia_Banderas, // 0x14f6329a, America/Bahia_Banderas
  &kAtcZoneAsia_Kabul, // 0x153b5601, Asia/Kabul
  &kAtcZoneAsia_Ashkhabad, // 0x15454f09, Asia/Ashkhabad -> Asia/Ashgabat
  &kAtcZoneAsia_Macao, // 0x155f88b3, Asia/Macao -> Asia/Macau
  &kAtcZoneAsia_Macau, // 0x155f88b9, Asia/Macau
  &kAtcZoneAsia_Qatar, // 0x15a8330b, Asia/Qatar
  &kAtcZoneAsia_Seoul, // 0x15ce82da, Asia/Seoul
  &kAtcZoneAsia_Tokyo, // 0x15e606a8, Asia/Tokyo
  &kAtcZoneAsia_Tomsk, // 0x15e60e60, Asia/Tomsk
  &kAtcZoneAsia_Tel_Aviv, // 0x166d7c2c, Asia/Tel_Aviv -> Asia/Jerusalem
  &kAtcZoneAsia_Thimphu, // 0x170380d1, Asia/Thimphu
  &kAtcZoneAmerica_Guayaquil, // 0x17e64958, America/Guayaquil
  &kAtcZoneAmerica_Montserrat, // 0x199b0a35, America/Montserrat -> America/Puerto_Rico
  &kAtcZoneAmerica_Kentucky_Louisville, // 0x1a21024b, America/Kentucky/Louisville
  &kAtcZoneAsia_Pontianak, // 0x1a76c057, Asia/Pontianak
  &kAtcZoneEurope_Podgorica, // 0x1c1a499c, Europe/Podgorica -> Europe/Belgrade
  &kAtcZoneAtlantic_Reykjavik, // 0x1c2b4f74, Atlantic/Reykjavik -> Africa/Abidjan
  &kAtcZoneAmerica_New_York, // 0x1e2a7654, America/New_York
  &kAtcZoneEurope_Luxembourg, // 0x1f8bc6ce, Europe/Luxembourg -> Europe/Brussels
  &kAtcZoneAsia_Aden, // 0x1fa7084a, Asia/Aden -> Asia/Riyadh
  &kAtcZoneAsia_Baku, // 0x1fa788b5, Asia/Baku
  &kAtcZoneAsia_Dili, // 0x1fa8c394, Asia/Dili
  &kAtcZoneAsia_Gaza, // 0x1faa4875, Asia/Gaza
  &kAtcZoneAsia_Hovd, // 0x1fab0fe3, Asia/Hovd
  &kAtcZoneAsia_Omsk, // 0x1faeddac, Asia/Omsk
  &kAtcZoneAsia_Oral, // 0x1faef0a0, Asia/Oral
  &kAtcZoneAmerica_Montreal, // 0x203a1ea8, America/Montreal -> America/Toronto
  &kAtcZoneAsia_Ho_Chi_Minh, // 0x20f2d127, Asia/Ho_Chi_Minh
  &kAtcZoneAsia_Damascus, // 0x20fbb063, Asia/Damascus
  &kAtcZoneAmerica_Argentina_ComodRivadavia, // 0x22758877, America/Argentina/ComodRivadavia -> America/Argentina/Catamarca
  &kAtcZonePacific_Apia, // 0x23359b5e, Pacific/Apia
  &kAtcZonePacific_Fiji, // 0x23383ba5, Pacific/Fiji
  &kAtcZonePacific_Guam, // 0x2338f9ed, Pacific/Guam
  &kAtcZonePacific_Niue, // 0x233ca014, Pacific/Niue
  &kAtcZonePacific_Truk, // 0x234010a9, Pacific/Truk -> Pacific/Port_Moresby
  &kAtcZonePacific_Wake, // 0x23416c2b, Pacific/Wake -> Pacific/Tarawa
  &kAtcZoneAustralia_Adelaide, // 0x2428e8a3, Australia/Adelaide
  &kAtcZonePacific_Auckland, // 0x25062f86, Pacific/Auckland
  &kAtcZonePacific_Tongatapu, // 0x262ca836, Pacific/Tongatapu
  &kAtcZoneAmerica_Monterrey, // 0x269a1deb, America/Monterrey
  &kAtcZoneEtc_Greenwich, // 0x26daa98c, Etc/Greenwich -> Etc/GMT
  &kAtcZoneAustralia_Currie, // 0x278b6a24, Australia/Currie -> Australia/Hobart
  &kAtcZoneAustralia_Darwin, // 0x2876bdff, Australia/Darwin
  &kAtcZonePacific_Pohnpei, // 0x28929f96, Pacific/Pohnpei -> Pacific/Guadalcanal
  &kAtcZoneAsia_Famagusta, // 0x289b4f8b, Asia/Famagusta
  &kAtcZoneAmerica_Indiana_Vincennes, // 0x28a0b212, America/Indiana/Vincennes
  &kAtcZoneAmerica_Indiana_Indianapolis, // 0x28a669a4, America/Indiana/Indianapolis
  &kAtcZoneAsia_Vladivostok, // 0x29de34a8, Asia/Vladivostok
  &kAtcZoneAustralia_Canberra, // 0x2a09ae58, Australia/Canberra -> Australia/Sydney
  &kAtcZoneAmerica_Fortaleza, // 0x2ad018ee, America/Fortaleza
  &kAtcZoneAmerica_Vancouver, // 0x2c6f6b1f, America/Vancouver
  &kAtcZoneAmerica_Pangnirtung, // 0x2d999193, America/Pangnirtung
  &kAtcZoneAmerica_Iqaluit, // 0x2de310bf, America/Iqaluit
  &kAtcZoneJamaica, // 0x2e44fdab, Jamaica -> America/Jamaica
  &kAtcZonePacific_Chatham, // 0x2f0de999, Pacific/Chatham
  &kAtcZoneEtc_Universal, // 0x2f8cb9a9, Etc/Universal -> Etc/UTC
  &kAtcZoneAmerica_Indiana_Marengo, // 0x2feeee72, America/Indiana/Marengo
  &kAtcZoneEurope_Tallinn, // 0x30c4e096, Europe/Tallinn
  &kAtcZoneAfrica_Djibouti, // 0x30ea01d4, Africa/Djibouti -> Africa/Nairobi
  &kAtcZoneAsia_Ulaanbaatar, // 0x30f0cc4e, Asia/Ulaanbaatar
  &kAtcZoneAfrica_Gaborone, // 0x317c0aa7, Africa/Gaborone -> Africa/Maputo
  &kAtcZoneAmerica_Argentina_Ushuaia, // 0x320dcdde, America/Argentina/Ushuaia
  &kAtcZoneAsia_Calcutta, // 0x328a44c3, Asia/Calcutta -> Asia/Kolkata
  &kAtcZoneAustralia_Hobart, // 0x32bf951a, Australia/Hobart
  &kAtcZoneAsia_Dushanbe, // 0x32fc5c3c, Asia/Dushanbe
  &kAtcZoneAtlantic_South_Georgia, // 0x33013174, Atlantic/South_Georgia
  &kAtcZoneAmerica_Phoenix, // 0x34b5af01, America/Phoenix
  &kAtcZoneAsia_Istanbul, // 0x382e7894, Asia/Istanbul -> Europe/Istanbul
  &kAtcZoneAsia_Ulan_Bator, // 0x394db4d9, Asia/Ulan_Bator -> Asia/Ulaanbaatar
  &kAtcZoneAntarctica_Mawson, // 0x399cd863, Antarctica/Mawson
  &kAtcZoneAfrica_Brazzaville, // 0x39cda760, Africa/Brazzaville -> Africa/Lagos
  &kAtcZoneAmerica_Caracas, // 0x3be064f4, America/Caracas
  &kAtcZoneAmerica_Cayenne, // 0x3c617269, America/Cayenne
  &kAtcZoneAfrica_Porto_Novo, // 0x3d1bf95d, Africa/Porto-Novo -> Africa/Lagos
  &kAtcZoneAtlantic_Bermuda, // 0x3d4bb1c4, Atlantic/Bermuda
  &kAtcZoneAmerica_Managua, // 0x3d5e7600, America/Managua
  &kAtcZoneAmerica_Marigot, // 0x3dab3a59, America/Marigot -> America/Puerto_Rico
  &kAtcZoneEurope_Guernsey, // 0x3db12c16, Europe/Guernsey -> Europe/London
  &kAtcZoneAfrica_Nouakchott, // 0x3dc49dba, Africa/Nouakchott -> Africa/Abidjan
  &kAtcZoneAmerica_Louisville, // 0x3dcb47ee, America/Louisville -> America/Kentucky/Louisville
  &kAtcZoneAmerica_Argentina_San_Juan, // 0x3e1009bd, America/Argentina/San_Juan
  &kAtcZoneAmerica_Argentina_San_Luis, // 0x3e11238c, America/Argentina/San_Luis
  &kAtcZoneEurope_Volgograd, // 0x3ed0f389, Europe/Volgograd
  &kAtcZoneAmerica_Fort_Nelson, // 0x3f437e0f, America/Fort_Nelson
  &kAtcZoneEtc_GMT_PLUS_10, // 0x3f8f1cc4, Etc/GMT+10
  &kAtcZoneEtc_GMT_PLUS_11, // 0x3f8f1cc5, Etc/GMT+11
  &kAtcZoneEtc_GMT_PLUS_12, // 0x3f8f1cc6, Etc/GMT+12
  &kAtcZoneEtc_GMT_10, // 0x3f8f2546, Etc/GMT-10
  &kAtcZoneEtc_GMT_11, // 0x3f8f2547, Etc/GMT-11
  &kAtcZoneEtc_GMT_12, // 0x3f8f2548, Etc/GMT-12
  &kAtcZoneEtc_GMT_13, // 0x3f8f2549, Etc/GMT-13
  &kAtcZoneEtc_GMT_14, // 0x3f8f254a, Etc/GMT-14
  &kAtcZoneAntarctica_Palmer, // 0x40962f4f, Antarctica/Palmer
  &kAtcZoneCanada_Pacific, // 0x40fa3c7b, Canada/Pacific -> America/Vancouver
  &kAtcZoneEurope_Athens, // 0x4318fa27, Europe/Athens
  &kAtcZoneIndian_Kerguelen, // 0x4351b389, Indian/Kerguelen -> Indian/Maldives
  &kAtcZoneAmerica_Indiana_Winamac, // 0x4413fa69, America/Indiana/Winamac
  &kAtcZoneEurope_Berlin, // 0x44644c20, Europe/Berlin
  &kAtcZoneAtlantic_St_Helena, // 0x451fc5f7, Atlantic/St_Helena -> Africa/Abidjan
  &kAtcZoneIndian_Chagos, // 0x456f7c3c, Indian/Chagos
  &kAtcZoneIndian_Mahe, // 0x45e725e2, Indian/Mahe -> Asia/Dubai
  &kAtcZoneIndian_Comoro, // 0x45f4deb6, Indian/Comoro -> Africa/Nairobi
  &kAtcZoneAmerica_Mendoza, // 0x46b4e054, America/Mendoza -> America/Argentina/Mendoza
  &kAtcZoneAsia_Ust_Nera, // 0x4785f921, Asia/Ust-Nera
  &kAtcZoneEurope_Dublin, // 0x4a275f62, Europe/Dublin
  &kAtcZoneAsia_Nicosia, // 0x4b0fcf78, Asia/Nicosia
  &kAtcZoneAmerica_Chicago, // 0x4b92b5d4, America/Chicago
  &kAtcZoneAustralia_Sydney, // 0x4d1e9776, Australia/Sydney
  &kAtcZoneNZ_CHAT, // 0x4d42afda, NZ-CHAT -> Pacific/Chatham
  &kAtcZoneUS_Arizona, // 0x4ec52670, US/Arizona -> America/Phoenix
  &kAtcZoneAntarctica_Vostok, // 0x4f966fd4, Antarctica/Vostok -> Asia/Urumqi
  &kAtcZoneUS_Aleutian, // 0x4fe013ef, US/Aleutian -> America/Adak
  &kAtcZoneAustralia_Brisbane, // 0x4fedc9c0, Australia/Brisbane
  &kAtcZoneAmerica_Catamarca, // 0x5036e963, America/Catamarca -> America/Argentina/Catamarca
  &kAtcZoneAmerica_Asuncion, // 0x50ec79a6, America/Asuncion
  &kAtcZoneAsia_Karachi, // 0x527f5245, Asia/Karachi
  &kAtcZoneAsia_Kashgar, // 0x52955193, Asia/Kashgar -> Asia/Urumqi
  &kAtcZoneCanada_Atlantic, // 0x536b119c, Canada/Atlantic -> America/Halifax
  &kAtcZonePacific_Gambier, // 0x53720c3a, Pacific/Gambier
  &kAtcZoneAmerica_Whitehorse, // 0x54e0e3e8, America/Whitehorse
  &kAtcZoneAmerica_Martinique, // 0x551e84c5, America/Martinique
  &kAtcZoneAmerica_Jamaica, // 0x565dad6c, America/Jamaica
  &kAtcZoneUS_Samoa, // 0x566821cd, US/Samoa -> Pacific/Pago_Pago
  &kAtcZoneHongkong, // 0x56d36560, Hongkong -> Asia/Hong_Kong
  &kAtcZoneEurope_Jersey, // 0x570dae76, Europe/Jersey -> Europe/London
  &kAtcZoneAsia_Hong_Kong, // 0x577f28ac, Asia/Hong_Kong
  &kAtcZonePacific_Marquesas, // 0x57ca7135, Pacific/Marquesas
  &kAtcZoneAmerica_Miquelon, // 0x59674330, America/Miquelon
  &kAtcZoneAntarctica_DumontDUrville, // 0x5a3c656c, Antarctica/DumontDUrville -> Pacific/Port_Moresby
  &kAtcZoneAtlantic_Jan_Mayen, // 0x5a7535b6, Atlantic/Jan_Mayen -> Europe/Berlin
  &kAtcZoneAmerica_Anchorage, // 0x5a79260e, America/Anchorage
  &kAtcZoneUS_Eastern, // 0x5bb7e78e, US/Eastern -> America/New_York
  &kAtcZoneAsia_Jerusalem, // 0x5becd23a, Asia/Jerusalem
  &kAtcZoneEurope_Stockholm, // 0x5bf6fbb8, Europe/Stockholm -> Europe/Berlin
  &kAtcZoneEurope_Lisbon, // 0x5c00a70b, Europe/Lisbon
  &kAtcZoneAtlantic_Cape_Verde, // 0x5c5e1772, Atlantic/Cape_Verde
  &kAtcZoneEurope_London, // 0x5c6a84ae, Europe/London
  &kAtcZoneAmerica_Cordoba, // 0x5c8a7600, America/Cordoba -> America/Argentina/Cordoba
  &kAtcZoneAsia_Ujung_Pandang, // 0x5d001eb3, Asia/Ujung_Pandang -> Asia/Makassar
  &kAtcZoneAfrica_Mbabane, // 0x5d3bdd40, Africa/Mbabane -> Africa/Johannesburg
  &kAtcZoneEurope_Madrid, // 0x5dbd1535, Europe/Madrid
  &kAtcZoneAmerica_Moncton, // 0x5e07fe24, America/Moncton
  &kAtcZonePacific_Bougainville, // 0x5e10f7a4, Pacific/Bougainville
  &kAtcZoneEurope_Monaco, // 0x5ebf9f01, Europe/Monaco -> Europe/Paris
  &kAtcZoneEurope_Moscow, // 0x5ec266fc, Europe/Moscow
  &kAtcZoneAmerica_Argentina_Jujuy, // 0x5f2f46c5, America/Argentina/Jujuy
  &kAtcZoneAmerica_Argentina_Salta, // 0x5fc73403, America/Argentina/Salta
  &kAtcZonePacific_Pago_Pago, // 0x603aebd0, Pacific/Pago_Pago
  &kAtcZonePacific_Enderbury, // 0x61599a93, Pacific/Enderbury -> Pacific/Kanton
  &kAtcZoneAfrica_Sao_Tome, // 0x61b319d1, Africa/Sao_Tome
  &kAtcZoneCanada_Central, // 0x626710f5, Canada/Central -> America/Winnipeg
  &kAtcZoneAmerica_Creston, // 0x62a70204, America/Creston -> America/Phoenix
  &kAtcZoneAmerica_Costa_Rica, // 0x63ff66be, America/Costa_Rica
  &kAtcZoneAsia_Qostanay, // 0x654fe522, Asia/Qostanay
  &kAtcZoneAmerica_Indiana_Knox, // 0x6554adc9, America/Indiana/Knox
  &kAtcZoneEurope_Prague, // 0x65ee5d48, Europe/Prague
  &kAtcZoneBrazil_Acre, // 0x66934f93, Brazil/Acre -> America/Rio_Branco
  &kAtcZoneBrazil_East, // 0x669578c5, Brazil/East -> America/Sao_Paulo
  &kAtcZoneAfrica_Kinshasa, // 0x6695d70c, Africa/Kinshasa -> Africa/Lagos
  &kAtcZoneBrazil_West, // 0x669f689b, Brazil/West -> America/Manaus
  &kAtcZoneAfrica_Mogadishu, // 0x66bc159b, Africa/Mogadishu -> Africa/Nairobi
  &kAtcZoneAmerica_Puerto_Rico, // 0x6752ca31, America/Puerto_Rico
  &kAtcZoneUS_Indiana_Starke, // 0x67977be7, US/Indiana-Starke -> America/Indiana/Knox
  &kAtcZoneAmerica_Buenos_Aires, // 0x67d79a05, America/Buenos_Aires -> America/Argentina/Buenos_Aires
  &kAtcZoneAfrica_Freetown, // 0x6823dd64, Africa/Freetown -> Africa/Abidjan
  &kAtcZoneIndian_Christmas, // 0x68c207d5, Indian/Christmas -> Asia/Bangkok
  &kAtcZoneAsia_Novokuznetsk, // 0x69264f93, Asia/Novokuznetsk
  &kAtcZoneAmerica_Indianapolis, // 0x6a009ae1, America/Indianapolis -> America/Indiana/Indianapolis
  &kAtcZoneEurope_Sarajevo, // 0x6a576c3f, Europe/Sarajevo -> Europe/Belgrade
  &kAtcZoneAmerica_Curacao, // 0x6a879184, America/Curacao -> America/Puerto_Rico
  &kAtcZoneAmerica_Tijuana, // 0x6aa1df72, America/Tijuana
  &kAtcZoneAsia_Makassar, // 0x6aa21c85, Asia/Makassar
  &kAtcZoneEurope_Helsinki, // 0x6ab2975b, Europe/Helsinki
  &kAtcZoneAmerica_Lower_Princes, // 0x6ae45b62, America/Lower_Princes -> America/Puerto_Rico
  &kAtcZoneAmerica_Porto_Velho, // 0x6b1aac77, America/Porto_Velho
  &kAtcZoneEurope_Samara, // 0x6bc0b139, Europe/Samara
  &kAtcZoneEurope_Skopje, // 0x6c76fdd0, Europe/Skopje -> Europe/Belgrade
  &kAtcZoneAmerica_Edmonton, // 0x6cb9484a, America/Edmonton
  &kAtcZoneAmerica_Dawson_Creek, // 0x6cf24e5b, America/Dawson_Creek
  &kAtcZoneAsia_Rangoon, // 0x6d1217c6, Asia/Rangoon -> Asia/Yangon
  &kAtcZoneUS_East_Indiana, // 0x6dcf558a, US/East-Indiana -> America/Indiana/Indianapolis
  &kAtcZoneAmerica_Grand_Turk, // 0x6e216197, America/Grand_Turk
  &kAtcZoneAmerica_Blanc_Sablon, // 0x6e299892, America/Blanc-Sablon -> America/Puerto_Rico
  &kAtcZoneEurope_Tirane, // 0x6ea95b47, Europe/Tirane
  &kAtcZoneUS_Mountain, // 0x6eb88247, US/Mountain -> America/Denver
  &kAtcZoneAntarctica_McMurdo, // 0x6eeb5585, Antarctica/McMurdo -> Pacific/Auckland
  &kAtcZoneAmerica_Araguaina, // 0x6f9a3aef, America/Araguaina
  &kAtcZoneAfrica_Lubumbashi, // 0x6fd88566, Africa/Lubumbashi -> Africa/Maputo
  &kAtcZoneIndian_Reunion, // 0x7076c047, Indian/Reunion -> Asia/Dubai
  &kAtcZoneAsia_Qyzylorda, // 0x71282e81, Asia/Qyzylorda
  &kAtcZoneAsia_Kolkata, // 0x72c06cd9, Asia/Kolkata
  &kAtcZoneEurope_Vienna, // 0x734cc2e5, Europe/Vienna
  &kAtcZoneAfrica_Asmara, // 0x73b278ef, Africa/Asmara -> Africa/Nairobi
  &kAtcZoneAfrica_Asmera, // 0x73b289f3, Africa/Asmera -> Africa/Nairobi
  &kAtcZoneAsia_Kamchatka, // 0x73baf9d7, Asia/Kamchatka
  &kAtcZoneAmerica_Santarem, // 0x740caec1, America/Santarem
  &kAtcZoneAmerica_Santiago, // 0x7410c9bc, America/Santiago
  &kAtcZoneAfrica_Bamako, // 0x74c1e7a5, Africa/Bamako -> Africa/Abidjan
  &kAtcZoneAfrica_Bangui, // 0x74c28ed0, Africa/Bangui -> Africa/Lagos
  &kAtcZoneAfrica_Banjul, // 0x74c29b96, Africa/Banjul -> Africa/Abidjan
  &kAtcZoneEurope_Nicosia, // 0x74efab8a, Europe/Nicosia -> Asia/Nicosia
  &kAtcZoneEurope_Warsaw, // 0x75185c19, Europe/Warsaw
  &kAtcZoneAmerica_El_Salvador, // 0x752ad652, America/El_Salvador
  &kAtcZoneAfrica_Bissau, // 0x75564141, Africa/Bissau
  &kAtcZoneAmerica_Santo_Domingo, // 0x75a0d177, America/Santo_Domingo
  &kAtcZoneUS_Michigan, // 0x766bb7bc, US/Michigan -> America/Detroit
  &kAtcZoneCanada_Saskatchewan, // 0x77311f49, Canada/Saskatchewan -> America/Regina
  &kAtcZoneAfrica_Accra, // 0x77d5b054, Africa/Accra -> Africa/Abidjan
  &kAtcZoneAfrica_Cairo, // 0x77f8e228, Africa/Cairo
  &kAtcZoneAfrica_Ceuta, // 0x77fb46ec, Africa/Ceuta
  &kAtcZoneAfrica_Dakar, // 0x780b00fd, Africa/Dakar -> Africa/Abidjan
  &kAtcZoneAfrica_Lagos, // 0x789bb5d0, Africa/Lagos
  &kAtcZoneAfrica_Windhoek, // 0x789c9bd3, Africa/Windhoek
  &kAtcZoneCanada_Yukon, // 0x78dd35c2, Canada/Yukon -> America/Whitehorse
  &kAtcZoneAmerica_Toronto, // 0x792e851b, America/Toronto
  &kAtcZoneAmerica_Tortola, // 0x7931462b, America/Tortola -> America/Puerto_Rico
  &kAtcZoneAfrica_Tunis, // 0x79378e6d, Africa/Tunis
  &kAtcZoneAfrica_Douala, // 0x7a6df310, Africa/Douala -> Africa/Lagos
  &kAtcZoneAfrica_Conakry, // 0x7ab36b31, Africa/Conakry -> Africa/Abidjan
  &kAtcZoneIndian_Mauritius, // 0x7b09c02a, Indian/Mauritius
  &kAtcZoneAtlantic_Stanley, // 0x7bb3e1c4, Atlantic/Stanley
  &kAtcZoneAmerica_Ensenada, // 0x7bc95445, America/Ensenada -> America/Tijuana
  &kAtcZoneEurope_Zagreb, // 0x7c11c9ff, Europe/Zagreb -> Europe/Belgrade
  &kAtcZoneCuba, // 0x7c83cba0, Cuba -> America/Havana
  &kAtcZoneEire, // 0x7c84b36a, Eire -> Europe/Dublin
  &kAtcZoneGMT0, // 0x7c8550fd, GMT0 -> Etc/GMT
  &kAtcZoneIran, // 0x7c87090f, Iran -> Asia/Tehran
  &kAtcZoneW_SU, // 0x7c8d8ef1, W-SU -> Europe/Moscow
  &kAtcZoneZulu, // 0x7c9069b5, Zulu -> Etc/UTC
  &kAtcZoneEurope_Zurich, // 0x7d8195b9, Europe/Zurich
  &kAtcZoneChile_Continental, // 0x7e2bdb18, Chile/Continental -> America/Santiago
  &kAtcZoneAmerica_Fort_Wayne, // 0x7eaaaf24, America/Fort_Wayne -> America/Indiana/Indianapolis
  &kAtcZoneAsia_Kuching, // 0x801b003b, Asia/Kuching
  &kAtcZoneAtlantic_Madeira, // 0x81b5c037, Atlantic/Madeira
  &kAtcZoneAmerica_Atikokan, // 0x81b92098, America/Atikokan -> America/Panama
  &kAtcZoneAfrica_Harare, // 0x82c39a2d, Africa/Harare -> Africa/Maputo
  &kAtcZoneAmerica_Shiprock, // 0x82fb7049, America/Shiprock -> America/Denver
  &kAtcZonePacific_Kiritimati, // 0x8305073a, Pacific/Kiritimati
  &kAtcZoneAmerica_St_Vincent, // 0x8460e523, America/St_Vincent -> America/Puerto_Rico
  &kAtcZoneAmerica_Metlakatla, // 0x84de2686, America/Metlakatla
  &kAtcZoneAsia_Yakutsk, // 0x87bb3a9e, Asia/Yakutsk
  &kAtcZoneAmerica_Chihuahua, // 0x8827d776, America/Chihuahua
  &kAtcZonePacific_Pitcairn, // 0x8837d8bd, Pacific/Pitcairn
  &kAtcZoneAsia_Vientiane, // 0x89d68d75, Asia/Vientiane -> Asia/Bangkok
  &kAtcZonePacific_Chuuk, // 0x8a090b23, Pacific/Chuuk -> Pacific/Port_Moresby
  &kAtcZonePacific_Efate, // 0x8a2bce28, Pacific/Efate
  &kAtcZoneAfrica_Kigali, // 0x8a4dcf2b, Africa/Kigali -> Africa/Maputo
  &kAtcZoneAustralia_ACT, // 0x8a970eb2, Australia/ACT -> Australia/Sydney
  &kAtcZoneAustralia_LHI, // 0x8a973e17, Australia/LHI -> Australia/Lord_Howe
  &kAtcZoneAustralia_NSW, // 0x8a974812, Australia/NSW -> Australia/Sydney
  &kAtcZonePacific_Nauru, // 0x8acc41ae, Pacific/Nauru
  &kAtcZoneEST5EDT, // 0x8adc72a3, EST5EDT
  &kAtcZonePacific_Palau, // 0x8af04a36, Pacific/Palau
  &kAtcZonePacific_Samoa, // 0x8b2699b4, Pacific/Samoa -> Pacific/Pago_Pago
  &kAtcZoneAmerica_Winnipeg, // 0x8c7dafc7, America/Winnipeg
  &kAtcZoneAustralia_Eucla, // 0x8cf99e44, Australia/Eucla
  &kAtcZoneAmerica_Argentina_Catamarca, // 0x8d40986b, America/Argentina/Catamarca
  &kAtcZoneAfrica_Luanda, // 0x8d7909cf, Africa/Luanda -> Africa/Lagos
  &kAtcZoneAfrica_Lusaka, // 0x8d82b23b, Africa/Lusaka -> Africa/Maputo
  &kAtcZoneAustralia_North, // 0x8d997165, Australia/North -> Australia/Darwin
  &kAtcZoneAustralia_Perth, // 0x8db8269d, Australia/Perth
  &kAtcZoneAustralia_South, // 0x8df3f8ad, Australia/South -> Australia/Adelaide
  &kAtcZonePacific_Kwajalein, // 0x8e216759, Pacific/Kwajalein
  &kAtcZoneAmerica_Port_au_Prince, // 0x8e4a7bdc, America/Port-au-Prince
  &kAtcZoneAfrica_Malabo, // 0x8e6a1906, Africa/Malabo -> Africa/Lagos
  &kAtcZoneAfrica_Maputo, // 0x8e6ca1f0, Africa/Maputo
  &kAtcZoneAfrica_Maseru, // 0x8e6e02c7, Africa/Maseru -> Africa/Johannesburg
  &kAtcZonePacific_Norfolk, // 0x8f4eb4be, Pacific/Norfolk
  &kAtcZoneAmerica_Godthab, // 0x8f7eba1f, America/Godthab -> America/Nuuk
  &kAtcZoneAustralia_Yancowinna, // 0x90bac131, Australia/Yancowinna -> Australia/Broken_Hill
  &kAtcZoneAfrica_Niamey, // 0x914a30fd, Africa/Niamey -> Africa/Lagos
  &kAtcZoneAsia_Yerevan, // 0x9185c8cc, Asia/Yerevan
  &kAtcZoneAmerica_Detroit, // 0x925cfbc1, America/Detroit
  &kAtcZoneAsia_Choibalsan, // 0x928aa4a6, Asia/Choibalsan
  &kAtcZoneAntarctica_Macquarie, // 0x92f47626, Antarctica/Macquarie
  &kAtcZoneAmerica_Belize, // 0x93256c81, America/Belize
  &kAtcZoneMexico_General, // 0x93711d57, Mexico/General -> America/Mexico_City
  &kAtcZoneAmerica_Bogota, // 0x93d7bc62, America/Bogota
  &kAtcZoneAsia_Pyongyang, // 0x93ed1c8e, Asia/Pyongyang
  &kAtcZoneAmerica_Indiana_Petersburg, // 0x94ac7acc, America/Indiana/Petersburg
  &kAtcZoneAmerica_Cancun, // 0x953331be, America/Cancun
  &kAtcZoneAmerica_Cayman, // 0x953961df, America/Cayman -> America/Panama
  &kAtcZoneAmerica_Glace_Bay, // 0x9681f8dd, America/Glace_Bay
  &kAtcZoneAsia_Khandyga, // 0x9685a4d9, Asia/Khandyga
  &kAtcZoneAmerica_Grenada, // 0x968ce4d8, America/Grenada -> America/Puerto_Rico
  &kAtcZoneAmerica_Cuiaba, // 0x969a52eb, America/Cuiaba
  &kAtcZoneAmerica_Dawson, // 0x978d8d12, America/Dawson
  &kAtcZoneAmerica_Aruba, // 0x97cf8651, America/Aruba -> America/Puerto_Rico
  &kAtcZoneAmerica_Denver, // 0x97d10b2a, America/Denver
  &kAtcZoneAmerica_Bahia, // 0x97d815fb, America/Bahia
  &kAtcZoneAmerica_Belem, // 0x97da580b, America/Belem
  &kAtcZoneAmerica_Boise, // 0x97dfc8d8, America/Boise
  &kAtcZoneEurope_Andorra, // 0x97f6764b, Europe/Andorra
  &kAtcZoneAmerica_Adak, // 0x97fe49d7, America/Adak
  &kAtcZoneAmerica_Atka, // 0x97fe8f27, America/Atka -> America/Adak
  &kAtcZoneAmerica_Lima, // 0x980468c9, America/Lima
  &kAtcZoneAmerica_Nome, // 0x98059b15, America/Nome
  &kAtcZoneAmerica_Nuuk, // 0x9805b5a9, America/Nuuk
  &kAtcZoneIndian_Maldives, // 0x9869681c, Indian/Maldives
  &kAtcZoneAmerica_Jujuy, // 0x9873dbbd, America/Jujuy -> America/Argentina/Jujuy
  &kAtcZoneAmerica_Sitka, // 0x99104ce2, America/Sitka
  &kAtcZoneAmerica_Thule, // 0x9921dd68, America/Thule
  &kAtcZonePacific_Rarotonga, // 0x9981a3b0, Pacific/Rarotonga
  &kAtcZoneAsia_Kathmandu, // 0x9a96ce6f, Asia/Kathmandu
  &kAtcZoneBrazil_DeNoronha, // 0x9b4cb496, Brazil/DeNoronha -> America/Noronha
  &kAtcZoneAmerica_North_Dakota_Beulah, // 0x9b52b384, America/North_Dakota/Beulah
  &kAtcZoneAmerica_Rainy_River, // 0x9cd58a10, America/Rainy_River
  &kAtcZoneEurope_Budapest, // 0x9ce0197c, Europe/Budapest
  &kAtcZoneAsia_Baghdad, // 0x9ceffbed, Asia/Baghdad
  &kAtcZoneAsia_Bahrain, // 0x9d078487, Asia/Bahrain -> Asia/Qatar
  &kAtcZoneEtc_GMT_PLUS_0, // 0x9d13da13, Etc/GMT+0 -> Etc/GMT
  &kAtcZoneEtc_GMT_PLUS_1, // 0x9d13da14, Etc/GMT+1
  &kAtcZoneEtc_GMT_PLUS_2, // 0x9d13da15, Etc/GMT+2
  &kAtcZoneEtc_GMT_PLUS_3, // 0x9d13da16, Etc/GMT+3
  &kAtcZoneEtc_GMT_PLUS_4, // 0x9d13da17, Etc/GMT+4
  &kAtcZoneEtc_GMT_PLUS_5, // 0x9d13da18, Etc/GMT+5
  &kAtcZoneEtc_GMT_PLUS_6, // 0x9d13da19, Etc/GMT+6
  &kAtcZoneEtc_GMT_PLUS_7, // 0x9d13da1a, Etc/GMT+7
  &kAtcZoneEtc_GMT_PLUS_8, // 0x9d13da1b, Etc/GMT+8
  &kAtcZoneEtc_GMT_PLUS_9, // 0x9d13da1c, Etc/GMT+9
  &kAtcZoneEtc_GMT_0, // 0x9d13da55, Etc/GMT-0 -> Etc/GMT
  &kAtcZoneEtc_GMT_1, // 0x9d13da56, Etc/GMT-1
  &kAtcZoneEtc_GMT_2, // 0x9d13da57, Etc/GMT-2
  &kAtcZoneEtc_GMT_3, // 0x9d13da58, Etc/GMT-3
  &kAtcZoneEtc_GMT_4, // 0x9d13da59, Etc/GMT-4
  &kAtcZoneEtc_GMT_5, // 0x9d13da5a, Etc/GMT-5
  &kAtcZoneEtc_GMT_6, // 0x9d13da5b, Etc/GMT-6
  &kAtcZoneEtc_GMT_7, // 0x9d13da5c, Etc/GMT-7
  &kAtcZoneEtc_GMT_8, // 0x9d13da5d, Etc/GMT-8
  &kAtcZoneEtc_GMT_9, // 0x9d13da5e, Etc/GMT-9
  &kAtcZoneAmerica_Nipigon, // 0x9d2a8b1a, America/Nipigon
  &kAtcZoneAmerica_Rio_Branco, // 0x9d352764, America/Rio_Branco
  &kAtcZoneAsia_Bangkok, // 0x9d6e3aaf, Asia/Bangkok
  &kAtcZoneAfrica_El_Aaiun, // 0x9d6fb118, Africa/El_Aaiun
  &kAtcZoneAmerica_North_Dakota_Center, // 0x9da42814, America/North_Dakota/Center
  &kAtcZoneAsia_Barnaul, // 0x9dba4997, Asia/Barnaul
  &kAtcZoneAfrica_Tripoli, // 0x9dfebd3d, Africa/Tripoli
  &kAtcZoneEurope_Istanbul, // 0x9e09d6e6, Europe/Istanbul
  &kAtcZoneIndian_Antananarivo, // 0x9ebf5289, Indian/Antananarivo -> Africa/Nairobi
  &kAtcZoneAfrica_Ndjamena, // 0x9fe09898, Africa/Ndjamena
  &kAtcZoneAmerica_Guyana, // 0x9ff7bd0b, America/Guyana
  &kAtcZoneAfrica_Dar_es_Salaam, // 0xa04c47b6, Africa/Dar_es_Salaam -> Africa/Nairobi
  &kAtcZoneAmerica_Havana, // 0xa0e15675, America/Havana
  &kAtcZoneAsia_Novosibirsk, // 0xa2a435cb, Asia/Novosibirsk
  &kAtcZoneEurope_Kiev, // 0xa2c19eb3, Europe/Kiev -> Europe/Kyiv
  &kAtcZoneEurope_Kyiv, // 0xa2c1e347, Europe/Kyiv
  &kAtcZoneEurope_Oslo, // 0xa2c3fba1, Europe/Oslo -> Europe/Berlin
  &kAtcZoneEurope_Riga, // 0xa2c57587, Europe/Riga
  &kAtcZoneEurope_Rome, // 0xa2c58fd7, Europe/Rome
  &kAtcZoneAmerica_Inuvik, // 0xa42189fc, America/Inuvik
  &kAtcZoneAmerica_Argentina_La_Rioja, // 0xa46b7eef, America/Argentina/La_Rioja
  &kAtcZoneAsia_Almaty, // 0xa61f41fa, Asia/Almaty
  &kAtcZoneAsia_Anadyr, // 0xa63cebd1, Asia/Anadyr
  &kAtcZoneAsia_Aqtobe, // 0xa67dcc4e, Asia/Aqtobe
  &kAtcZoneAsia_Atyrau, // 0xa6b6e068, Asia/Atyrau
  &kAtcZoneAmerica_Juneau, // 0xa6f13e2e, America/Juneau
  &kAtcZoneAustralia_Lord_Howe, // 0xa748b67d, Australia/Lord_Howe
  &kAtcZonePacific_Port_Moresby, // 0xa7ba7f68, Pacific/Port_Moresby
  &kAtcZoneAsia_Katmandu, // 0xa7ec12c7, Asia/Katmandu -> Asia/Kathmandu
  &kAtcZoneAsia_Beirut, // 0xa7f3d5fd, Asia/Beirut
  &kAtcZoneSingapore, // 0xa8598c8d, Singapore -> Asia/Singapore
  &kAtcZoneAfrica_Nairobi, // 0xa87ab57e, Africa/Nairobi
  &kAtcZoneAsia_Brunei, // 0xa8e595f7, Asia/Brunei -> Asia/Kuching
  &kAtcZoneUS_Pacific, // 0xa950f6ab, US/Pacific -> America/Los_Angeles
  &kAtcZonePacific_Galapagos, // 0xa952f752, Pacific/Galapagos
  &kAtcZoneAmerica_Argentina_Mendoza, // 0xa9f72d5c, America/Argentina/Mendoza
  &kAtcZoneAmerica_La_Paz, // 0xaa29125d, America/La_Paz
  &kAtcZoneAmerica_Noronha, // 0xab5116fb, America/Noronha
  &kAtcZoneAmerica_Coral_Harbour, // 0xabcb7569, America/Coral_Harbour -> America/Panama
  &kAtcZoneAmerica_Maceio, // 0xac80c6d4, America/Maceio
  &kAtcZoneAmerica_Manaus, // 0xac86bf8b, America/Manaus
  &kAtcZoneAmerica_Merida, // 0xacd172d8, America/Merida
  &kAtcZoneEurope_Chisinau, // 0xad58aa18, Europe/Chisinau
  &kAtcZoneAmerica_Nassau, // 0xaedef011, America/Nassau -> America/Toronto
  &kAtcZoneAmerica_Anguilla, // 0xafe31333, America/Anguilla -> America/Puerto_Rico
  &kAtcZoneEurope_Uzhgorod, // 0xb066f5d6, Europe/Uzhgorod -> Europe/Kyiv
  &kAtcZoneAustralia_Broken_Hill, // 0xb06eada3, Australia/Broken_Hill
  &kAtcZoneAsia_Bishkek, // 0xb0728553, Asia/Bishkek
  &kAtcZoneChile_EasterIsland, // 0xb0982af8, Chile/EasterIsland -> Pacific/Easter
  &kAtcZonePacific_Johnston, // 0xb15d7b36, Pacific/Johnston -> Pacific/Honolulu
  &kAtcZoneAfrica_Timbuktu, // 0xb164d56f, Africa/Timbuktu -> Africa/Abidjan
  &kAtcZoneAmerica_St_Thomas, // 0xb1b3d778, America/St_Thomas -> America/Puerto_Rico
  &kAtcZoneAmerica_Paramaribo, // 0xb319e4c4, America/Paramaribo
  &kAtcZoneAmerica_Panama, // 0xb3863854, America/Panama
  &kAtcZoneCanada_Newfoundland, // 0xb396e991, Canada/Newfoundland -> America/St_Johns
  &kAtcZoneAsia_Harbin, // 0xb5af1186, Asia/Harbin -> Asia/Shanghai
  &kAtcZoneAsia_Hebron, // 0xb5eef250, Asia/Hebron
  &kAtcZoneAmerica_Goose_Bay, // 0xb649541e, America/Goose_Bay
  &kAtcZoneAmerica_Los_Angeles, // 0xb7f7e8f2, America/Los_Angeles
  &kAtcZoneAmerica_Recife, // 0xb8730494, America/Recife
  &kAtcZoneAmerica_Regina, // 0xb875371c, America/Regina
  &kAtcZoneAsia_Ashgabat, // 0xba87598d, Asia/Ashgabat
  &kAtcZoneIsrael, // 0xba88c9e5, Israel -> Asia/Jerusalem
  &kAtcZonePacific_Yap, // 0xbb40138d, Pacific/Yap -> Pacific/Port_Moresby
  &kAtcZoneAmerica_Halifax, // 0xbc5b7183, America/Halifax
  &kAtcZoneEurope_Ljubljana, // 0xbd98cdb7, Europe/Ljubljana -> Europe/Belgrade
  &kAtcZoneAsia_Kuwait, // 0xbe1b2f27, Asia/Kuwait -> Asia/Riyadh
  &kAtcZoneEurope_Tiraspol, // 0xbe704472, Europe/Tiraspol -> Europe/Chisinau
  &kAtcZoneAsia_Srednekolymsk, // 0xbf8e337d, Asia/Srednekolymsk
  &kAtcZoneAmerica_Argentina_Cordoba, // 0xbfccc308, America/Argentina/Cordoba
  &kAtcZoneAmerica_Tegucigalpa, // 0xbfd6fd4c, America/Tegucigalpa
  &kAtcZoneAmerica_Antigua, // 0xc067a32f, America/Antigua -> America/Puerto_Rico
  &kAtcZoneEurope_Busingen, // 0xc06d2cdf, Europe/Busingen -> Europe/Zurich
  &kAtcZoneAsia_Manila, // 0xc156c944, Asia/Manila
  &kAtcZoneAfrica_Kampala, // 0xc1d30e31, Africa/Kampala -> Africa/Nairobi
  &kAtcZoneAmerica_Knox_IN, // 0xc1db9a1c, America/Knox_IN -> America/Indiana/Knox
  &kAtcZoneAfrica_Abidjan, // 0xc21305a3, Africa/Abidjan
  &kAtcZoneAmerica_Virgin, // 0xc2183ab5, America/Virgin -> America/Puerto_Rico
  &kAtcZoneAsia_Phnom_Penh, // 0xc224945e, Asia/Phnom_Penh -> Asia/Bangkok
  &kAtcZoneAsia_Muscat, // 0xc2c3565f, Asia/Muscat -> Asia/Dubai
  &kAtcZoneAmerica_Punta_Arenas, // 0xc2c3bce7, America/Punta_Arenas
  &kAtcZonePortugal, // 0xc3274593, Portugal -> Europe/Lisbon
  &kAtcZoneNavajo, // 0xc4ef0e24, Navajo -> America/Denver
  &kAtcZoneAfrica_Casablanca, // 0xc59f1b33, Africa/Casablanca
  &kAtcZoneAmerica_Argentina_Rio_Gallegos, // 0xc5b0f565, America/Argentina/Rio_Gallegos
  &kAtcZoneAsia_Jayapura, // 0xc6833c2f, Asia/Jayapura
  &kAtcZoneAmerica_Resolute, // 0xc7093459, America/Resolute
  &kAtcZoneAsia_Chungking, // 0xc7121dd0, Asia/Chungking -> Asia/Shanghai
  &kAtcZoneGreenwich, // 0xc84d4221, Greenwich -> Etc/GMT
  &kAtcZoneAmerica_Rankin_Inlet, // 0xc8de4984, America/Rankin_Inlet
  &kAtcZonePoland, // 0xca913b23, Poland -> Europe/Warsaw
  &kAtcZoneUS_Central, // 0xcabdcb25, US/Central -> America/Chicago
  &kAtcZoneEurope_Vatican, // 0xcb485dca, Europe/Vatican -> Europe/Rome
  &kAtcZoneAmerica_Barbados, // 0xcbbc3b04, America/Barbados
  &kAtcZoneAmerica_Porto_Acre, // 0xcce5bf54, America/Porto_Acre -> America/Rio_Branco
  &kAtcZoneAmerica_Guadeloupe, // 0xcd1f8a31, America/Guadeloupe -> America/Puerto_Rico
  &kAtcZoneAntarctica_South_Pole, // 0xcd96b290, Antarctica/South_Pole -> Pacific/Auckland
  &kAtcZoneAsia_Riyadh, // 0xcd973d93, Asia/Riyadh
  &kAtcZoneAmerica_Dominica, // 0xcecb4c4a, America/Dominica -> America/Puerto_Rico
  &kAtcZoneEurope_San_Marino, // 0xcef7724b, Europe/San_Marino -> Europe/Rome
  &kAtcZoneAsia_Saigon, // 0xcf52f713, Asia/Saigon -> Asia/Ho_Chi_Minh
  &kAtcZonePacific_Easter, // 0xcf54f7e7, Pacific/Easter
  &kAtcZoneAsia_Singapore, // 0xcf8581fa, Asia/Singapore
  &kAtcZoneAsia_Krasnoyarsk, // 0xd0376c6a, Asia/Krasnoyarsk
  &kAtcZoneEurope_Belfast, // 0xd07dd1e5, Europe/Belfast -> Europe/London
  &kAtcZoneAmerica_Mexico_City, // 0xd0d93f43, America/Mexico_City
  &kAtcZoneUniversal, // 0xd0ff523e, Universal -> Etc/UTC
  &kAtcZoneAsia_Taipei, // 0xd1a844ae, Asia/Taipei
  &kAtcZoneAsia_Tehran, // 0xd1f02254, Asia/Tehran
  &kAtcZoneAsia_Thimbu, // 0xd226e31b, Asia/Thimbu -> Asia/Thimphu
  &kAtcZoneArctic_Longyearbyen, // 0xd23e7859, Arctic/Longyearbyen -> Europe/Berlin
  &kAtcZoneAustralia_Queensland, // 0xd326ed0a, Australia/Queensland -> Australia/Brisbane
  &kAtcZoneEurope_Kaliningrad, // 0xd33b2f28, Europe/Kaliningrad
  &kAtcZoneAmerica_Argentina_Buenos_Aires, // 0xd43b4c0d, America/Argentina/Buenos_Aires
  &kAtcZoneTurkey, // 0xd455e469, Turkey -> Europe/Istanbul
  &kAtcZoneAfrica_Juba, // 0xd51b395c, Africa/Juba
  &kAtcZoneAfrica_Lome, // 0xd51c3a07, Africa/Lome -> Africa/Abidjan
  &kAtcZoneAsia_Urumqi, // 0xd5379735, Asia/Urumqi
  &kAtcZoneAmerica_Cambridge_Bay, // 0xd5a44aff, America/Cambridge_Bay
  &kAtcZoneAfrica_Johannesburg, // 0xd5d157a0, Africa/Johannesburg
  &kAtcZoneAmerica_Port_of_Spain, // 0xd8b28d59, America/Port_of_Spain -> America/Puerto_Rico
  &kAtcZoneEtc_GMT, // 0xd8e2de58, Etc/GMT
  &kAtcZoneEtc_UCT, // 0xd8e3189c, Etc/UCT -> Etc/UTC
  &kAtcZoneEtc_UTC, // 0xd8e31abc, Etc/UTC
  &kAtcZoneAmerica_Yakutat, // 0xd8ee31e9, America/Yakutat
  &kAtcZoneAfrica_Algiers, // 0xd94515c1, Africa/Algiers
  &kAtcZonePST8PDT, // 0xd99ee2dc, PST8PDT
  &kAtcZoneEurope_Bratislava, // 0xda493bed, Europe/Bratislava -> Europe/Prague
  &kAtcZoneEurope_Simferopol, // 0xda9eb724, Europe/Simferopol
  &kAtcZonePacific_Funafuti, // 0xdb402d65, Pacific/Funafuti -> Pacific/Tarawa
  &kAtcZoneAmerica_Matamoros, // 0xdd1b0259, America/Matamoros
  &kAtcZonePacific_Kanton, // 0xdd512f0e, Pacific/Kanton
  &kAtcZoneAsia_Yangon, // 0xdd54a8be, Asia/Yangon
  &kAtcZoneEurope_Vilnius, // 0xdd63b8ce, Europe/Vilnius
  &kAtcZoneAustralia_West, // 0xdd858a5d, Australia/West -> Australia/Perth
  &kAtcZonePacific_Kosrae, // 0xde5139a8, Pacific/Kosrae
  &kAtcZoneAmerica_Kentucky_Monticello, // 0xde71c439, America/Kentucky/Monticello
  &kAtcZoneEurope_Brussels, // 0xdee07337, Europe/Brussels
  &kAtcZoneAmerica_Swift_Current, // 0xdef98e55, America/Swift_Current
  &kAtcZoneAmerica_Rosario, // 0xdf448665, America/Rosario -> America/Argentina/Cordoba
  &kAtcZoneAsia_Irkutsk, // 0xdfbf213f, Asia/Irkutsk
  &kAtcZoneEurope_Ulyanovsk, // 0xe03783d0, Europe/Ulyanovsk
  &kAtcZoneAustralia_Lindeman, // 0xe05029e2, Australia/Lindeman
  &kAtcZoneEurope_Belgrade, // 0xe0532b3a, Europe/Belgrade
  &kAtcZoneAfrica_Blantyre, // 0xe08d813b, Africa/Blantyre -> Africa/Maputo
  &kAtcZoneAmerica_Menominee, // 0xe0e9c583, America/Menominee
  &kAtcZoneEurope_Copenhagen, // 0xe0ed30bc, Europe/Copenhagen -> Europe/Berlin
  &kAtcZoneAtlantic_Faroe, // 0xe110a971, Atlantic/Faroe
  &kAtcZonePacific_Majuro, // 0xe1f95371, Pacific/Majuro -> Pacific/Tarawa
  &kAtcZoneAntarctica_Casey, // 0xe2022583, Antarctica/Casey
  &kAtcZoneAntarctica_Davis, // 0xe2144b45, Antarctica/Davis
  &kAtcZoneEurope_Astrakhan, // 0xe22256e1, Europe/Astrakhan
  &kAtcZonePacific_Midway, // 0xe286d38e, Pacific/Midway -> Pacific/Pago_Pago
  &kAtcZoneAntarctica_Syowa, // 0xe330c7e1, Antarctica/Syowa -> Asia/Riyadh
  &kAtcZoneAntarctica_Troll, // 0xe33f085b, Antarctica/Troll
  &kAtcZoneEurope_Saratov, // 0xe4315da4, Europe/Saratov
  &kAtcZonePacific_Noumea, // 0xe551b788, Pacific/Noumea
  &kAtcZoneIceland, // 0xe56a35b5, Iceland -> Africa/Abidjan
  &kAtcZoneIndian_Mayotte, // 0xe6880bca, Indian/Mayotte -> Africa/Nairobi
  &kAtcZoneAustralia_Tasmania, // 0xe6d76648, Australia/Tasmania -> Australia/Hobart
  &kAtcZonePacific_Honolulu, // 0xe6e70af9, Pacific/Honolulu
  &kAtcZoneAmerica_Kralendijk, // 0xe7c456c5, America/Kralendijk -> America/Puerto_Rico
  &kAtcZoneAmerica_Argentina_Tucuman, // 0xe96399eb, America/Argentina/Tucuman
  &kAtcZonePacific_Ponape, // 0xe9f80086, Pacific/Ponape -> Pacific/Guadalcanal
  &kAtcZoneEurope_Zaporozhye, // 0xeab9767f, Europe/Zaporozhye -> Europe/Kyiv
  &kAtcZoneEurope_Isle_of_Man, // 0xeaf84580, Europe/Isle_of_Man -> Europe/London
  &kAtcZoneAsia_Magadan, // 0xebacc19b, Asia/Magadan
  &kAtcZoneAmerica_Ojinaga, // 0xebfde83f, America/Ojinaga
  &kAtcZonePacific_Saipan, // 0xeff7a35f, Pacific/Saipan -> Pacific/Guam
  &kAtcZoneCST6CDT, // 0xf0e87d00, CST6CDT
  &kAtcZonePacific_Tahiti, // 0xf24c2446, Pacific/Tahiti
  &kAtcZonePacific_Tarawa, // 0xf2517e63, Pacific/Tarawa
  &kAtcZoneMST7MDT, // 0xf2af9375, MST7MDT
  &kAtcZoneCanada_Eastern, // 0xf3612d5e, Canada/Eastern -> America/Toronto
  &kAtcZoneAsia_Tashkent, // 0xf3924254, Asia/Tashkent
  &kAtcZoneAsia_Sakhalin, // 0xf4a1c9bd, Asia/Sakhalin
  &kAtcZonePacific_Guadalcanal, // 0xf4dd25f0, Pacific/Guadalcanal
  &kAtcZoneEtc_GMT0, // 0xf53ea988, Etc/GMT0 -> Etc/GMT
  &kAtcZoneEtc_Zulu, // 0xf549c240, Etc/Zulu -> Etc/UTC
  &kAtcZoneAmerica_Danmarkshavn, // 0xf554d204, America/Danmarkshavn
  &kAtcZoneAsia_Shanghai, // 0xf895a7f5, Asia/Shanghai
  &kAtcZoneEurope_Gibraltar, // 0xf8e325fc, Europe/Gibraltar
  &kAtcZoneAsia_Chongqing, // 0xf937fb90, Asia/Chongqing -> Asia/Shanghai
  &kAtcZoneAtlantic_Azores, // 0xf93ed918, Atlantic/Azores
  &kAtcZonePacific_Wallis, // 0xf94ddb0f, Pacific/Wallis -> Pacific/Tarawa
  &kAtcZoneAmerica_Thunder_Bay, // 0xf962e71b, America/Thunder_Bay
  &kAtcZoneAmerica_Eirunepe, // 0xf9b29683, America/Eirunepe
  &kAtcZoneAmerica_Montevideo, // 0xfa214780, America/Montevideo
  &kAtcZoneUS_Alaska, // 0xfa300bc9, US/Alaska -> America/Anchorage
  &kAtcZoneGB_Eire, // 0xfa70e300, GB-Eire -> Europe/London
  &kAtcZoneEurope_Kirov, // 0xfaf5abef, Europe/Kirov
  &kAtcZoneEurope_Malta, // 0xfb1560f3, Europe/Malta
  &kAtcZoneEurope_Minsk, // 0xfb19cc66, Europe/Minsk
  &kAtcZoneEurope_Bucharest, // 0xfb349ec5, Europe/Bucharest
  &kAtcZoneAfrica_Khartoum, // 0xfb3d4205, Africa/Khartoum
  &kAtcZoneEurope_Paris, // 0xfb4bc2a3, Europe/Paris
  &kAtcZoneAsia_Yekaterinburg, // 0xfb544c6e, Asia/Yekaterinburg
  &kAtcZoneEurope_Sofia, // 0xfb898656, Europe/Sofia
  &kAtcZoneCanada_Mountain, // 0xfb8a8217, Canada/Mountain -> America/Edmonton
  &kAtcZoneEurope_Vaduz, // 0xfbb81bae, Europe/Vaduz -> Europe/Zurich
  &kAtcZoneAtlantic_Canary, // 0xfc23f2c2, Atlantic/Canary
  &kAtcZoneMexico_BajaNorte, // 0xfcf7150f, Mexico/BajaNorte -> America/Tijuana
  &kAtcZoneAmerica_Santa_Isabel, // 0xfd18a56c, America/Santa_Isabel -> America/Tijuana
  &kAtcZoneAmerica_Campo_Grande, // 0xfec3e7a6, America/Campo_Grande

};

//---------------------------------------------------------------------------
// Link (thin) Entry registry. Sorted by linkId. Links are references to Zones.
//---------------------------------------------------------------------------
const AtcLinkEntry kAtcLinkRegistry[241]  = {
  { kAtcZoneIdGB, kAtcZoneIdEurope_London }, // 0x005973ae -> 0x5c6a84ae
  { kAtcZoneIdNZ, kAtcZoneIdPacific_Auckland }, // 0x005974ad -> 0x25062f86
  { kAtcZoneIdAsia_Kuala_Lumpur, kAtcZoneIdAsia_Singapore }, // 0x014763c4 -> 0xcf8581fa
  { kAtcZoneIdAfrica_Libreville, kAtcZoneIdAfrica_Lagos }, // 0x01d96de4 -> 0x789bb5d0
  { kAtcZoneIdIndian_Cocos, kAtcZoneIdAsia_Yangon }, // 0x021e86de -> 0xdd54a8be
  { kAtcZoneIdAustralia_Victoria, kAtcZoneIdAustralia_Melbourne }, // 0x0260d5db -> 0x0fe559a3
  { kAtcZoneIdAtlantic_Faeroe, kAtcZoneIdAtlantic_Faroe }, // 0x031ec516 -> 0xe110a971
  { kAtcZoneIdAmerica_St_Kitts, kAtcZoneIdAmerica_Puerto_Rico }, // 0x04c0507b -> 0x6752ca31
  { kAtcZoneIdAfrica_Ouagadougou, kAtcZoneIdAfrica_Abidjan }, // 0x04d7219a -> 0xc21305a3
  { kAtcZoneIdAmerica_St_Lucia, kAtcZoneIdAmerica_Puerto_Rico }, // 0x04d8b3ba -> 0x6752ca31
  { kAtcZoneIdAfrica_Bujumbura, kAtcZoneIdAfrica_Maputo }, // 0x05232a47 -> 0x8e6ca1f0
  { kAtcZoneIdAmerica_St_Barthelemy, kAtcZoneIdAmerica_Puerto_Rico }, // 0x054e6a79 -> 0x6752ca31
  { kAtcZoneIdAfrica_Addis_Ababa, kAtcZoneIdAfrica_Nairobi }, // 0x05ae1e65 -> 0xa87ab57e
  { kAtcZoneIdMexico_BajaSur, kAtcZoneIdAmerica_Mazatlan }, // 0x08ee3641 -> 0x0532189e
  { kAtcZoneIdUS_Hawaii, kAtcZoneIdPacific_Honolulu }, // 0x09c8de2f -> 0xe6e70af9
  { kAtcZoneIdGMT, kAtcZoneIdEtc_GMT }, // 0x0b87eb2d -> 0xd8e2de58
  { kAtcZoneIdPRC, kAtcZoneIdAsia_Shanghai }, // 0x0b88120a -> 0xf895a7f5
  { kAtcZoneIdROC, kAtcZoneIdAsia_Taipei }, // 0x0b881a29 -> 0xd1a844ae
  { kAtcZoneIdROK, kAtcZoneIdAsia_Seoul }, // 0x0b881a31 -> 0x15ce82da
  { kAtcZoneIdUCT, kAtcZoneIdEtc_UTC }, // 0x0b882571 -> 0xd8e31abc
  { kAtcZoneIdUTC, kAtcZoneIdEtc_UTC }, // 0x0b882791 -> 0xd8e31abc
  { kAtcZoneIdEurope_Mariehamn, kAtcZoneIdEurope_Helsinki }, // 0x0caa6496 -> 0x6ab2975b
  { kAtcZoneIdEgypt, kAtcZoneIdAfrica_Cairo }, // 0x0d1a278e -> 0x77f8e228
  { kAtcZoneIdGMT_PLUS_0, kAtcZoneIdEtc_GMT }, // 0x0d2f7028 -> 0xd8e2de58
  { kAtcZoneIdGMT_0, kAtcZoneIdEtc_GMT }, // 0x0d2f706a -> 0xd8e2de58
  { kAtcZoneIdJapan, kAtcZoneIdAsia_Tokyo }, // 0x0d712f8f -> 0x15e606a8
  { kAtcZoneIdLibya, kAtcZoneIdAfrica_Tripoli }, // 0x0d998b16 -> 0x9dfebd3d
  { kAtcZoneIdKwajalein, kAtcZoneIdPacific_Kwajalein }, // 0x0e57afbb -> 0x8e216759
  { kAtcZoneIdEurope_Amsterdam, kAtcZoneIdEurope_Brussels }, // 0x109395c2 -> 0xdee07337
  { kAtcZoneIdAsia_Dacca, kAtcZoneIdAsia_Dhaka }, // 0x14bcac5e -> 0x14c07b8b
  { kAtcZoneIdAsia_Ashkhabad, kAtcZoneIdAsia_Ashgabat }, // 0x15454f09 -> 0xba87598d
  { kAtcZoneIdAsia_Macao, kAtcZoneIdAsia_Macau }, // 0x155f88b3 -> 0x155f88b9
  { kAtcZoneIdAsia_Tel_Aviv, kAtcZoneIdAsia_Jerusalem }, // 0x166d7c2c -> 0x5becd23a
  { kAtcZoneIdAmerica_Montserrat, kAtcZoneIdAmerica_Puerto_Rico }, // 0x199b0a35 -> 0x6752ca31
  { kAtcZoneIdEurope_Podgorica, kAtcZoneIdEurope_Belgrade }, // 0x1c1a499c -> 0xe0532b3a
  { kAtcZoneIdAtlantic_Reykjavik, kAtcZoneIdAfrica_Abidjan }, // 0x1c2b4f74 -> 0xc21305a3
  { kAtcZoneIdEurope_Luxembourg, kAtcZoneIdEurope_Brussels }, // 0x1f8bc6ce -> 0xdee07337
  { kAtcZoneIdAsia_Aden, kAtcZoneIdAsia_Riyadh }, // 0x1fa7084a -> 0xcd973d93
  { kAtcZoneIdAmerica_Montreal, kAtcZoneIdAmerica_Toronto }, // 0x203a1ea8 -> 0x792e851b
  { kAtcZoneIdAmerica_Argentina_ComodRivadavia, kAtcZoneIdAmerica_Argentina_Catamarca }, // 0x22758877 -> 0x8d40986b
  { kAtcZoneIdPacific_Truk, kAtcZoneIdPacific_Port_Moresby }, // 0x234010a9 -> 0xa7ba7f68
  { kAtcZoneIdPacific_Wake, kAtcZoneIdPacific_Tarawa }, // 0x23416c2b -> 0xf2517e63
  { kAtcZoneIdEtc_Greenwich, kAtcZoneIdEtc_GMT }, // 0x26daa98c -> 0xd8e2de58
  { kAtcZoneIdAustralia_Currie, kAtcZoneIdAustralia_Hobart }, // 0x278b6a24 -> 0x32bf951a
  { kAtcZoneIdPacific_Pohnpei, kAtcZoneIdPacific_Guadalcanal }, // 0x28929f96 -> 0xf4dd25f0
  { kAtcZoneIdAustralia_Canberra, kAtcZoneIdAustralia_Sydney }, // 0x2a09ae58 -> 0x4d1e9776
  { kAtcZoneIdJamaica, kAtcZoneIdAmerica_Jamaica }, // 0x2e44fdab -> 0x565dad6c
  { kAtcZoneIdEtc_Universal, kAtcZoneIdEtc_UTC }, // 0x2f8cb9a9 -> 0xd8e31abc
  { kAtcZoneIdAfrica_Djibouti, kAtcZoneIdAfrica_Nairobi }, // 0x30ea01d4 -> 0xa87ab57e
  { kAtcZoneIdAfrica_Gaborone, kAtcZoneIdAfrica_Maputo }, // 0x317c0aa7 -> 0x8e6ca1f0
  { kAtcZoneIdAsia_Calcutta, kAtcZoneIdAsia_Kolkata }, // 0x328a44c3 -> 0x72c06cd9
  { kAtcZoneIdAsia_Istanbul, kAtcZoneIdEurope_Istanbul }, // 0x382e7894 -> 0x9e09d6e6
  { kAtcZoneIdAsia_Ulan_Bator, kAtcZoneIdAsia_Ulaanbaatar }, // 0x394db4d9 -> 0x30f0cc4e
  { kAtcZoneIdAfrica_Brazzaville, kAtcZoneIdAfrica_Lagos }, // 0x39cda760 -> 0x789bb5d0
  { kAtcZoneIdAfrica_Porto_Novo, kAtcZoneIdAfrica_Lagos }, // 0x3d1bf95d -> 0x789bb5d0
  { kAtcZoneIdAmerica_Marigot, kAtcZoneIdAmerica_Puerto_Rico }, // 0x3dab3a59 -> 0x6752ca31
  { kAtcZoneIdEurope_Guernsey, kAtcZoneIdEurope_London }, // 0x3db12c16 -> 0x5c6a84ae
  { kAtcZoneIdAfrica_Nouakchott, kAtcZoneIdAfrica_Abidjan }, // 0x3dc49dba -> 0xc21305a3
  { kAtcZoneIdAmerica_Louisville, kAtcZoneIdAmerica_Kentucky_Louisville }, // 0x3dcb47ee -> 0x1a21024b
  { kAtcZoneIdCanada_Pacific, kAtcZoneIdAmerica_Vancouver }, // 0x40fa3c7b -> 0x2c6f6b1f
  { kAtcZoneIdIndian_Kerguelen, kAtcZoneIdIndian_Maldives }, // 0x4351b389 -> 0x9869681c
  { kAtcZoneIdAtlantic_St_Helena, kAtcZoneIdAfrica_Abidjan }, // 0x451fc5f7 -> 0xc21305a3
  { kAtcZoneIdIndian_Mahe, kAtcZoneIdAsia_Dubai }, // 0x45e725e2 -> 0x14c79f77
  { kAtcZoneIdIndian_Comoro, kAtcZoneIdAfrica_Nairobi }, // 0x45f4deb6 -> 0xa87ab57e
  { kAtcZoneIdAmerica_Mendoza, kAtcZoneIdAmerica_Argentina_Mendoza }, // 0x46b4e054 -> 0xa9f72d5c
  { kAtcZoneIdNZ_CHAT, kAtcZoneIdPacific_Chatham }, // 0x4d42afda -> 0x2f0de999
  { kAtcZoneIdUS_Arizona, kAtcZoneIdAmerica_Phoenix }, // 0x4ec52670 -> 0x34b5af01
  { kAtcZoneIdAntarctica_Vostok, kAtcZoneIdAsia_Urumqi }, // 0x4f966fd4 -> 0xd5379735
  { kAtcZoneIdUS_Aleutian, kAtcZoneIdAmerica_Adak }, // 0x4fe013ef -> 0x97fe49d7
  { kAtcZoneIdAmerica_Catamarca, kAtcZoneIdAmerica_Argentina_Catamarca }, // 0x5036e963 -> 0x8d40986b
  { kAtcZoneIdAsia_Kashgar, kAtcZoneIdAsia_Urumqi }, // 0x52955193 -> 0xd5379735
  { kAtcZoneIdCanada_Atlantic, kAtcZoneIdAmerica_Halifax }, // 0x536b119c -> 0xbc5b7183
  { kAtcZoneIdUS_Samoa, kAtcZoneIdPacific_Pago_Pago }, // 0x566821cd -> 0x603aebd0
  { kAtcZoneIdHongkong, kAtcZoneIdAsia_Hong_Kong }, // 0x56d36560 -> 0x577f28ac
  { kAtcZoneIdEurope_Jersey, kAtcZoneIdEurope_London }, // 0x570dae76 -> 0x5c6a84ae
  { kAtcZoneIdAntarctica_DumontDUrville, kAtcZoneIdPacific_Port_Moresby }, // 0x5a3c656c -> 0xa7ba7f68
  { kAtcZoneIdAtlantic_Jan_Mayen, kAtcZoneIdEurope_Berlin }, // 0x5a7535b6 -> 0x44644c20
  { kAtcZoneIdUS_Eastern, kAtcZoneIdAmerica_New_York }, // 0x5bb7e78e -> 0x1e2a7654
  { kAtcZoneIdEurope_Stockholm, kAtcZoneIdEurope_Berlin }, // 0x5bf6fbb8 -> 0x44644c20
  { kAtcZoneIdAmerica_Cordoba, kAtcZoneIdAmerica_Argentina_Cordoba }, // 0x5c8a7600 -> 0xbfccc308
  { kAtcZoneIdAsia_Ujung_Pandang, kAtcZoneIdAsia_Makassar }, // 0x5d001eb3 -> 0x6aa21c85
  { kAtcZoneIdAfrica_Mbabane, kAtcZoneIdAfrica_Johannesburg }, // 0x5d3bdd40 -> 0xd5d157a0
  { kAtcZoneIdEurope_Monaco, kAtcZoneIdEurope_Paris }, // 0x5ebf9f01 -> 0xfb4bc2a3
  { kAtcZoneIdPacific_Enderbury, kAtcZoneIdPacific_Kanton }, // 0x61599a93 -> 0xdd512f0e
  { kAtcZoneIdCanada_Central, kAtcZoneIdAmerica_Winnipeg }, // 0x626710f5 -> 0x8c7dafc7
  { kAtcZoneIdAmerica_Creston, kAtcZoneIdAmerica_Phoenix }, // 0x62a70204 -> 0x34b5af01
  { kAtcZoneIdBrazil_Acre, kAtcZoneIdAmerica_Rio_Branco }, // 0x66934f93 -> 0x9d352764
  { kAtcZoneIdBrazil_East, kAtcZoneIdAmerica_Sao_Paulo }, // 0x669578c5 -> 0x1063bfc9
  { kAtcZoneIdAfrica_Kinshasa, kAtcZoneIdAfrica_Lagos }, // 0x6695d70c -> 0x789bb5d0
  { kAtcZoneIdBrazil_West, kAtcZoneIdAmerica_Manaus }, // 0x669f689b -> 0xac86bf8b
  { kAtcZoneIdAfrica_Mogadishu, kAtcZoneIdAfrica_Nairobi }, // 0x66bc159b -> 0xa87ab57e
  { kAtcZoneIdUS_Indiana_Starke, kAtcZoneIdAmerica_Indiana_Knox }, // 0x67977be7 -> 0x6554adc9
  { kAtcZoneIdAmerica_Buenos_Aires, kAtcZoneIdAmerica_Argentina_Buenos_Aires }, // 0x67d79a05 -> 0xd43b4c0d
  { kAtcZoneIdAfrica_Freetown, kAtcZoneIdAfrica_Abidjan }, // 0x6823dd64 -> 0xc21305a3
  { kAtcZoneIdIndian_Christmas, kAtcZoneIdAsia_Bangkok }, // 0x68c207d5 -> 0x9d6e3aaf
  { kAtcZoneIdAmerica_Indianapolis, kAtcZoneIdAmerica_Indiana_Indianapolis }, // 0x6a009ae1 -> 0x28a669a4
  { kAtcZoneIdEurope_Sarajevo, kAtcZoneIdEurope_Belgrade }, // 0x6a576c3f -> 0xe0532b3a
  { kAtcZoneIdAmerica_Curacao, kAtcZoneIdAmerica_Puerto_Rico }, // 0x6a879184 -> 0x6752ca31
  { kAtcZoneIdAmerica_Lower_Princes, kAtcZoneIdAmerica_Puerto_Rico }, // 0x6ae45b62 -> 0x6752ca31
  { kAtcZoneIdEurope_Skopje, kAtcZoneIdEurope_Belgrade }, // 0x6c76fdd0 -> 0xe0532b3a
  { kAtcZoneIdAsia_Rangoon, kAtcZoneIdAsia_Yangon }, // 0x6d1217c6 -> 0xdd54a8be
  { kAtcZoneIdUS_East_Indiana, kAtcZoneIdAmerica_Indiana_Indianapolis }, // 0x6dcf558a -> 0x28a669a4
  { kAtcZoneIdAmerica_Blanc_Sablon, kAtcZoneIdAmerica_Puerto_Rico }, // 0x6e299892 -> 0x6752ca31
  { kAtcZoneIdUS_Mountain, kAtcZoneIdAmerica_Denver }, // 0x6eb88247 -> 0x97d10b2a
  { kAtcZoneIdAntarctica_McMurdo, kAtcZoneIdPacific_Auckland }, // 0x6eeb5585 -> 0x25062f86
  { kAtcZoneIdAfrica_Lubumbashi, kAtcZoneIdAfrica_Maputo }, // 0x6fd88566 -> 0x8e6ca1f0
  { kAtcZoneIdIndian_Reunion, kAtcZoneIdAsia_Dubai }, // 0x7076c047 -> 0x14c79f77
  { kAtcZoneIdAfrica_Asmara, kAtcZoneIdAfrica_Nairobi }, // 0x73b278ef -> 0xa87ab57e
  { kAtcZoneIdAfrica_Asmera, kAtcZoneIdAfrica_Nairobi }, // 0x73b289f3 -> 0xa87ab57e
  { kAtcZoneIdAfrica_Bamako, kAtcZoneIdAfrica_Abidjan }, // 0x74c1e7a5 -> 0xc21305a3
  { kAtcZoneIdAfrica_Bangui, kAtcZoneIdAfrica_Lagos }, // 0x74c28ed0 -> 0x789bb5d0
  { kAtcZoneIdAfrica_Banjul, kAtcZoneIdAfrica_Abidjan }, // 0x74c29b96 -> 0xc21305a3
  { kAtcZoneIdEurope_Nicosia, kAtcZoneIdAsia_Nicosia }, // 0x74efab8a -> 0x4b0fcf78
  { kAtcZoneIdUS_Michigan, kAtcZoneIdAmerica_Detroit }, // 0x766bb7bc -> 0x925cfbc1
  { kAtcZoneIdCanada_Saskatchewan, kAtcZoneIdAmerica_Regina }, // 0x77311f49 -> 0xb875371c
  { kAtcZoneIdAfrica_Accra, kAtcZoneIdAfrica_Abidjan }, // 0x77d5b054 -> 0xc21305a3
  { kAtcZoneIdAfrica_Dakar, kAtcZoneIdAfrica_Abidjan }, // 0x780b00fd -> 0xc21305a3
  { kAtcZoneIdCanada_Yukon, kAtcZoneIdAmerica_Whitehorse }, // 0x78dd35c2 -> 0x54e0e3e8
  { kAtcZoneIdAmerica_Tortola, kAtcZoneIdAmerica_Puerto_Rico }, // 0x7931462b -> 0x6752ca31
  { kAtcZoneIdAfrica_Douala, kAtcZoneIdAfrica_Lagos }, // 0x7a6df310 -> 0x789bb5d0
  { kAtcZoneIdAfrica_Conakry, kAtcZoneIdAfrica_Abidjan }, // 0x7ab36b31 -> 0xc21305a3
  { kAtcZoneIdAmerica_Ensenada, kAtcZoneIdAmerica_Tijuana }, // 0x7bc95445 -> 0x6aa1df72
  { kAtcZoneIdEurope_Zagreb, kAtcZoneIdEurope_Belgrade }, // 0x7c11c9ff -> 0xe0532b3a
  { kAtcZoneIdCuba, kAtcZoneIdAmerica_Havana }, // 0x7c83cba0 -> 0xa0e15675
  { kAtcZoneIdEire, kAtcZoneIdEurope_Dublin }, // 0x7c84b36a -> 0x4a275f62
  { kAtcZoneIdGMT0, kAtcZoneIdEtc_GMT }, // 0x7c8550fd -> 0xd8e2de58
  { kAtcZoneIdIran, kAtcZoneIdAsia_Tehran }, // 0x7c87090f -> 0xd1f02254
  { kAtcZoneIdW_SU, kAtcZoneIdEurope_Moscow }, // 0x7c8d8ef1 -> 0x5ec266fc
  { kAtcZoneIdZulu, kAtcZoneIdEtc_UTC }, // 0x7c9069b5 -> 0xd8e31abc
  { kAtcZoneIdChile_Continental, kAtcZoneIdAmerica_Santiago }, // 0x7e2bdb18 -> 0x7410c9bc
  { kAtcZoneIdAmerica_Fort_Wayne, kAtcZoneIdAmerica_Indiana_Indianapolis }, // 0x7eaaaf24 -> 0x28a669a4
  { kAtcZoneIdAmerica_Atikokan, kAtcZoneIdAmerica_Panama }, // 0x81b92098 -> 0xb3863854
  { kAtcZoneIdAfrica_Harare, kAtcZoneIdAfrica_Maputo }, // 0x82c39a2d -> 0x8e6ca1f0
  { kAtcZoneIdAmerica_Shiprock, kAtcZoneIdAmerica_Denver }, // 0x82fb7049 -> 0x97d10b2a
  { kAtcZoneIdAmerica_St_Vincent, kAtcZoneIdAmerica_Puerto_Rico }, // 0x8460e523 -> 0x6752ca31
  { kAtcZoneIdAsia_Vientiane, kAtcZoneIdAsia_Bangkok }, // 0x89d68d75 -> 0x9d6e3aaf
  { kAtcZoneIdPacific_Chuuk, kAtcZoneIdPacific_Port_Moresby }, // 0x8a090b23 -> 0xa7ba7f68
  { kAtcZoneIdAfrica_Kigali, kAtcZoneIdAfrica_Maputo }, // 0x8a4dcf2b -> 0x8e6ca1f0
  { kAtcZoneIdAustralia_ACT, kAtcZoneIdAustralia_Sydney }, // 0x8a970eb2 -> 0x4d1e9776
  { kAtcZoneIdAustralia_LHI, kAtcZoneIdAustralia_Lord_Howe }, // 0x8a973e17 -> 0xa748b67d
  { kAtcZoneIdAustralia_NSW, kAtcZoneIdAustralia_Sydney }, // 0x8a974812 -> 0x4d1e9776
  { kAtcZoneIdPacific_Samoa, kAtcZoneIdPacific_Pago_Pago }, // 0x8b2699b4 -> 0x603aebd0
  { kAtcZoneIdAfrica_Luanda, kAtcZoneIdAfrica_Lagos }, // 0x8d7909cf -> 0x789bb5d0
  { kAtcZoneIdAfrica_Lusaka, kAtcZoneIdAfrica_Maputo }, // 0x8d82b23b -> 0x8e6ca1f0
  { kAtcZoneIdAustralia_North, kAtcZoneIdAustralia_Darwin }, // 0x8d997165 -> 0x2876bdff
  { kAtcZoneIdAustralia_South, kAtcZoneIdAustralia_Adelaide }, // 0x8df3f8ad -> 0x2428e8a3
  { kAtcZoneIdAfrica_Malabo, kAtcZoneIdAfrica_Lagos }, // 0x8e6a1906 -> 0x789bb5d0
  { kAtcZoneIdAfrica_Maseru, kAtcZoneIdAfrica_Johannesburg }, // 0x8e6e02c7 -> 0xd5d157a0
  { kAtcZoneIdAmerica_Godthab, kAtcZoneIdAmerica_Nuuk }, // 0x8f7eba1f -> 0x9805b5a9
  { kAtcZoneIdAustralia_Yancowinna, kAtcZoneIdAustralia_Broken_Hill }, // 0x90bac131 -> 0xb06eada3
  { kAtcZoneIdAfrica_Niamey, kAtcZoneIdAfrica_Lagos }, // 0x914a30fd -> 0x789bb5d0
  { kAtcZoneIdMexico_General, kAtcZoneIdAmerica_Mexico_City }, // 0x93711d57 -> 0xd0d93f43
  { kAtcZoneIdAmerica_Cayman, kAtcZoneIdAmerica_Panama }, // 0x953961df -> 0xb3863854
  { kAtcZoneIdAmerica_Grenada, kAtcZoneIdAmerica_Puerto_Rico }, // 0x968ce4d8 -> 0x6752ca31
  { kAtcZoneIdAmerica_Aruba, kAtcZoneIdAmerica_Puerto_Rico }, // 0x97cf8651 -> 0x6752ca31
  { kAtcZoneIdAmerica_Atka, kAtcZoneIdAmerica_Adak }, // 0x97fe8f27 -> 0x97fe49d7
  { kAtcZoneIdAmerica_Jujuy, kAtcZoneIdAmerica_Argentina_Jujuy }, // 0x9873dbbd -> 0x5f2f46c5
  { kAtcZoneIdBrazil_DeNoronha, kAtcZoneIdAmerica_Noronha }, // 0x9b4cb496 -> 0xab5116fb
  { kAtcZoneIdAsia_Bahrain, kAtcZoneIdAsia_Qatar }, // 0x9d078487 -> 0x15a8330b
  { kAtcZoneIdEtc_GMT_PLUS_0, kAtcZoneIdEtc_GMT }, // 0x9d13da13 -> 0xd8e2de58
  { kAtcZoneIdEtc_GMT_0, kAtcZoneIdEtc_GMT }, // 0x9d13da55 -> 0xd8e2de58
  { kAtcZoneIdIndian_Antananarivo, kAtcZoneIdAfrica_Nairobi }, // 0x9ebf5289 -> 0xa87ab57e
  { kAtcZoneIdAfrica_Dar_es_Salaam, kAtcZoneIdAfrica_Nairobi }, // 0xa04c47b6 -> 0xa87ab57e
  { kAtcZoneIdEurope_Kiev, kAtcZoneIdEurope_Kyiv }, // 0xa2c19eb3 -> 0xa2c1e347
  { kAtcZoneIdEurope_Oslo, kAtcZoneIdEurope_Berlin }, // 0xa2c3fba1 -> 0x44644c20
  { kAtcZoneIdAsia_Katmandu, kAtcZoneIdAsia_Kathmandu }, // 0xa7ec12c7 -> 0x9a96ce6f
  { kAtcZoneIdSingapore, kAtcZoneIdAsia_Singapore }, // 0xa8598c8d -> 0xcf8581fa
  { kAtcZoneIdAsia_Brunei, kAtcZoneIdAsia_Kuching }, // 0xa8e595f7 -> 0x801b003b
  { kAtcZoneIdUS_Pacific, kAtcZoneIdAmerica_Los_Angeles }, // 0xa950f6ab -> 0xb7f7e8f2
  { kAtcZoneIdAmerica_Coral_Harbour, kAtcZoneIdAmerica_Panama }, // 0xabcb7569 -> 0xb3863854
  { kAtcZoneIdAmerica_Nassau, kAtcZoneIdAmerica_Toronto }, // 0xaedef011 -> 0x792e851b
  { kAtcZoneIdAmerica_Anguilla, kAtcZoneIdAmerica_Puerto_Rico }, // 0xafe31333 -> 0x6752ca31
  { kAtcZoneIdEurope_Uzhgorod, kAtcZoneIdEurope_Kyiv }, // 0xb066f5d6 -> 0xa2c1e347
  { kAtcZoneIdChile_EasterIsland, kAtcZoneIdPacific_Easter }, // 0xb0982af8 -> 0xcf54f7e7
  { kAtcZoneIdPacific_Johnston, kAtcZoneIdPacific_Honolulu }, // 0xb15d7b36 -> 0xe6e70af9
  { kAtcZoneIdAfrica_Timbuktu, kAtcZoneIdAfrica_Abidjan }, // 0xb164d56f -> 0xc21305a3
  { kAtcZoneIdAmerica_St_Thomas, kAtcZoneIdAmerica_Puerto_Rico }, // 0xb1b3d778 -> 0x6752ca31
  { kAtcZoneIdCanada_Newfoundland, kAtcZoneIdAmerica_St_Johns }, // 0xb396e991 -> 0x04b14e6e
  { kAtcZoneIdAsia_Harbin, kAtcZoneIdAsia_Shanghai }, // 0xb5af1186 -> 0xf895a7f5
  { kAtcZoneIdIsrael, kAtcZoneIdAsia_Jerusalem }, // 0xba88c9e5 -> 0x5becd23a
  { kAtcZoneIdPacific_Yap, kAtcZoneIdPacific_Port_Moresby }, // 0xbb40138d -> 0xa7ba7f68
  { kAtcZoneIdEurope_Ljubljana, kAtcZoneIdEurope_Belgrade }, // 0xbd98cdb7 -> 0xe0532b3a
  { kAtcZoneIdAsia_Kuwait, kAtcZoneIdAsia_Riyadh }, // 0xbe1b2f27 -> 0xcd973d93
  { kAtcZoneIdEurope_Tiraspol, kAtcZoneIdEurope_Chisinau }, // 0xbe704472 -> 0xad58aa18
  { kAtcZoneIdAmerica_Antigua, kAtcZoneIdAmerica_Puerto_Rico }, // 0xc067a32f -> 0x6752ca31
  { kAtcZoneIdEurope_Busingen, kAtcZoneIdEurope_Zurich }, // 0xc06d2cdf -> 0x7d8195b9
  { kAtcZoneIdAfrica_Kampala, kAtcZoneIdAfrica_Nairobi }, // 0xc1d30e31 -> 0xa87ab57e
  { kAtcZoneIdAmerica_Knox_IN, kAtcZoneIdAmerica_Indiana_Knox }, // 0xc1db9a1c -> 0x6554adc9
  { kAtcZoneIdAmerica_Virgin, kAtcZoneIdAmerica_Puerto_Rico }, // 0xc2183ab5 -> 0x6752ca31
  { kAtcZoneIdAsia_Phnom_Penh, kAtcZoneIdAsia_Bangkok }, // 0xc224945e -> 0x9d6e3aaf
  { kAtcZoneIdAsia_Muscat, kAtcZoneIdAsia_Dubai }, // 0xc2c3565f -> 0x14c79f77
  { kAtcZoneIdPortugal, kAtcZoneIdEurope_Lisbon }, // 0xc3274593 -> 0x5c00a70b
  { kAtcZoneIdNavajo, kAtcZoneIdAmerica_Denver }, // 0xc4ef0e24 -> 0x97d10b2a
  { kAtcZoneIdAsia_Chungking, kAtcZoneIdAsia_Shanghai }, // 0xc7121dd0 -> 0xf895a7f5
  { kAtcZoneIdGreenwich, kAtcZoneIdEtc_GMT }, // 0xc84d4221 -> 0xd8e2de58
  { kAtcZoneIdPoland, kAtcZoneIdEurope_Warsaw }, // 0xca913b23 -> 0x75185c19
  { kAtcZoneIdUS_Central, kAtcZoneIdAmerica_Chicago }, // 0xcabdcb25 -> 0x4b92b5d4
  { kAtcZoneIdEurope_Vatican, kAtcZoneIdEurope_Rome }, // 0xcb485dca -> 0xa2c58fd7
  { kAtcZoneIdAmerica_Porto_Acre, kAtcZoneIdAmerica_Rio_Branco }, // 0xcce5bf54 -> 0x9d352764
  { kAtcZoneIdAmerica_Guadeloupe, kAtcZoneIdAmerica_Puerto_Rico }, // 0xcd1f8a31 -> 0x6752ca31
  { kAtcZoneIdAntarctica_South_Pole, kAtcZoneIdPacific_Auckland }, // 0xcd96b290 -> 0x25062f86
  { kAtcZoneIdAmerica_Dominica, kAtcZoneIdAmerica_Puerto_Rico }, // 0xcecb4c4a -> 0x6752ca31
  { kAtcZoneIdEurope_San_Marino, kAtcZoneIdEurope_Rome }, // 0xcef7724b -> 0xa2c58fd7
  { kAtcZoneIdAsia_Saigon, kAtcZoneIdAsia_Ho_Chi_Minh }, // 0xcf52f713 -> 0x20f2d127
  { kAtcZoneIdEurope_Belfast, kAtcZoneIdEurope_London }, // 0xd07dd1e5 -> 0x5c6a84ae
  { kAtcZoneIdUniversal, kAtcZoneIdEtc_UTC }, // 0xd0ff523e -> 0xd8e31abc
  { kAtcZoneIdAsia_Thimbu, kAtcZoneIdAsia_Thimphu }, // 0xd226e31b -> 0x170380d1
  { kAtcZoneIdArctic_Longyearbyen, kAtcZoneIdEurope_Berlin }, // 0xd23e7859 -> 0x44644c20
  { kAtcZoneIdAustralia_Queensland, kAtcZoneIdAustralia_Brisbane }, // 0xd326ed0a -> 0x4fedc9c0
  { kAtcZoneIdTurkey, kAtcZoneIdEurope_Istanbul }, // 0xd455e469 -> 0x9e09d6e6
  { kAtcZoneIdAfrica_Lome, kAtcZoneIdAfrica_Abidjan }, // 0xd51c3a07 -> 0xc21305a3
  { kAtcZoneIdAmerica_Port_of_Spain, kAtcZoneIdAmerica_Puerto_Rico }, // 0xd8b28d59 -> 0x6752ca31
  { kAtcZoneIdEtc_UCT, kAtcZoneIdEtc_UTC }, // 0xd8e3189c -> 0xd8e31abc
  { kAtcZoneIdEurope_Bratislava, kAtcZoneIdEurope_Prague }, // 0xda493bed -> 0x65ee5d48
  { kAtcZoneIdPacific_Funafuti, kAtcZoneIdPacific_Tarawa }, // 0xdb402d65 -> 0xf2517e63
  { kAtcZoneIdAustralia_West, kAtcZoneIdAustralia_Perth }, // 0xdd858a5d -> 0x8db8269d
  { kAtcZoneIdAmerica_Rosario, kAtcZoneIdAmerica_Argentina_Cordoba }, // 0xdf448665 -> 0xbfccc308
  { kAtcZoneIdAfrica_Blantyre, kAtcZoneIdAfrica_Maputo }, // 0xe08d813b -> 0x8e6ca1f0
  { kAtcZoneIdEurope_Copenhagen, kAtcZoneIdEurope_Berlin }, // 0xe0ed30bc -> 0x44644c20
  { kAtcZoneIdPacific_Majuro, kAtcZoneIdPacific_Tarawa }, // 0xe1f95371 -> 0xf2517e63
  { kAtcZoneIdPacific_Midway, kAtcZoneIdPacific_Pago_Pago }, // 0xe286d38e -> 0x603aebd0
  { kAtcZoneIdAntarctica_Syowa, kAtcZoneIdAsia_Riyadh }, // 0xe330c7e1 -> 0xcd973d93
  { kAtcZoneIdIceland, kAtcZoneIdAfrica_Abidjan }, // 0xe56a35b5 -> 0xc21305a3
  { kAtcZoneIdIndian_Mayotte, kAtcZoneIdAfrica_Nairobi }, // 0xe6880bca -> 0xa87ab57e
  { kAtcZoneIdAustralia_Tasmania, kAtcZoneIdAustralia_Hobart }, // 0xe6d76648 -> 0x32bf951a
  { kAtcZoneIdAmerica_Kralendijk, kAtcZoneIdAmerica_Puerto_Rico }, // 0xe7c456c5 -> 0x6752ca31
  { kAtcZoneIdPacific_Ponape, kAtcZoneIdPacific_Guadalcanal }, // 0xe9f80086 -> 0xf4dd25f0
  { kAtcZoneIdEurope_Zaporozhye, kAtcZoneIdEurope_Kyiv }, // 0xeab9767f -> 0xa2c1e347
  { kAtcZoneIdEurope_Isle_of_Man, kAtcZoneIdEurope_London }, // 0xeaf84580 -> 0x5c6a84ae
  { kAtcZoneIdPacific_Saipan, kAtcZoneIdPacific_Guam }, // 0xeff7a35f -> 0x2338f9ed
  { kAtcZoneIdCanada_Eastern, kAtcZoneIdAmerica_Toronto }, // 0xf3612d5e -> 0x792e851b
  { kAtcZoneIdEtc_GMT0, kAtcZoneIdEtc_GMT }, // 0xf53ea988 -> 0xd8e2de58
  { kAtcZoneIdEtc_Zulu, kAtcZoneIdEtc_UTC }, // 0xf549c240 -> 0xd8e31abc
  { kAtcZoneIdAsia_Chongqing, kAtcZoneIdAsia_Shanghai }, // 0xf937fb90 -> 0xf895a7f5
  { kAtcZoneIdPacific_Wallis, kAtcZoneIdPacific_Tarawa }, // 0xf94ddb0f -> 0xf2517e63
  { kAtcZoneIdUS_Alaska, kAtcZoneIdAmerica_Anchorage }, // 0xfa300bc9 -> 0x5a79260e
  { kAtcZoneIdGB_Eire, kAtcZoneIdEurope_London }, // 0xfa70e300 -> 0x5c6a84ae
  { kAtcZoneIdCanada_Mountain, kAtcZoneIdAmerica_Edmonton }, // 0xfb8a8217 -> 0x6cb9484a
  { kAtcZoneIdEurope_Vaduz, kAtcZoneIdEurope_Zurich }, // 0xfbb81bae -> 0x7d8195b9
  { kAtcZoneIdMexico_BajaNorte, kAtcZoneIdAmerica_Tijuana }, // 0xfcf7150f -> 0x6aa1df72
  { kAtcZoneIdAmerica_Santa_Isabel, kAtcZoneIdAmerica_Tijuana }, // 0xfd18a56c -> 0x6aa1df72

};
