// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/dev/tz
//     --output_dir /home/brian/src/AceTimeC/src/ace_time_c/zonedb
//     --tz_version 2022g
//     --action zonedb
//     --language c
//     --scope extended
//     --generate_int16_years
//     --start_year 2000
//     --until_year 10000
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2022g
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDBX_ZONE_POLICIES_H
#define ACE_TIME_C_ZONEDBX_ZONE_POLICIES_H

#include "../zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

//---------------------------------------------------------------------------
// Supported zone policies: 83
//---------------------------------------------------------------------------

extern const AtcZonePolicy kAtcPolicyAN;
extern const AtcZonePolicy kAtcPolicyAQ;
extern const AtcZonePolicy kAtcPolicyAS;
extern const AtcZonePolicy kAtcPolicyAT;
extern const AtcZonePolicy kAtcPolicyAV;
extern const AtcZonePolicy kAtcPolicyAW;
extern const AtcZonePolicy kAtcPolicyArg;
extern const AtcZonePolicy kAtcPolicyArmenia;
extern const AtcZonePolicy kAtcPolicyAus;
extern const AtcZonePolicy kAtcPolicyAzer;
extern const AtcZonePolicy kAtcPolicyBarb;
extern const AtcZonePolicy kAtcPolicyBelize;
extern const AtcZonePolicy kAtcPolicyBrazil;
extern const AtcZonePolicy kAtcPolicyC_Eur;
extern const AtcZonePolicy kAtcPolicyCO;
extern const AtcZonePolicy kAtcPolicyCR;
extern const AtcZonePolicy kAtcPolicyCanada;
extern const AtcZonePolicy kAtcPolicyChatham;
extern const AtcZonePolicy kAtcPolicyChile;
extern const AtcZonePolicy kAtcPolicyCook;
extern const AtcZonePolicy kAtcPolicyCuba;
extern const AtcZonePolicy kAtcPolicyDhaka;
extern const AtcZonePolicy kAtcPolicyE_EurAsia;
extern const AtcZonePolicy kAtcPolicyEU;
extern const AtcZonePolicy kAtcPolicyEUAsia;
extern const AtcZonePolicy kAtcPolicyEcuador;
extern const AtcZonePolicy kAtcPolicyEgypt;
extern const AtcZonePolicy kAtcPolicyEire;
extern const AtcZonePolicy kAtcPolicyFalk;
extern const AtcZonePolicy kAtcPolicyFiji;
extern const AtcZonePolicy kAtcPolicyGuam;
extern const AtcZonePolicy kAtcPolicyGuat;
extern const AtcZonePolicy kAtcPolicyHK;
extern const AtcZonePolicy kAtcPolicyHaiti;
extern const AtcZonePolicy kAtcPolicyHoliday;
extern const AtcZonePolicy kAtcPolicyHond;
extern const AtcZonePolicy kAtcPolicyIran;
extern const AtcZonePolicy kAtcPolicyIraq;
extern const AtcZonePolicy kAtcPolicyJapan;
extern const AtcZonePolicy kAtcPolicyJordan;
extern const AtcZonePolicy kAtcPolicyKyrgyz;
extern const AtcZonePolicy kAtcPolicyLH;
extern const AtcZonePolicy kAtcPolicyLebanon;
extern const AtcZonePolicy kAtcPolicyLibya;
extern const AtcZonePolicy kAtcPolicyMacau;
extern const AtcZonePolicy kAtcPolicyMauritius;
extern const AtcZonePolicy kAtcPolicyMexico;
extern const AtcZonePolicy kAtcPolicyMoldova;
extern const AtcZonePolicy kAtcPolicyMoncton;
extern const AtcZonePolicy kAtcPolicyMongol;
extern const AtcZonePolicy kAtcPolicyMorocco;
extern const AtcZonePolicy kAtcPolicyNC;
extern const AtcZonePolicy kAtcPolicyNT_YK;
extern const AtcZonePolicy kAtcPolicyNZ;
extern const AtcZonePolicy kAtcPolicyNamibia;
extern const AtcZonePolicy kAtcPolicyNic;
extern const AtcZonePolicy kAtcPolicyPRC;
extern const AtcZonePolicy kAtcPolicyPakistan;
extern const AtcZonePolicy kAtcPolicyPalestine;
extern const AtcZonePolicy kAtcPolicyPara;
extern const AtcZonePolicy kAtcPolicyPeru;
extern const AtcZonePolicy kAtcPolicyPhil;
extern const AtcZonePolicy kAtcPolicyROK;
extern const AtcZonePolicy kAtcPolicyRussia;
extern const AtcZonePolicy kAtcPolicyRussiaAsia;
extern const AtcZonePolicy kAtcPolicySA;
extern const AtcZonePolicy kAtcPolicySalv;
extern const AtcZonePolicy kAtcPolicySanLuis;
extern const AtcZonePolicy kAtcPolicyStJohns;
extern const AtcZonePolicy kAtcPolicySudan;
extern const AtcZonePolicy kAtcPolicySyria;
extern const AtcZonePolicy kAtcPolicyTaiwan;
extern const AtcZonePolicy kAtcPolicyThule;
extern const AtcZonePolicy kAtcPolicyTonga;
extern const AtcZonePolicy kAtcPolicyTroll;
extern const AtcZonePolicy kAtcPolicyTunisia;
extern const AtcZonePolicy kAtcPolicyTurkey;
extern const AtcZonePolicy kAtcPolicyUS;
extern const AtcZonePolicy kAtcPolicyUruguay;
extern const AtcZonePolicy kAtcPolicyVanuatu;
extern const AtcZonePolicy kAtcPolicyWS;
extern const AtcZonePolicy kAtcPolicyWinn;
extern const AtcZonePolicy kAtcPolicyZion;


//---------------------------------------------------------------------------
// Unsupported zone policies: 51
//---------------------------------------------------------------------------

// Albania {unused}
// Algeria {unused}
// Austria {unused}
// Belgium {unused}
// Bermuda {unused}
// Bulg {unused}
// CA {unused}
// Chicago {unused}
// Cyprus {unused}
// Czech {unused}
// DR {unused}
// Denver {unused}
// Detroit {unused}
// E-Eur {unused}
// Edm {unused}
// EgyptAsia {unused}
// Finland {unused}
// France {unused}
// GB-Eire {unused}
// Germany {unused}
// Greece {unused}
// Halifax {unused}
// Hungary {unused}
// Indianapolis {unused}
// Italy {unused}
// Latvia {unused}
// Louisville {unused}
// Malta {unused}
// Marengo {unused}
// Menominee {unused}
// NBorneo {unused}
// NYC {unused}
// Perry {unused}
// Pike {unused}
// Poland {unused}
// Port {unused}
// Pulaski {unused}
// Regina {unused}
// Romania {unused}
// Shang {unused}
// SovietZone {unused}
// Spain {unused}
// SpainAfrica {unused}
// Starke {unused}
// Swift {unused}
// Swiss {unused}
// Toronto {unused}
// Vanc {unused}
// Vincennes {unused}
// W-Eur {unused}
// Yukon {unused}


//---------------------------------------------------------------------------
// Notable zone policies: 15
//---------------------------------------------------------------------------

// Armenia {Added anchor rule at year 0}
// Belize {LETTER 'CST' not single character}
// Dhaka {Added anchor rule at year 0}
// Eire {SAVE (delta_offset) '-1:00' different from 1:00}
// LH {SAVE (delta_offset) '0:30' different from 1:00}
// Moncton {AT '0:01' not on 15-minute boundary}
// Morocco {SAVE (delta_offset) '-1:00' different from 1:00}
// Namibia {
//   LETTER 'CAT' not single character,
//   LETTER 'WAT' not single character,
//   SAVE (delta_offset) '-1:00' different from 1:00,
// }
// Pakistan {Added anchor rule at year 0}
// Palestine {
//   AT '0:01' not on 15-minute boundary,
//   Added anchor rule at year 0,
// }
// SanLuis {Added anchor rule at year 0}
// StJohns {
//   AT '0:01' not on 15-minute boundary,
//   LETTER 'DD' not single character,
//   SAVE (delta_offset) '2:00' different from 1:00,
// }
// Tonga {Added anchor rule at year 0}
// Troll {
//   Added anchor rule at year 0,
//   LETTER '+00' not single character,
//   LETTER '+02' not single character,
//   SAVE (delta_offset) '2:00' different from 1:00,
// }
// WS {Added anchor rule at year 0}


//---------------------------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif
