// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/dev/tz
//     --output_dir /home/brian/src/AceTimeC/src/ace_time_c/zonedb
//     --tz_version 2022a
//     --action zonedb
//     --language c
//     --scope extended
//     --start_year 2000
//     --until_year 2050
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2022a
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDBX_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDBX_ZONE_REGISTRY_H

#include "../zone_info.h"

// Zones
const uint16_t kAtcZoneRegistrySize = 377;
extern const struct AtcZoneInfo * const kAtcZoneRegistry[377];

// Zones and Links
const uint16_t kAtcZoneAndLinkRegistrySize = 594;
extern const struct AtcZoneInfo * const kAtcZoneAndLinkRegistry[594];

// Link Entries
const uint16_t kAtcLinkRegistrySize = 217;
extern const struct AtcLinkEntry kAtcLinkRegistry[217];

#endif
