// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedbtesting/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedbtesting
//     --tz_version 2025b
//     --actions zonedb
//     --language c
//     --scope complete
//     --db_namespace Testing
//     --start_year 2000
//     --until_year 2200
//     --nocompress
//     --include_list include_list.txt
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025b
//
// Supported Zones: 17 (16 zones, 1 links)
// Unsupported Zones: 580 (324 zones, 256 links)
//
// Requested Years: [2000,2200]
// Accurate Years: [2000,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1966,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1966,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 17
//   Eras: 22
//   Policies: 8
//   Rules: 201
//
// Memory (8-bits):
//   Context: 20
//   Rules: 2412
//   Policies: 24
//   Eras: 330
//   Zones: 208
//   Links: 13
//   Registry: 34
//   Formats: 37
//   Letters: 23
//   Fragments: 0
//   Names: 268 (original: 268)
//   TOTAL: 3369
//
// Memory (32-bits):
//   Context: 28
//   Rules: 2412
//   Policies: 64
//   Eras: 440
//   Zones: 384
//   Links: 24
//   Registry: 68
//   Formats: 37
//   Letters: 33
//   Fragments: 0
//   Names: 268 (original: 268)
//   TOTAL: 3758
//
// DO NOT EDIT

#include "zone_policies.h"

//---------------------------------------------------------------------------
// Policies: 8
// Rules: 201
//---------------------------------------------------------------------------

//---------------------------------------------------------------------------
// Policy name: Aus
// Rules: 1
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesAus[]  = {
  // Anchor: Rule    Aus    1943    1944    -    Mar    lastSun    2:00s    0    S
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyAus  = {
  kAtcZoneRulesAus /*rules*/,
  1 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: Canada
// Rules: 6
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesCanada[]  = {
  // Anchor: Rule    Canada    1974    2006    -    Oct    lastSun    2:00    0    S
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    Canada    1974    1986    -    Apr    lastSun    2:00    1:00    D
  {
    1974 /*from_year*/,
    1986 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    Canada    1974    2006    -    Oct    lastSun    2:00    0    S
  {
    1974 /*from_year*/,
    2006 /*to_year*/,
    10 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    Canada    1987    2006    -    Apr    Sun>=1    2:00    1:00    D
  {
    1987 /*from_year*/,
    2006 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    Canada    2007    max    -    Mar    Sun>=8    2:00    1:00    D
  {
    2007 /*from_year*/,
    32766 /*to_year*/,
    3 /*in_month*/,
    7 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    Canada    2007    max    -    Nov    Sun>=1    2:00    0    S
  {
    2007 /*from_year*/,
    32766 /*to_year*/,
    11 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyCanada  = {
  kAtcZoneRulesCanada /*rules*/,
  6 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: EU
// Rules: 4
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesEU[]  = {
  // Anchor: Rule    EU    1979    1995    -    Sep    lastSun     1:00u    0    -
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    EU    1979    1995    -    Sep    lastSun     1:00u    0    -
  {
    1979 /*from_year*/,
    1995 /*to_year*/,
    9 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    32 /*at_time_modifier (kAtcSuffixU + seconds=0)*/,
    240 /*at_time_code (3600/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    EU    1981    max    -    Mar    lastSun     1:00u    1:00    S
  {
    1981 /*from_year*/,
    32766 /*to_year*/,
    3 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    32 /*at_time_modifier (kAtcSuffixU + seconds=0)*/,
    240 /*at_time_code (3600/15)*/,
    60 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    EU    1996    max    -    Oct    lastSun     1:00u    0    -
  {
    1996 /*from_year*/,
    32766 /*to_year*/,
    10 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    32 /*at_time_modifier (kAtcSuffixU + seconds=0)*/,
    240 /*at_time_code (3600/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyEU  = {
  kAtcZoneRulesEU /*rules*/,
  4 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: Morocco
// Rules: 170
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesMorocco[]  = {
  // Anchor: Rule    Morocco    1978    only    -    Aug     4     0:00    0    -
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    1978    only    -    Aug     4     0:00    0    -
  {
    1978 /*from_year*/,
    1978 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    4 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2008    only    -    Jun     1     0:00    1:00    -
  {
    2008 /*from_year*/,
    2008 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2008    only    -    Sep     1     0:00    0    -
  {
    2008 /*from_year*/,
    2008 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2009    only    -    Jun     1     0:00    1:00    -
  {
    2009 /*from_year*/,
    2009 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2009    only    -    Aug    21     0:00    0    -
  {
    2009 /*from_year*/,
    2009 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    21 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2010    only    -    May     2     0:00    1:00    -
  {
    2010 /*from_year*/,
    2010 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2010    only    -    Aug     8     0:00    0    -
  {
    2010 /*from_year*/,
    2010 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2011    only    -    Apr     3     0:00    1:00    -
  {
    2011 /*from_year*/,
    2011 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    3 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2011    only    -    Jul    31     0:00    0    -
  {
    2011 /*from_year*/,
    2011 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    31 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2012    2013    -    Apr    lastSun     2:00    1:00    -
  {
    2012 /*from_year*/,
    2013 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2012    only    -    Jul    20     3:00    0    -
  {
    2012 /*from_year*/,
    2012 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    20 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2012    only    -    Aug    20     2:00    1:00    -
  {
    2012 /*from_year*/,
    2012 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    20 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2012    only    -    Sep    30     3:00    0    -
  {
    2012 /*from_year*/,
    2012 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    30 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2013    only    -    Jul     7     3:00    0    -
  {
    2013 /*from_year*/,
    2013 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    7 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2013    only    -    Aug    10     2:00    1:00    -
  {
    2013 /*from_year*/,
    2013 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2013    2018    -    Oct    lastSun     3:00    0    -
  {
    2013 /*from_year*/,
    2018 /*to_year*/,
    10 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2014    2018    -    Mar    lastSun     2:00    1:00    -
  {
    2014 /*from_year*/,
    2018 /*to_year*/,
    3 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2014    only    -    Jun    28     3:00    0    -
  {
    2014 /*from_year*/,
    2014 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2014    only    -    Aug     2     2:00    1:00    -
  {
    2014 /*from_year*/,
    2014 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2015    only    -    Jun    14     3:00    0    -
  {
    2015 /*from_year*/,
    2015 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2015    only    -    Jul    19     2:00    1:00    -
  {
    2015 /*from_year*/,
    2015 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2016    only    -    Jun     5     3:00    0    -
  {
    2016 /*from_year*/,
    2016 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2016    only    -    Jul    10     2:00    1:00    -
  {
    2016 /*from_year*/,
    2016 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2017    only    -    May    21     3:00    0    -
  {
    2017 /*from_year*/,
    2017 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    21 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2017    only    -    Jul     2     2:00    1:00    -
  {
    2017 /*from_year*/,
    2017 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2018    only    -    May    13     3:00    0    -
  {
    2018 /*from_year*/,
    2018 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    13 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2018    only    -    Jun    17     2:00    1:00    -
  {
    2018 /*from_year*/,
    2018 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    17 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2019    only    -    May     5     3:00    -1:00    -
  {
    2019 /*from_year*/,
    2019 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2019    only    -    Jun     9     2:00    0    -
  {
    2019 /*from_year*/,
    2019 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    9 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2020    only    -    Apr    19     3:00    -1:00    -
  {
    2020 /*from_year*/,
    2020 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2020    only    -    May    31     2:00    0    -
  {
    2020 /*from_year*/,
    2020 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    31 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2021    only    -    Apr    11     3:00    -1:00    -
  {
    2021 /*from_year*/,
    2021 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2021    only    -    May    16     2:00    0    -
  {
    2021 /*from_year*/,
    2021 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    16 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2022    only    -    Mar    27     3:00    -1:00    -
  {
    2022 /*from_year*/,
    2022 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    27 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2022    only    -    May     8     2:00    0    -
  {
    2022 /*from_year*/,
    2022 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2023    only    -    Mar    19     3:00    -1:00    -
  {
    2023 /*from_year*/,
    2023 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2023    only    -    Apr    23     2:00    0    -
  {
    2023 /*from_year*/,
    2023 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2024    only    -    Mar    10     3:00    -1:00    -
  {
    2024 /*from_year*/,
    2024 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2024    only    -    Apr    14     2:00    0    -
  {
    2024 /*from_year*/,
    2024 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2025    only    -    Feb    23     3:00    -1:00    -
  {
    2025 /*from_year*/,
    2025 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2025    only    -    Apr     6     2:00    0    -
  {
    2025 /*from_year*/,
    2025 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    6 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2026    only    -    Feb    15     3:00    -1:00    -
  {
    2026 /*from_year*/,
    2026 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    15 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2026    only    -    Mar    22     2:00    0    -
  {
    2026 /*from_year*/,
    2026 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    22 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2027    only    -    Feb     7     3:00    -1:00    -
  {
    2027 /*from_year*/,
    2027 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    7 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2027    only    -    Mar    14     2:00    0    -
  {
    2027 /*from_year*/,
    2027 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2028    only    -    Jan    23     3:00    -1:00    -
  {
    2028 /*from_year*/,
    2028 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2028    only    -    Mar     5     2:00    0    -
  {
    2028 /*from_year*/,
    2028 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2029    only    -    Jan    14     3:00    -1:00    -
  {
    2029 /*from_year*/,
    2029 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2029    only    -    Feb    18     2:00    0    -
  {
    2029 /*from_year*/,
    2029 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    18 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2029    only    -    Dec    30     3:00    -1:00    -
  {
    2029 /*from_year*/,
    2029 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    30 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2030    only    -    Feb    10     2:00    0    -
  {
    2030 /*from_year*/,
    2030 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2030    only    -    Dec    22     3:00    -1:00    -
  {
    2030 /*from_year*/,
    2030 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    22 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2031    only    -    Jan    26     2:00    0    -
  {
    2031 /*from_year*/,
    2031 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    26 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2031    only    -    Dec    14     3:00    -1:00    -
  {
    2031 /*from_year*/,
    2031 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2032    only    -    Jan    18     2:00    0    -
  {
    2032 /*from_year*/,
    2032 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    18 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2032    only    -    Nov    28     3:00    -1:00    -
  {
    2032 /*from_year*/,
    2032 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2033    only    -    Jan     9     2:00    0    -
  {
    2033 /*from_year*/,
    2033 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    9 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2033    only    -    Nov    20     3:00    -1:00    -
  {
    2033 /*from_year*/,
    2033 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    20 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2033    only    -    Dec    25     2:00    0    -
  {
    2033 /*from_year*/,
    2033 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    25 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2034    only    -    Nov     5     3:00    -1:00    -
  {
    2034 /*from_year*/,
    2034 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2034    only    -    Dec    17     2:00    0    -
  {
    2034 /*from_year*/,
    2034 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    17 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2035    only    -    Oct    28     3:00    -1:00    -
  {
    2035 /*from_year*/,
    2035 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2035    only    -    Dec     9     2:00    0    -
  {
    2035 /*from_year*/,
    2035 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    9 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2036    only    -    Oct    19     3:00    -1:00    -
  {
    2036 /*from_year*/,
    2036 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2036    only    -    Nov    23     2:00    0    -
  {
    2036 /*from_year*/,
    2036 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2037    only    -    Oct     4     3:00    -1:00    -
  {
    2037 /*from_year*/,
    2037 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    4 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2037    only    -    Nov    15     2:00    0    -
  {
    2037 /*from_year*/,
    2037 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    15 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2038    only    -    Sep    26     3:00    -1:00    -
  {
    2038 /*from_year*/,
    2038 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    26 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2038    only    -    Oct    31     2:00    0    -
  {
    2038 /*from_year*/,
    2038 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    31 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2039    only    -    Sep    18     3:00    -1:00    -
  {
    2039 /*from_year*/,
    2039 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    18 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2039    only    -    Oct    23     2:00    0    -
  {
    2039 /*from_year*/,
    2039 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2040    only    -    Sep     2     3:00    -1:00    -
  {
    2040 /*from_year*/,
    2040 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2040    only    -    Oct    14     2:00    0    -
  {
    2040 /*from_year*/,
    2040 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2041    only    -    Aug    25     3:00    -1:00    -
  {
    2041 /*from_year*/,
    2041 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    25 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2041    only    -    Sep    29     2:00    0    -
  {
    2041 /*from_year*/,
    2041 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    29 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2042    only    -    Aug    10     3:00    -1:00    -
  {
    2042 /*from_year*/,
    2042 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2042    only    -    Sep    21     2:00    0    -
  {
    2042 /*from_year*/,
    2042 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    21 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2043    only    -    Aug     2     3:00    -1:00    -
  {
    2043 /*from_year*/,
    2043 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2043    only    -    Sep    13     2:00    0    -
  {
    2043 /*from_year*/,
    2043 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    13 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2044    only    -    Jul    24     3:00    -1:00    -
  {
    2044 /*from_year*/,
    2044 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    24 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2044    only    -    Aug    28     2:00    0    -
  {
    2044 /*from_year*/,
    2044 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2045    only    -    Jul     9     3:00    -1:00    -
  {
    2045 /*from_year*/,
    2045 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    9 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2045    only    -    Aug    20     2:00    0    -
  {
    2045 /*from_year*/,
    2045 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    20 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2046    only    -    Jul     1     3:00    -1:00    -
  {
    2046 /*from_year*/,
    2046 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2046    only    -    Aug     5     2:00    0    -
  {
    2046 /*from_year*/,
    2046 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2047    only    -    Jun    23     3:00    -1:00    -
  {
    2047 /*from_year*/,
    2047 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2047    only    -    Jul    28     2:00    0    -
  {
    2047 /*from_year*/,
    2047 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2048    only    -    Jun     7     3:00    -1:00    -
  {
    2048 /*from_year*/,
    2048 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    7 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2048    only    -    Jul    19     2:00    0    -
  {
    2048 /*from_year*/,
    2048 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2049    only    -    May    30     3:00    -1:00    -
  {
    2049 /*from_year*/,
    2049 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    30 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2049    only    -    Jul     4     2:00    0    -
  {
    2049 /*from_year*/,
    2049 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    4 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2050    only    -    May    15     3:00    -1:00    -
  {
    2050 /*from_year*/,
    2050 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    15 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2050    only    -    Jun    26     2:00    0    -
  {
    2050 /*from_year*/,
    2050 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    26 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2051    only    -    May     7     3:00    -1:00    -
  {
    2051 /*from_year*/,
    2051 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    7 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2051    only    -    Jun    18     2:00    0    -
  {
    2051 /*from_year*/,
    2051 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    18 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2052    only    -    Apr    28     3:00    -1:00    -
  {
    2052 /*from_year*/,
    2052 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2052    only    -    Jun     2     2:00    0    -
  {
    2052 /*from_year*/,
    2052 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2053    only    -    Apr    13     3:00    -1:00    -
  {
    2053 /*from_year*/,
    2053 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    13 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2053    only    -    May    25     2:00    0    -
  {
    2053 /*from_year*/,
    2053 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    25 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2054    only    -    Apr     5     3:00    -1:00    -
  {
    2054 /*from_year*/,
    2054 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2054    only    -    May    10     2:00    0    -
  {
    2054 /*from_year*/,
    2054 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2055    only    -    Mar    28     3:00    -1:00    -
  {
    2055 /*from_year*/,
    2055 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2055    only    -    May     2     2:00    0    -
  {
    2055 /*from_year*/,
    2055 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2056    only    -    Mar    12     3:00    -1:00    -
  {
    2056 /*from_year*/,
    2056 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    12 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2056    only    -    Apr    23     2:00    0    -
  {
    2056 /*from_year*/,
    2056 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2057    only    -    Mar     4     3:00    -1:00    -
  {
    2057 /*from_year*/,
    2057 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    4 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2057    only    -    Apr     8     2:00    0    -
  {
    2057 /*from_year*/,
    2057 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2058    only    -    Feb    17     3:00    -1:00    -
  {
    2058 /*from_year*/,
    2058 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    17 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2058    only    -    Mar    31     2:00    0    -
  {
    2058 /*from_year*/,
    2058 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    31 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2059    only    -    Feb     9     3:00    -1:00    -
  {
    2059 /*from_year*/,
    2059 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    9 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2059    only    -    Mar    23     2:00    0    -
  {
    2059 /*from_year*/,
    2059 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    23 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2060    only    -    Feb     1     3:00    -1:00    -
  {
    2060 /*from_year*/,
    2060 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2060    only    -    Mar     7     2:00    0    -
  {
    2060 /*from_year*/,
    2060 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    7 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2061    only    -    Jan    16     3:00    -1:00    -
  {
    2061 /*from_year*/,
    2061 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    16 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2061    only    -    Feb    27     2:00    0    -
  {
    2061 /*from_year*/,
    2061 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    27 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2062    only    -    Jan     8     3:00    -1:00    -
  {
    2062 /*from_year*/,
    2062 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2062    only    -    Feb    12     2:00    0    -
  {
    2062 /*from_year*/,
    2062 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    12 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2062    only    -    Dec    31     3:00    -1:00    -
  {
    2062 /*from_year*/,
    2062 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    31 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2063    only    -    Feb     4     2:00    0    -
  {
    2063 /*from_year*/,
    2063 /*to_year*/,
    2 /*in_month*/,
    0 /*on_day_of_week*/,
    4 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2063    only    -    Dec    16     3:00    -1:00    -
  {
    2063 /*from_year*/,
    2063 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    16 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2064    only    -    Jan    27     2:00    0    -
  {
    2064 /*from_year*/,
    2064 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    27 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2064    only    -    Dec     7     3:00    -1:00    -
  {
    2064 /*from_year*/,
    2064 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    7 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2065    only    -    Jan    11     2:00    0    -
  {
    2065 /*from_year*/,
    2065 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2065    only    -    Nov    22     3:00    -1:00    -
  {
    2065 /*from_year*/,
    2065 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    22 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2066    only    -    Jan     3     2:00    0    -
  {
    2066 /*from_year*/,
    2066 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    3 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2066    only    -    Nov    14     3:00    -1:00    -
  {
    2066 /*from_year*/,
    2066 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2066    only    -    Dec    26     2:00    0    -
  {
    2066 /*from_year*/,
    2066 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    26 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2067    only    -    Nov     6     3:00    -1:00    -
  {
    2067 /*from_year*/,
    2067 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    6 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2067    only    -    Dec    11     2:00    0    -
  {
    2067 /*from_year*/,
    2067 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2068    only    -    Oct    21     3:00    -1:00    -
  {
    2068 /*from_year*/,
    2068 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    21 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2068    only    -    Dec     2     2:00    0    -
  {
    2068 /*from_year*/,
    2068 /*to_year*/,
    12 /*in_month*/,
    0 /*on_day_of_week*/,
    2 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2069    only    -    Oct    13     3:00    -1:00    -
  {
    2069 /*from_year*/,
    2069 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    13 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2069    only    -    Nov    17     2:00    0    -
  {
    2069 /*from_year*/,
    2069 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    17 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2070    only    -    Oct     5     3:00    -1:00    -
  {
    2070 /*from_year*/,
    2070 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    5 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2070    only    -    Nov     9     2:00    0    -
  {
    2070 /*from_year*/,
    2070 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    9 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2071    only    -    Sep    20     3:00    -1:00    -
  {
    2071 /*from_year*/,
    2071 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    20 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2071    only    -    Nov     1     2:00    0    -
  {
    2071 /*from_year*/,
    2071 /*to_year*/,
    11 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2072    only    -    Sep    11     3:00    -1:00    -
  {
    2072 /*from_year*/,
    2072 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2072    only    -    Oct    16     2:00    0    -
  {
    2072 /*from_year*/,
    2072 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    16 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2073    only    -    Aug    27     3:00    -1:00    -
  {
    2073 /*from_year*/,
    2073 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    27 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2073    only    -    Oct     8     2:00    0    -
  {
    2073 /*from_year*/,
    2073 /*to_year*/,
    10 /*in_month*/,
    0 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2074    only    -    Aug    19     3:00    -1:00    -
  {
    2074 /*from_year*/,
    2074 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2074    only    -    Sep    30     2:00    0    -
  {
    2074 /*from_year*/,
    2074 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    30 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2075    only    -    Aug    11     3:00    -1:00    -
  {
    2075 /*from_year*/,
    2075 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2075    only    -    Sep    15     2:00    0    -
  {
    2075 /*from_year*/,
    2075 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    15 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2076    only    -    Jul    26     3:00    -1:00    -
  {
    2076 /*from_year*/,
    2076 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    26 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2076    only    -    Sep     6     2:00    0    -
  {
    2076 /*from_year*/,
    2076 /*to_year*/,
    9 /*in_month*/,
    0 /*on_day_of_week*/,
    6 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2077    only    -    Jul    18     3:00    -1:00    -
  {
    2077 /*from_year*/,
    2077 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    18 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2077    only    -    Aug    22     2:00    0    -
  {
    2077 /*from_year*/,
    2077 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    22 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2078    only    -    Jul    10     3:00    -1:00    -
  {
    2078 /*from_year*/,
    2078 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    10 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2078    only    -    Aug    14     2:00    0    -
  {
    2078 /*from_year*/,
    2078 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2079    only    -    Jun    25     3:00    -1:00    -
  {
    2079 /*from_year*/,
    2079 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    25 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2079    only    -    Aug     6     2:00    0    -
  {
    2079 /*from_year*/,
    2079 /*to_year*/,
    8 /*in_month*/,
    0 /*on_day_of_week*/,
    6 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2080    only    -    Jun    16     3:00    -1:00    -
  {
    2080 /*from_year*/,
    2080 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    16 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2080    only    -    Jul    21     2:00    0    -
  {
    2080 /*from_year*/,
    2080 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    21 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2081    only    -    Jun     1     3:00    -1:00    -
  {
    2081 /*from_year*/,
    2081 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2081    only    -    Jul    13     2:00    0    -
  {
    2081 /*from_year*/,
    2081 /*to_year*/,
    7 /*in_month*/,
    0 /*on_day_of_week*/,
    13 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2082    only    -    May    24     3:00    -1:00    -
  {
    2082 /*from_year*/,
    2082 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    24 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2082    only    -    Jun    28     2:00    0    -
  {
    2082 /*from_year*/,
    2082 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    28 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2083    only    -    May    16     3:00    -1:00    -
  {
    2083 /*from_year*/,
    2083 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    16 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2083    only    -    Jun    20     2:00    0    -
  {
    2083 /*from_year*/,
    2083 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    20 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2084    only    -    Apr    30     3:00    -1:00    -
  {
    2084 /*from_year*/,
    2084 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    30 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2084    only    -    Jun    11     2:00    0    -
  {
    2084 /*from_year*/,
    2084 /*to_year*/,
    6 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2085    only    -    Apr    22     3:00    -1:00    -
  {
    2085 /*from_year*/,
    2085 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    22 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2085    only    -    May    27     2:00    0    -
  {
    2085 /*from_year*/,
    2085 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    27 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2086    only    -    Apr    14     3:00    -1:00    -
  {
    2086 /*from_year*/,
    2086 /*to_year*/,
    4 /*in_month*/,
    0 /*on_day_of_week*/,
    14 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2086    only    -    May    19     2:00    0    -
  {
    2086 /*from_year*/,
    2086 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    19 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2087    only    -    Mar    30     3:00    -1:00    -
  {
    2087 /*from_year*/,
    2087 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    30 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    -60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    Morocco    2087    only    -    May    11     2:00    0    -
  {
    2087 /*from_year*/,
    2087 /*to_year*/,
    5 /*in_month*/,
    0 /*on_day_of_week*/,
    11 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyMorocco  = {
  kAtcZoneRulesMorocco /*rules*/,
  170 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: Namibia
// Rules: 4
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesNamibia[]  = {
  // Anchor: Rule    Namibia    1994    2017    -    Sep    Sun>=1    2:00    0    CAT
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    1 /*letterIndex ("CAT")*/,
  },
  // Rule    Namibia    1994    only    -    Mar    21    0:00    -1:00    WAT
  {
    1994 /*from_year*/,
    1994 /*to_year*/,
    3 /*in_month*/,
    0 /*on_day_of_week*/,
    21 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    -60 /*delta_minutes*/,
    4 /*letterIndex ("WAT")*/,
  },
  // Rule    Namibia    1994    2017    -    Sep    Sun>=1    2:00    0    CAT
  {
    1994 /*from_year*/,
    2017 /*to_year*/,
    9 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    1 /*letterIndex ("CAT")*/,
  },
  // Rule    Namibia    1995    2017    -    Apr    Sun>=1    2:00    -1:00    WAT
  {
    1995 /*from_year*/,
    2017 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    -60 /*delta_minutes*/,
    4 /*letterIndex ("WAT")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyNamibia  = {
  kAtcZoneRulesNamibia /*rules*/,
  4 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: US
// Rules: 6
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesUS[]  = {
  // Anchor: Rule    US    1967    2006    -    Oct    lastSun    2:00    0    S
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    US    1967    2006    -    Oct    lastSun    2:00    0    S
  {
    1967 /*from_year*/,
    2006 /*to_year*/,
    10 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    US    1976    1986    -    Apr    lastSun    2:00    1:00    D
  {
    1976 /*from_year*/,
    1986 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    US    1987    2006    -    Apr    Sun>=1    2:00    1:00    D
  {
    1987 /*from_year*/,
    2006 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    US    2007    max    -    Mar    Sun>=8    2:00    1:00    D
  {
    2007 /*from_year*/,
    32766 /*to_year*/,
    3 /*in_month*/,
    7 /*on_day_of_week*/,
    8 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    US    2007    max    -    Nov    Sun>=1    2:00    0    S
  {
    2007 /*from_year*/,
    32766 /*to_year*/,
    11 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyUS  = {
  kAtcZoneRulesUS /*rules*/,
  6 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: WS
// Rules: 6
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesWS[]  = {
  // Anchor: Rule    WS    2011    only    -    Apr    Sat>=1    4:00    0    -
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    WS    2010    only    -    Sep    lastSun    0:00    1    -
  {
    2010 /*from_year*/,
    2010 /*to_year*/,
    9 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    WS    2011    only    -    Apr    Sat>=1    4:00    0    -
  {
    2011 /*from_year*/,
    2011 /*to_year*/,
    4 /*in_month*/,
    6 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    960 /*at_time_code (14400/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    WS    2011    only    -    Sep    lastSat    3:00    1    -
  {
    2011 /*from_year*/,
    2011 /*to_year*/,
    9 /*in_month*/,
    6 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    WS    2012    2021    -    Apr    Sun>=1    4:00    0    -
  {
    2012 /*from_year*/,
    2021 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    960 /*at_time_code (14400/15)*/,
    0 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },
  // Rule    WS    2012    2020    -    Sep    lastSun    3:00    1    -
  {
    2012 /*from_year*/,
    2020 /*to_year*/,
    9 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    720 /*at_time_code (10800/15)*/,
    60 /*delta_minutes*/,
    0 /*letterIndex ("")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyWS  = {
  kAtcZoneRulesWS /*rules*/,
  6 /*num_rules*/,
};

//---------------------------------------------------------------------------
// Policy name: Winn
// Rules: 4
//---------------------------------------------------------------------------

static const AtcZoneRule kAtcZoneRulesWinn[]  = {
  // Anchor: Rule    Winn    1966    2005    -    Oct    lastSun    2:00s    0    S
  {
    -32767 /*from_year*/,
    -32767 /*to_year*/,
    1 /*in_month*/,
    0 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    0 /*at_time_modifier (kAtcSuffixW + seconds=0)*/,
    0 /*at_time_code (0/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    Winn    1966    1986    -    Apr    lastSun    2:00s    1:00    D
  {
    1966 /*from_year*/,
    1986 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    16 /*at_time_modifier (kAtcSuffixS + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },
  // Rule    Winn    1966    2005    -    Oct    lastSun    2:00s    0    S
  {
    1966 /*from_year*/,
    2005 /*to_year*/,
    10 /*in_month*/,
    7 /*on_day_of_week*/,
    0 /*on_day_of_month*/,
    16 /*at_time_modifier (kAtcSuffixS + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    0 /*delta_minutes*/,
    3 /*letterIndex ("S")*/,
  },
  // Rule    Winn    1987    2005    -    Apr    Sun>=1    2:00s    1:00    D
  {
    1987 /*from_year*/,
    2005 /*to_year*/,
    4 /*in_month*/,
    7 /*on_day_of_week*/,
    1 /*on_day_of_month*/,
    16 /*at_time_modifier (kAtcSuffixS + seconds=0)*/,
    480 /*at_time_code (7200/15)*/,
    60 /*delta_minutes*/,
    2 /*letterIndex ("D")*/,
  },

};

const AtcZonePolicy kAtcTestingZonePolicyWinn  = {
  kAtcZoneRulesWinn /*rules*/,
  4 /*num_rules*/,
};


