// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/acetimec/src/zonedbtesting/tzfiles
//     --output_dir /home/brian/src/acetimec/src/zonedbtesting
//     --tz_version 2023c
//     --action zonedb
//     --language c
//     --scope complete
//     --db_namespace AtcTesting
//     --start_year 2000
//     --until_year 10000
//     --nocompress
//     --include_list include_list.txt
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2023c
//
// Supported Zones: 17 (16 zones, 1 links)
// Unsupported Zones: 579 (334 zones, 245 links)
//
// Original Years:  [1844,2087]
// Generated Years: [1966,2087]
// Estimator Years: [1966,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 17
//   Eras: 22
//   Policies: 8
//   Rules: 201
//
// Memory (8-bits):
//   Rules: 2412
//   Policies: 24
//   Eras: 330
//   Zones: 208
//   Links: 13
//   Registry: 34
//   Formats: 78
//   Letters: 23
//   Fragments: 0
//   Names: 268 (original: 268)
//   TOTAL: 3390
//
// Memory (32-bits):
//   Rules: 2412
//   Policies: 64
//   Eras: 440
//   Zones: 384
//   Links: 24
//   Registry: 68
//   Formats: 78
//   Letters: 33
//   Fragments: 0
//   Names: 268 (original: 268)
//   TOTAL: 3771
//
// DO NOT EDIT

#include "zone_policies.h"
#include "zone_infos.h"

//---------------------------------------------------------------------------
// ZoneContext (should not be in PROGMEM)
//---------------------------------------------------------------------------

static const char kAtcTzDatabaseVersion[] = "2023c";

static const char * const kAtcFragments[] = {
/*\x00*/ NULL,

};

static const char* const kAtcLetters[] = {
/*0*/ "",
/*1*/ "CAT",
/*2*/ "D",
/*3*/ "S",
/*4*/ "WAT",

};

const AtcZoneContext kAtcTestingZoneContext = {
  2000 /*start_year*/,
  10000 /*until_year*/,
  7 /*max_transitions*/,
  kAtcTzDatabaseVersion /*tz_version*/,
  1 /*num_fragments*/,
  5 /*num_letters*/,
  kAtcFragments /*fragments*/,
  kAtcLetters /*letters*/,
};

//---------------------------------------------------------------------------
// Zones: 16
// Eras: 22
//---------------------------------------------------------------------------

//---------------------------------------------------------------------------
// Zone name: Africa/Casablanca
// Zone Eras: 2
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAfrica_Casablanca[]  = {
  //              0:00    Morocco    +00/+01    2018 Oct 28  3:00
  {
    &kAtcTestingZonePolicyMorocco /*zone_policy*/,
    "+00/+01" /*format*/,
    0 /*offset_code (0/15)*/,
    0 /*offset_remainder (0%15)*/,
    0 /*delta_minutes*/,
    2018 /*until_year*/,
    10 /*until_month*/,
    28 /*until_day*/,
    720 /*until_time_code (10800/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },
  //              1:00    Morocco    +01/+00
  {
    &kAtcTestingZonePolicyMorocco /*zone_policy*/,
    "+01/+00" /*format*/,
    240 /*offset_code (3600/15)*/,
    0 /*offset_remainder (3600%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAfrica_Casablanca[]  = "Africa/Casablanca";

const AtcZoneInfo kAtcTestingZoneAfrica_Casablanca  = {
  kAtcZoneNameAfrica_Casablanca /*name*/,
  0xc59f1b33 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  2 /*num_eras*/,
  kAtcZoneEraAfrica_Casablanca /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: Africa/Windhoek
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAfrica_Windhoek[]  = {
  //             2:00    Namibia    %s
  {
    &kAtcTestingZonePolicyNamibia /*zone_policy*/,
    "%" /*format*/,
    480 /*offset_code (7200/15)*/,
    0 /*offset_remainder (7200%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAfrica_Windhoek[]  = "Africa/Windhoek";

const AtcZoneInfo kAtcTestingZoneAfrica_Windhoek  = {
  kAtcZoneNameAfrica_Windhoek /*name*/,
  0x789c9bd3 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAfrica_Windhoek /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Caracas
// Zone Eras: 3
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Caracas[]  = {
  //             -4:00    -    -04    2007 Dec  9  3:00
  {
    NULL /*zone_policy*/,
    "-04" /*format*/,
    -960 /*offset_code (-14400/15)*/,
    0 /*offset_remainder (-14400%15)*/,
    0 /*delta_minutes*/,
    2007 /*until_year*/,
    12 /*until_month*/,
    9 /*until_day*/,
    720 /*until_time_code (10800/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },
  //             -4:30    -    -0430    2016 May  1  2:30
  {
    NULL /*zone_policy*/,
    "-0430" /*format*/,
    -1080 /*offset_code (-16200/15)*/,
    0 /*offset_remainder (-16200%15)*/,
    0 /*delta_minutes*/,
    2016 /*until_year*/,
    5 /*until_month*/,
    1 /*until_day*/,
    600 /*until_time_code (9000/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },
  //             -4:00    -    -04
  {
    NULL /*zone_policy*/,
    "-04" /*format*/,
    -960 /*offset_code (-14400/15)*/,
    0 /*offset_remainder (-14400%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Caracas[]  = "America/Caracas";

const AtcZoneInfo kAtcTestingZoneAmerica_Caracas  = {
  kAtcZoneNameAmerica_Caracas /*name*/,
  0x3be064f4 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  3 /*num_eras*/,
  kAtcZoneEraAmerica_Caracas /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Chicago
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Chicago[]  = {
  //             -6:00    US    C%sT
  {
    &kAtcTestingZonePolicyUS /*zone_policy*/,
    "C%T" /*format*/,
    -1440 /*offset_code (-21600/15)*/,
    0 /*offset_remainder (-21600%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Chicago[]  = "America/Chicago";

const AtcZoneInfo kAtcTestingZoneAmerica_Chicago  = {
  kAtcZoneNameAmerica_Chicago /*name*/,
  0x4b92b5d4 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Chicago /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Denver
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Denver[]  = {
  //             -7:00    US    M%sT
  {
    &kAtcTestingZonePolicyUS /*zone_policy*/,
    "M%T" /*format*/,
    -1680 /*offset_code (-25200/15)*/,
    0 /*offset_remainder (-25200%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Denver[]  = "America/Denver";

const AtcZoneInfo kAtcTestingZoneAmerica_Denver  = {
  kAtcZoneNameAmerica_Denver /*name*/,
  0x97d10b2a /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Denver /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Edmonton
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Edmonton[]  = {
  //             -7:00    Canada    M%sT
  {
    &kAtcTestingZonePolicyCanada /*zone_policy*/,
    "M%T" /*format*/,
    -1680 /*offset_code (-25200/15)*/,
    0 /*offset_remainder (-25200%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Edmonton[]  = "America/Edmonton";

const AtcZoneInfo kAtcTestingZoneAmerica_Edmonton  = {
  kAtcZoneNameAmerica_Edmonton /*name*/,
  0x6cb9484a /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Edmonton /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Los_Angeles
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Los_Angeles[]  = {
  //             -8:00    US    P%sT
  {
    &kAtcTestingZonePolicyUS /*zone_policy*/,
    "P%T" /*format*/,
    -1920 /*offset_code (-28800/15)*/,
    0 /*offset_remainder (-28800%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Los_Angeles[]  = "America/Los_Angeles";

const AtcZoneInfo kAtcTestingZoneAmerica_Los_Angeles  = {
  kAtcZoneNameAmerica_Los_Angeles /*name*/,
  0xb7f7e8f2 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Los_Angeles /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/New_York
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_New_York[]  = {
  //             -5:00    US    E%sT
  {
    &kAtcTestingZonePolicyUS /*zone_policy*/,
    "E%T" /*format*/,
    -1200 /*offset_code (-18000/15)*/,
    0 /*offset_remainder (-18000%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_New_York[]  = "America/New_York";

const AtcZoneInfo kAtcTestingZoneAmerica_New_York  = {
  kAtcZoneNameAmerica_New_York /*name*/,
  0x1e2a7654 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_New_York /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Toronto
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Toronto[]  = {
  //             -5:00    Canada    E%sT
  {
    &kAtcTestingZonePolicyCanada /*zone_policy*/,
    "E%T" /*format*/,
    -1200 /*offset_code (-18000/15)*/,
    0 /*offset_remainder (-18000%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Toronto[]  = "America/Toronto";

const AtcZoneInfo kAtcTestingZoneAmerica_Toronto  = {
  kAtcZoneNameAmerica_Toronto /*name*/,
  0x792e851b /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Toronto /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Vancouver
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Vancouver[]  = {
  //             -8:00    Canada    P%sT
  {
    &kAtcTestingZonePolicyCanada /*zone_policy*/,
    "P%T" /*format*/,
    -1920 /*offset_code (-28800/15)*/,
    0 /*offset_remainder (-28800%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Vancouver[]  = "America/Vancouver";

const AtcZoneInfo kAtcTestingZoneAmerica_Vancouver  = {
  kAtcZoneNameAmerica_Vancouver /*name*/,
  0x2c6f6b1f /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Vancouver /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Whitehorse
// Zone Eras: 2
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Whitehorse[]  = {
  //             -8:00    Canada    P%sT    2020 Nov  1
  {
    &kAtcTestingZonePolicyCanada /*zone_policy*/,
    "P%T" /*format*/,
    -1920 /*offset_code (-28800/15)*/,
    0 /*offset_remainder (-28800%15)*/,
    0 /*delta_minutes*/,
    2020 /*until_year*/,
    11 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },
  //             -7:00    -    MST
  {
    NULL /*zone_policy*/,
    "MST" /*format*/,
    -1680 /*offset_code (-25200/15)*/,
    0 /*offset_remainder (-25200%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Whitehorse[]  = "America/Whitehorse";

const AtcZoneInfo kAtcTestingZoneAmerica_Whitehorse  = {
  kAtcZoneNameAmerica_Whitehorse /*name*/,
  0x54e0e3e8 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  2 /*num_eras*/,
  kAtcZoneEraAmerica_Whitehorse /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: America/Winnipeg
// Zone Eras: 2
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAmerica_Winnipeg[]  = {
  //             -6:00    Winn    C%sT    2006
  {
    &kAtcTestingZonePolicyWinn /*zone_policy*/,
    "C%T" /*format*/,
    -1440 /*offset_code (-21600/15)*/,
    0 /*offset_remainder (-21600%15)*/,
    0 /*delta_minutes*/,
    2006 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },
  //             -6:00    Canada    C%sT
  {
    &kAtcTestingZonePolicyCanada /*zone_policy*/,
    "C%T" /*format*/,
    -1440 /*offset_code (-21600/15)*/,
    0 /*offset_remainder (-21600%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAmerica_Winnipeg[]  = "America/Winnipeg";

const AtcZoneInfo kAtcTestingZoneAmerica_Winnipeg  = {
  kAtcZoneNameAmerica_Winnipeg /*name*/,
  0x8c7dafc7 /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  2 /*num_eras*/,
  kAtcZoneEraAmerica_Winnipeg /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: Australia/Darwin
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraAustralia_Darwin[]  = {
  //              9:30    Aus    AC%sT
  {
    &kAtcTestingZonePolicyAus /*zone_policy*/,
    "AC%T" /*format*/,
    2280 /*offset_code (34200/15)*/,
    0 /*offset_remainder (34200%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameAustralia_Darwin[]  = "Australia/Darwin";

const AtcZoneInfo kAtcTestingZoneAustralia_Darwin  = {
  kAtcZoneNameAustralia_Darwin /*name*/,
  0x2876bdff /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAustralia_Darwin /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: Etc/UTC
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraEtc_UTC[]  = {
  // 0 - UTC
  {
    NULL /*zone_policy*/,
    "UTC" /*format*/,
    0 /*offset_code (0/15)*/,
    0 /*offset_remainder (0%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameEtc_UTC[]  = "Etc/UTC";

const AtcZoneInfo kAtcTestingZoneEtc_UTC  = {
  kAtcZoneNameEtc_UTC /*name*/,
  0xd8e31abc /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraEtc_UTC /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: Europe/Lisbon
// Zone Eras: 1
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraEurope_Lisbon[]  = {
  //              0:00    EU    WE%sT
  {
    &kAtcTestingZonePolicyEU /*zone_policy*/,
    "WE%T" /*format*/,
    0 /*offset_code (0/15)*/,
    0 /*offset_remainder (0%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNameEurope_Lisbon[]  = "Europe/Lisbon";

const AtcZoneInfo kAtcTestingZoneEurope_Lisbon  = {
  kAtcZoneNameEurope_Lisbon /*name*/,
  0x5c00a70b /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraEurope_Lisbon /*eras*/,
  NULL /*target_info*/,
};

//---------------------------------------------------------------------------
// Zone name: Pacific/Apia
// Zone Eras: 2
//---------------------------------------------------------------------------

static const AtcZoneEra kAtcZoneEraPacific_Apia[]  = {
  //             -11:00    WS    -11/-10    2011 Dec 29 24:00
  {
    &kAtcTestingZonePolicyWS /*zone_policy*/,
    "-11/-10" /*format*/,
    -2640 /*offset_code (-39600/15)*/,
    0 /*offset_remainder (-39600%15)*/,
    0 /*delta_minutes*/,
    2011 /*until_year*/,
    12 /*until_month*/,
    29 /*until_day*/,
    5760 /*until_time_code (86400/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },
  //              13:00    WS    +13/+14
  {
    &kAtcTestingZonePolicyWS /*zone_policy*/,
    "+13/+14" /*format*/,
    3120 /*offset_code (46800/15)*/,
    0 /*offset_remainder (46800%15)*/,
    0 /*delta_minutes*/,
    32767 /*until_year*/,
    1 /*until_month*/,
    1 /*until_day*/,
    0 /*until_time_code (0/15)*/,
    0 /*until_time_modifier (kAtcSuffixW + seconds=0)*/,
  },

};

static const char kAtcZoneNamePacific_Apia[]  = "Pacific/Apia";

const AtcZoneInfo kAtcTestingZonePacific_Apia  = {
  kAtcZoneNamePacific_Apia /*name*/,
  0x23359b5e /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  2 /*num_eras*/,
  kAtcZoneEraPacific_Apia /*eras*/,
  NULL /*target_info*/,
};



//---------------------------------------------------------------------------
// Links: 1
//---------------------------------------------------------------------------

//---------------------------------------------------------------------------
// Link name: US/Pacific -> America/Los_Angeles
//---------------------------------------------------------------------------

static const char kAtcZoneNameUS_Pacific[]  = "US/Pacific";

const AtcZoneInfo kAtcTestingZoneUS_Pacific  = {
  kAtcZoneNameUS_Pacific /*name*/,
  0xa950f6ab /*zone_id*/,
  &kAtcTestingZoneContext /*zone_context*/,
  1 /*num_eras*/,
  kAtcZoneEraAmerica_Los_Angeles /*eras*/,
  &kAtcTestingZoneAmerica_Los_Angeles /*target_info*/,
};


